Repository eventespresso/event-espresso-core, pull requests merged in 2018-04, with the labels that each got.

#291 add generatePropertyOrKeyName(); [touch: 11482]
  tests/testcases/core/EE_Encryption_Test.php
Labels: bug, has codebase ticket

#290 add getJsUrl and getCssUrl helpers for retrieving asset urls
  core/services/assets/Registry.php
Labels: enhancement, gutenberg

#298 Move Github Meta files and tweak templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  ISSUE_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
  info.json
Labels: documentation, enhancement

#305 Switch to wp_add_inline_script from wp_localize_script for eejs.data api
  .travis.yml
  core/espresso_definitions.php
  core/services/assets/Registry.php
  tests/includes/EE_REST_TestCase.php
Labels: category:assets, type:build-process, type:enhancement

#314 Bug/11502/failing uni tests with wp 45
  modules/core_rest_api/EED_Core_Rest_Api.module.php
Labels: category:unit-tests, status:review

#300 Fix broken boolean indicator for whether the pricing metabox is being loaded for an event being created or not. (fixes #297)
  caffeinated/admin/new/pricing/espresso_events_Pricing_Hooks.class.php
Labels: status:merge, type:bug

#302 Fet/11498/allow disabling form inputs
  core/libraries/form_sections/inputs/EE_Form_Input_Base.input.php
Labels: category:forms-systems

#292 Fet/11481/extract custom post types
  assets/dist/build-manifest.json
  assets/dist/ee-eejs.46337f785c8714cdb33d.dist.js
  assets/dist/ee-eejs.a8ec0e900bc29c599579.dist.js
  assets/dist/ee-manifest.f5984092809447a8fba8.dist.js
  assets/dist/ee-reactVendor.35171c34ad0ef06233a0.dist.js
  assets/dist/ee-reactVendor.b5799c8665b24642d1cd.dist.js
  assets/dist/ee-wp-plugins-page.2260f8293749cc2eb3fc.dist.js
  assets/dist/ee-wp-plugins-page.6ce1ef98b3b927daed4f331f6930ee17.dist.css
  assets/dist/ee-wp-plugins-page.d4baf8b080ddc71432aa.dist.js
  caffeinated/admin/extend/events/Extend_Events_Admin_Page.core.php
  caffeinated/brewing_regular.php
  core/CPTs/CptQueryModifier.php
  core/CPTs/EE_CPT_Strategy.core.php
  core/CPTs/EE_Register_CPTs.core.php
  core/EE_Addon.core.php
  core/EE_Dependency_Map.core.php
  core/EE_Front_Controller.core.php
  core/EE_System.core.php
  core/admin/EE_Admin.core.php
  core/admin/EE_Admin_Page_CPT.core.php
  core/domain/entities/custom_post_types/CustomPostTypeDefinitions.php
  core/domain/entities/custom_post_types/CustomTaxonomyDefinitions.php
  core/domain/entities/custom_post_types/CustomTaxonomyTerm.php
  core/domain/services/custom_post_types/RegisterCustomPostTypes.php
  core/domain/services/custom_post_types/RegisterCustomTaxonomies.php
  core/domain/services/custom_post_types/RegisterCustomTaxonomyTerms.php
  core/domain/services/custom_post_types/RewriteRules.php
  core/helpers/EEH_Activation.helper.php
  core/helpers/EEH_Debug_Tools.helper.php
  core/helpers/EEH_Template.helper.php
  core/libraries/plugin_api/EE_Register_CPT.lib.php
  modules/event_single/EED_Event_Single.module.php
  modules/events_archive/EED_Events_Archive.module.php
  modules/venue_single/EED_Venue_Single.module.php
  modules/venues_archive/EED_Venues_Archive.module.php
Labels: category:gutenberg, category:has-codebase-ticket, status:review, type:enhancement

#343 NO EVENT TYPES FOR YOU !!!
  core/domain/services/custom_post_types/RegisterCustomPostTypes.php
  core/domain/services/custom_post_types/RegisterCustomTaxonomies.php
  tests/mocks/core/domain/services/custom_post_types/RegisterCustomPostTypesMock.php
  tests/mocks/core/domain/services/custom_post_types/RegisterCustomTaxonomiesMock.php
  tests/testcases/core/domain/services/custom_post_types/RegisterCustomPostTypesTest.php
  tests/testcases/core/domain/services/custom_post_types/RegisterCustomTaxonomiesTest.php
Labels: category:core-plugin, priority:high, status:review, type:bug

#359 Improve tests to allow passes when times are within one minute (fixes #341)
  tests/testcases/core/db_models/EEM_Base_Test.php
  tests/testcases/core/libraries/rest_api/ModelDataTranslatorTest.php
Labels: category:unit-tests, status:review, type:bug, type:build-process

#361 Configure wp global so its aliased to external packages in webpack
  webpack.common.js
Labels: status:review, type:build-process, type:enhancement

#374 Remove empty index.js and add .gitignore
  assets/src/blocks/common/.gitignore
  assets/src/blocks/common/index.js
  assets/src/blocks/editor/.gitignore
  assets/src/blocks/editor/index.js
  assets/src/blocks/index.js
  assets/src/blocks/shortcodes/.gitignore
  assets/src/blocks/shortcodes/index.js
  assets/src/blocks/widgets/.gitignore
  assets/src/blocks/widgets/index.js
  assets/src/editor/.gitignore
  assets/src/editor/index.js
  webpack.common.js
Labels: category:assets, status:review, type:build-process, type:enhancement
