Repository eventespresso/event-espresso-core, pull requests merged in 2018-07, with the labels that each got.

#563 Add classname to the markup that wraps the Event phone
  public/Espresso_Arabica_2014/content-espresso_events-details.php
Labels: status:merge

#564 Expose models on eejs (Gutenberg)
  assets/dist/build-manifest.json
  assets/dist/ee-model.a3f18c4fad21e24ab2a1.dist.js
  core/domain/services/assets/CoreAssetManager.php
  docs/AA--Javascript-in-EE/eejs-module.md
  package-lock.json
  webpack.common.js
  webpack.prod.js
Labels: category:assets, category:gutenberg, type:build-process 🔨

#566 Improve status model constants
  assets/src/components/form/select/model-selects/status.js
  assets/src/data/model/registration/constants.js
  assets/src/data/model/registration/query.js
  assets/src/data/model/status/constants.js
Labels: category:assets, category:gutenberg, category:models-and-data-infrastructure, type:enhancement 🎉

#565 Allow for querying attendees by registration ID in js attendee model.
  assets/src/data/model/attendee/index.js
  assets/src/data/model/attendee/test/index.js
Labels: category:assets, category:gutenberg, category:models-and-data-infrastructure, type:enhancement 🎉

#560 Bug/rest api between operator bad expectations
  CHANGELOG.md
  core/libraries/rest_api/ModelDataTranslator.php
  docs/C--REST-API/ee4-rest-api-GET-calculated-fields.md
  docs/C--REST-API/ee4-rest-api-GET-filtering-results.md
  docs/C--REST-API/ee4-rest-api-GET-including-specific-fields-and-related-entities-in-results.md
  docs/C--REST-API/ee4-rest-api-GET-response-headers.md
  docs/C--REST-API/ee4-rest-api-introduction.md
  docs/C--REST-API/ee4-rest-api-reading-data.md
  docs/C--REST-API/ee4-rest-api-writing-data.md
  docs/D--Addon-API/extending-ee4-rest-api.md
  docs/T--Tutorials/ee4-rest-api-code-examples.md
  tests/testcases/core/libraries/rest_api/ModelDataTranslatorTest.php
Labels: category:models-and-data-infrastructure, status:merge, type:bug 🐞

#567 Gdpr/phone not remoevd
  CHANGELOG.md
  core/domain/services/admin/privacy/erasure/EraseAttendeeData.php
Labels: category:GDPR, status:needs-testing, type:bug 🐞

#572 Add bulletproofing styles for Ticket Selector
  modules/ticket_selector/assets/ticket_selector.css
Labels: status:merge

#571 Check get_user_locale() exists before attempting to use it, compatibility fix for WP4.5
  CHANGELOG.md
  core/services/assets/I18nRegistry.php
Labels: status:merge

#583 Show attendees when specifying an archived ticket
  core/domain/entities/shortcodes/EspressoEventAttendees.php
Labels: add-changelog, status:merge

#581 Force curl to use TLS1.2 when connecting to PayPal.
  core/EE_Payment_Processor.core.php
Labels: priority:high, status:feedback-needed

#588 fix typo in action hook name
  core/EE_Deprecated.core.php
Labels: status:review

#587 if node_modules is a symlink, ignore it too
  .gitignore
Labels: category:general, status:review, type:task ✅

#592 even if the ee_error_js is already enqueued, we should still localize… Fixes #589
  CHANGELOG.md
  core/EE_Error.core.php
Labels: category:admin-page-ui-&-ux, status:review, type:bug 🐞

#596 add changelogs to skeleton addons
  CHANGELOG.md
  docs/A--Best-Practices/change-log.md
  tests/mocks/addons/eea-new-addon/CHANGELOG.md
  tests/mocks/addons/new-messages-template-pack-variation/CHANGELOG.md
  tests/mocks/addons/new-messages-template-pack/CHANGELOG.md
  tests/mocks/addons/new-payment-method/CHANGELOG.md
Labels: category:3rd-party-integrations, category:general, category:unit-tests, status:review, type:feature-request 🙏

#599 Enable Webpack CSS loading for Components
  core/domain/services/assets/CoreAssetManager.php
  webpack.common.js
Labels: category:assets, category:gutenberg, priority:high, status:review, type:build-process 🔨, type:enhancement 🎉

#590 Tweak capability checks to allow readonly for registration form answers
  admin_pages/registrations/Registrations_Admin_Page.core.php
  admin_pages/registrations/form_sections/EE_Registration_Custom_Questions_Form.form.php
  admin_pages/registrations/templates/reg_admin_details_main_meta_box_reg_questions.template.php
Labels: status:merge

#600 just always load template tags to avoid problems in page builders
  CHANGELOG.md
  core/EE_System.core.php
Labels: category:3rd-party-integrations, status:merge, type:bug 🐞

#601 render_callback needs to be a callable
  core/domain/entities/editor/Block.php
Labels: category:gutenberg, status:review, type:enhancement 🎉

#536 Bug/sold out events not in rest api #527
  CHANGELOG.md
  core/db_models/strategies/EE_Restriction_Generator_Base.strategy.php
  core/db_models/strategies/EE_Restriction_Generator_Default_Public.strategy.php
  core/db_models/strategies/EE_Restriction_Generator_Event_Related_Protected.strategy.php
  core/db_models/strategies/EE_Restriction_Generator_Event_Related_Public.strategy.php
  core/db_models/strategies/EE_Restriction_Generator_Public.strategy.php
  tests/testcases/core/libraries/rest_api/controllers/Read_Test.php
Labels: category:models-and-data-infrastructure, status:feedback-needed, type:bug 🐞

#603 sync labels to ee private
  .github/label-sync.yml
Labels: status:review, type:build-process 🔨

#612 show the pretty description of the venue, not the awful one
  CHANGELOG.md
  core/helpers/EEH_Venue_View.helper.php
Labels: category:frontend-ui-&-ux, status:merge, type:bug 🐞

#602 Add Calculated Fields class for Attendee model
  core/libraries/rest_api/CalculatedModelFields.php
  core/libraries/rest_api/calculations/Attendee.php
Labels: category:models-and-data-infrastructure, status:review, type:enhancement 🎉
