Repository eventespresso/event-espresso-core, pull requests merged in 2018-11, with the labels that each got.

#749 Populate States/Provinces for the "Your Organization" tab Country input Fixes #739
  admin_pages/general_settings/General_Settings_Admin_Page.core.php
  admin_pages/general_settings/OrganizationSettings.php
  core/EE_Config.core.php
  core/EE_Dependency_Map.core.php
  core/admin/EE_Admin_Page.core.php
  core/libraries/form_sections/inputs/EE_Country_Select_Input.php
  core/libraries/form_sections/inputs/EE_State_Select_Input.php
  core/services/address/CountrySubRegionDao.php
  core/services/validators/JsonValidator.php
Labels: category:admin-page-ui-&-ux, status:merge, type:enhancement 🎉

#768 Improve PhpStorm code assistance on aliased javascript imports
  docs/A--Best-Practices/code-style-tools-resources.md
  docs/A--Best-Practices/javascript-coding-assistance-in-phpstorm.md
  phpstorm-webpack.config.js
Labels: category:gutenberg, type:build-process 🔨, type:enhancement 🎉

#774 Restored the ability to change PDF paper size
  core/libraries/messages/messenger/EE_Pdf_messenger.class.php
Labels: priority:high, status:merge, type:bug 🐞

#771 Fix session not saving after clearing notices Fixes #770
  core/EE_Session.core.php
Labels: category:core-plugin, priority:high, status:merge, type:bug 🐞

#775 Make adjustments to tag list and update version numbers
  readme.txt
Labels: status:merge

#782 Fix bug with template pack switching
  admin_pages/messages/Messages_Admin_Page.core.php
  core/helpers/EEH_MSG_Template.helper.php
Labels: category:messaging-&-messengers, type:bug 🐞

#783 Add fail safe for loading of the network core config
  core/EE_Network_Config.core.php
  core/EE_Registry.core.php
Labels: category:core-plugin, status:merge, type:enhancement 🎉

#786 Fixed Datetime Filter Radio Input Values Fixes #785
  modules/ticket_selector/assets/ticket_selector.js
Labels: category:spco-&-registration, priority:high, type:bug 🐞

#784 Fet/simplify rest api passing in arrays
  core/libraries/rest_api/ModelDataTranslator.php
  core/libraries/rest_api/RestIncomingQueryParamContext.php
  core/libraries/rest_api/RestIncomingQueryParamMetadata.php
  core/libraries/rest_api/controllers/Base.php
  docs/C--REST-API/ee4-rest-api-GET-filtering-results.md
  docs/C--REST-API/rest-api-changelog.md
  modules/core_rest_api/EED_Core_Rest_Api.module.php
  tests/testcases/core/libraries/rest_api/ModelDataTranslatorTest.php
  tests/testcases/core/services/validators/URLValidatorTest.php
Labels: category:models-and-data-infrastructure, status:merge, type:feature-request 🙏

#791 Fix incorrect dependency on `wp-api-request` in our asset registration
  core/domain/services/assets/CoreAssetManager.php
Labels: category:assets, category:gutenberg, type:bug 🐞

#792 fix potential for PHP fatal in PHP7.2+ boxes
  core/third_party_libs/pue/pue-client.php
Labels: category:pue-uxip-and-licensing, type:bug 🐞

#793 Add shim for get_user_locale
  core/wordpress-shims.php
Labels: category:general, type:bug 🐞

#797 Up the requirements in the readme.txt
  readme.txt
Labels: type:bug 🐞

#802 move php docs for $query_params on EEM_Base::get_all to documentation
  admin_pages/registration_form/Registration_Form_Admin_Page.core.php
  admin_pages/registrations/Registrations_Admin_Page.core.php
  caffeinated/admin/extend/registrations/Extend_Registrations_Admin_Page.core.php
  core/db_classes/EE_Base_Class.class.php
  core/db_classes/EE_Datetime.class.php
  core/db_classes/EE_Event.class.php
  core/db_classes/EE_Export.class.php
  core/db_classes/EE_Message_Template_Group.class.php
  core/db_classes/EE_Payment.class.php
  core/db_classes/EE_Registration.class.php
  core/db_classes/EE_Ticket.class.php
  core/db_classes/EE_Transaction.class.php
  core/db_classes/EE_Venue.class.php
  core/db_models/EEM_Base.model.php
  core/db_models/EEM_CPT_Base.model.php
  core/db_models/EEM_Change_Log.model.php
  core/db_models/EEM_Currency.model.php
  core/db_models/EEM_Datetime.model.php
  core/db_models/EEM_Line_Item.model.php
  core/db_models/EEM_Message_Template_Group.model.php
  core/db_models/EEM_Payment_Method.model.php
  core/db_models/EEM_Registration.model.php
  core/db_models/EEM_Soft_Delete_Base.model.php
  core/db_models/EEM_Term_Relationship.model.php
  core/db_models/relations/EE_Belongs_To_Relation.php
  core/db_models/relations/EE_Has_Many_Revision_Relation.php
  core/db_models/relations/EE_Model_Relation_Base.php
  core/db_models/strategies/EE_CPT_Minimum_Where_Conditions.strategy.php
  core/db_models/strategies/EE_CPT_Where_Conditions.strategy.php
  core/db_models/strategies/EE_Default_Where_Conditions.strategy.php
  core/db_models/strategies/EE_Restriction_Generator_Base.strategy.php
  core/db_models/strategies/EE_Soft_Delete_Where_Conditions.strategy.php
  core/libraries/form_sections/strategies/validation/EE_Model_Matching_Query_Validation_Strategy.strategy.php
  core/libraries/rest_api/ModelDataTranslator.php
  core/libraries/rest_api/controllers/model/Read.php
  docs/G--Model-System/README.md
  docs/G--Model-System/model-query-params.md
  docs/G--Model-System/model-querying.md
Labels: category:models-and-data-infrastructure, status:review, type:documentation 📖

#800 use default_avatar option instead of hardcoding in “Mystery Man”
  core/libraries/rest_api/calculations/Attendee.php
  ui/blocks/event-attendees.php
Labels: category:gutenberg, status:merge
