Repository eventespresso/event-espresso-core, pull requests merged in 2019-08, with the labels that each got.

#1463 Run PHP 5.5 Travis builds on Ubuntu Trusty
  .travis.yml
Labels: category:unit-tests, type:bug 🐞

#1462 place execution of modify_current_screen() into the do_action() in `EE_Admin_Page_CPT`
  core/admin/EE_Admin_Page_CPT.core.php
Labels: status:merge, type:bug 🐞, type:theme/plugin-conflict 💥

#1464 Remove github config from add-on boilerplate's info.json
  tests/mocks/addons/eea-new-addon/info.json
Labels: type:build-process 🔨, type:task 🧹

#1450 Add filter hooks to allow for changing the way prices are displayed on the attendee information step
  core/libraries/line_item_display/EE_Default_Line_Item_Display_Strategy.strategy.php
Labels: category:spco-&-registration, status:needs-testing, type:enhancement 🎉

#1465 add filter hooks to allow filtering display of unit price and total
  core/libraries/line_item_display/EE_SPCO_Line_Item_Display_Strategy.strategy.php
Labels: category:spco-&-registration, status:merge, type:enhancement 🎉

#1466 Task/js build file docs update
  docs/AA--Javascript-in-EE/asset-caching-by-filename.md
Labels: status:review, type:documentation 📖

#1477 Use correct variable for Primary Reg Phone
  admin_pages/transactions/templates/txn_admin_details_side_meta_box_registrant.template.php
Labels: category:admin-pages, type:bug 🐞

#1501 Add $wpdb->prepare to junk delete query
  core/db_models/EEM_Transaction.model.php
Labels: category:models-and-data-infrastructure, type:enhancement 🎉

#1514 make sure validation defaults are initialized when loading billing forms
  modules/single_page_checkout/js/single_page_checkout.js
Labels: category:forms-systems, category:payment-methods, category:spco-&-registration, status:needs-testing, type:bug 🐞

#1531 FET/deprecate log functionality
  admin_pages/general_settings/help_tabs/general_settings_admin_options.help_tab.php
  admin_pages/general_settings/help_tours/Admin_Options_Help_Tour.class.php
  caffeinated/admin/extend/general_settings/Extend_General_Settings_Admin_Page.core.php
  caffeinated/admin/extend/general_settings/templates/debug_log_settings.template.php
  core/EE_Config.core.php
  core/EE_Log.core.php
  core/EE_System.core.php
  core/data_migration_scripts/4_1_0_stages/EE_DMS_4_1_0_org_options.dmsstage.php
Labels: category:admin-pages, category:core-plugin, status:merge, type:task 🧹

#1536 Change return from bool to always array
  modules/ticket_selector/ProcessTicketSelector.php
Labels: category:ticket-selector, status:merge
