Repository eventespresso/event-espresso-core, pull requests merged in 2019-01, with the labels that each got.

#870 update travis build to include php 7.3 (fixes #794)
  .travis.yml
  admin_pages/transactions/Transactions_Admin_Page.core.php
  tests/testcases/admin_pages/transactions/Transactions_Admin_Page_Test.php
Labels: category:unit-tests, type:build-process 🔨

#875 instead of only using FKs to identify a duplicate, use all the columns
  core/db_models/relations/EE_HABTM_Relation.php
  tests/testcases/core/db_classes/EE_Base_Class_Test.php
Labels: category:models-and-data-infrastructure, category:spco-&-registration, status:review, type:bug 🐞

#852 Bug/rest api taxonomy relationships regression, Fixes #845
  core/db_models/EEM_Base.model.php
  core/libraries/rest_api/controllers/model/Read.php
  tests/testcases/core/libraries/rest_api/controllers/Read_Test.php
Labels: category:models-and-data-infrastructure, status:merge, type:bug 🐞

#861 Bug/11315/fix long titles for events breaking registraiton due to wpdb insert error
  core/helpers/EEH_Line_Item.helper.php
Labels: category:models-and-data-infrastructure, type:bug 🐞, type:user-proofing 🛡

#828 Removed bot trap timestamp Fixes #670
  modules/bot_trap/EED_Bot_Trap.module.php
Labels: category:admin-page-ui-&-ux, category:frontend-ui-&-ux, category:spco-&-registration, status:merge, type:task ✅

#886 Fix npm version installed in travis environment and switch to wp-scripts check-engines
  .travis.yml
  package-lock.json
  package.json
Labels: category:assets, type:bug 🐞, type:build-process 🔨

#834 Fix block-level elements breaking the payment method description output
  modules/single_page_checkout/reg_steps/payment_options/EE_SPCO_Reg_Step_Payment_Options.class.php
Labels: category:spco-&-registration, status:needs-testing

#839 Remove navigation link that results in a Fatal Error on Registrations Check-ins
  caffeinated/admin/extend/registrations/Extend_Registrations_Admin_Page.core.php
Labels: status:needs-testing

#851 Override iOS default input styles
  modules/ticket_selector/assets/ticket_selector_embed.css
Labels: category:frontend-ui-&-ux, category:templates-shortcodes-and-widgets, status:merge, type:enhancement 🎉

#865 Remove monster sideload error
  core/helpers/EEH_Sideloader.helper.php
Labels: status:merge

#880 raise default limit, fixes #879
  core/domain/entities/shortcodes/EspressoEventAttendees.php
Labels: status:needs-testing

#820 improve paypal pro unauthenticatd message
  caffeinated/payment_methods/Paypal_Pro/EEG_Paypal_Pro.gateway.php
  caffeinated/payment_methods/Paypal_Pro/EE_PMT_Paypal_Pro.pm.php
  caffeinated/payment_methods/Paypal_Pro/forms/PayPalProSettingsForm.php
  core/services/payment_methods/forms/PayPalSettingsForm.php
  payment_methods/Paypal_Express/EE_PMT_Paypal_Express.pm.php
  payment_methods/Paypal_Express/forms/SettingsForm.php
Labels: category:payment-methods, status:merge, type:feature-request 🙏

#889 add attendee importer to label sync
  .github/label-sync.yml
Labels: status:review, type:build-process 🔨, type:task ✅

#884 tweaked batch job error message to mention they can refresh the page …
  modules/batch/EED_Batch.module.php
Labels: category:admin-page-ui-&-ux, status:review, type:enhancement 🎉

#896 Loosen up restrictions on error reporting when invisible reCAPTCHA fails
  caffeinated/modules/recaptcha_invisible/EED_Recaptcha_Invisible.module.php
  caffeinated/modules/recaptcha_invisible/InvisibleRecaptcha.php
Labels: category:security, category:spco-&-registration, status:merge, type:enhancement 🎉, type:impacts-eventsmart

#904 Bug/rest api innaccessible related model causes error response
  core/libraries/rest_api/controllers/model/Read.php
  tests/testcases/core/libraries/rest_api/controllers/ReadProtectedTest.php
  tests/testcases/core/libraries/rest_api/controllers/Read_Test.php
Labels: category:models-and-data-infrastructure, priority:high, status:merge, type:bug 🐞

#906 Use the correct path for PayPalSettingsForm namespace. Fixes #905
  caffeinated/payment_methods/Paypal_Pro/EE_PMT_Paypal_Pro.pm.php
Labels: status:triage

#914 Document default where conditions for REST API
  docs/C--REST-API/ee4-rest-api-GET-filtering-results.md
  docs/C--REST-API/ee4-rest-api-editing-relations.md
  docs/C--REST-API/ee4-rest-api-reading-data.md
  docs/C--REST-API/ee4-rest-api-writing-data.md
  docs/C--REST-API/rest-api-changelog.md
  docs/G--Model-System/model-query-params.md
Labels: category:models-and-data-infrastructure, status:review, type:documentation 📖

#921 export __DEV__ constant
  assets/src/eejs/index.js
Labels: category:assets, category:gutenberg, type:enhancement 🎉

#817 paypal pro can handle negative line items, so send them. (Just for pe…
  caffeinated/payment_methods/Paypal_Pro/EEG_Paypal_Pro.gateway.php
Labels: category:payment-methods, type:bug 🐞

#711 Fix Potential Recursion during Reg Status Updates
  core/db_classes/EE_Registration.class.php
  core/domain/services/event/EventSpacesCalculator.php
Labels: category:models-and-data-infrastructure, status:merge, type:bug 🐞
