Repository eventespresso/event-espresso-core, pull requests merged in 2020-08, with the labels that each got.

#3069 Don't Apply Default Taxes to Default Free Tickets
  core/db_classes/EE_Price.class.php
  core/domain/services/admin/entities/DefaultPrices.php
Labels: EDTR v2, category:models-and-data-infrastructure, type:enhancement 🎉

#3070 Toolbar icon fix.
  core/admin/assets/admin-menu-styles.css
Labels: category:admin-page-ui-&-ux

#3071 Prepare GQL for bulk edit
  core/domain/services/graphql/mutators/BulkEntityMutator.php
  core/domain/services/graphql/mutators/DatetimeBulkUpdate.php
  core/domain/services/graphql/mutators/TicketBulkUpdate.php
  core/domain/services/graphql/types/Datetime.php
  core/domain/services/graphql/types/Ticket.php
  docs/GraphQL-API/README.md
  docs/GraphQL-API/mutations/bulk-update.md
  package.json
  yarn.lock
Labels: EDTR v2, category:models-and-data-infrastructure, type:enhancement 🎉

#3074 Fix & Improve Legacy Admin Asset Loading
  admin_pages/registrations/EE_Registrations_List_Table.class.php
  admin_pages/registrations/Registrations_Admin_Page.core.php
  admin_pages/transactions/Transactions_Admin_Page.core.php
  caffeinated/admin/extend/registrations/EE_Event_Registrations_List_Table.class.php
  caffeinated/admin/extend/registrations/Extend_Registrations_Admin_Page.core.php
  core/admin/EE_Admin_Page.core.php
  core/admin/EE_Admin_Page_Init.core.php
  core/admin/assets/ee-admin-page.css
  core/domain/entities/routing/handlers/admin/AdminRoute.php
  core/domain/entities/routing/handlers/admin/EspressoEventEditor.php
  core/domain/entities/routing/handlers/admin/EspressoLegacyAdmin.php
  core/domain/services/assets/CoreAssetManager.php
  core/domain/services/assets/EspressoLegacyAdminAssetManager.php
  core/domain/services/assets/JqueryAssetManager.php
  core/domain/services/assets/LegacyAccountingAssetManager.php
  core/domain/values/assets/Asset.php
  core/domain/values/assets/JavascriptAsset.php
  core/helpers/EEH_Qtip_Loader.helper.php
  core/services/assets/AssetManager.php
  core/services/assets/Registry.php
Labels: category:admin-pages, category:assets, status:review, type:enhancement 🎉

#3076 EBulk delete GQL schema
  core/domain/services/graphql/mutators/BulkEntityDelete.php
  core/domain/services/graphql/mutators/EntityReorder.php
  core/domain/services/graphql/mutators/TicketDelete.php
  core/domain/services/graphql/types/Datetime.php
  docs/GraphQL-API/mutations/common.md
Labels: EDTR v2, category:models-and-data-infrastructure, status:review, type:enhancement 🎉

#3077 Deps array update.
  assets/src/application/ui/calendars/dateDisplay/EditDateRangeButton.tsx
  assets/src/application/ui/calendars/dateDisplay/types.ts
  assets/src/application/ui/display/Popover/index.tsx
  assets/src/application/ui/display/icons/HelpIcon/index.tsx
  assets/src/application/ui/input/Button/Button.tsx
  assets/src/application/ui/input/Button/IconButton/index.tsx
  assets/src/application/ui/input/Button/Link.tsx
  assets/src/application/ui/input/Button/types.ts
  assets/src/application/ui/input/CurrencyInput/index.tsx
  assets/src/application/ui/layout/Container/Sidebar.tsx
  assets/src/application/ui/layout/Container/Stack.tsx
  assets/src/application/ui/layout/EntityCard/index.tsx
  assets/src/application/ui/layout/dropdownMenu/DropdownToggle/style.scss
  assets/src/application/ui/layout/espressoTable/style/_data-cell.scss
  assets/src/application/ui/layout/espressoTable/style/_row.scss
  assets/src/application/ui/layout/espressoTable/style/index.scss
  assets/src/application/valueObjects/config/CurrentUser.ts
  assets/src/domain/eventEditor/services/apollo/initialization/useCacheRehydrationData.ts
  assets/src/domain/eventEditor/services/filterState/tickets/useTicketsListFilterStateManager.ts
  assets/src/domain/eventEditor/ui/datetimes/datesList/cardView/DateCapacity.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/cardView/DateCardSidebar.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/editable/EditableDesc.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/editable/EditableName.tsx
  assets/src/domain/eventEditor/ui/tickets/hooks/useRecalculateBasePrice.ts
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/components/DefaultPricesInfo.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/components/DefaultTaxesInfo.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/cardView/TicketCardSidebar.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/editable/EditableDesc.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/editable/EditableName.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/editable/EditablePrice.tsx
  assets/src/infrastructure/ui/inputs/dateTime/DatePicker/index.tsx
  assets/src/infrastructure/ui/inputs/dateTime/TimePicker/index.tsx
  assets/src/infrastructure/ui/inputs/inlineEdit/InlineEditInput.tsx
Labels: EDTR v2

#3084 Fix default tax removal bug
  assets/src/application/services/apollo/relations/reducer.ts
  assets/src/domain/eventEditor/services/apollo/mutations/datetimes/useMutationHandler.ts
  assets/src/domain/eventEditor/services/apollo/mutations/datetimes/useOnCreateDatetime.ts
  assets/src/domain/eventEditor/services/apollo/mutations/datetimes/useOnUpdateDatetime.ts
  assets/src/domain/eventEditor/services/apollo/mutations/tickets/useMutationHandler.ts
  assets/src/domain/eventEditor/services/apollo/mutations/tickets/useOnCreateTicket.ts
  assets/src/domain/eventEditor/services/apollo/mutations/tickets/useOnUpdateTicket.ts
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/buttons/DeleteAllPricesButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/buttons/DeletePriceModifierButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/hooks/index.ts
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/hooks/useRemoveAllTaxes.ts
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/hooks/useRemoveDefaultTax.ts
Labels: EDTR v2, category:models-and-data-infrastructure, status:review, type:bug 🐞

#3090 Date/Time picker API improvements
  assets/src/application/ui/calendars/dateDisplay/EditDateRangeButton.tsx
  assets/src/application/ui/calendars/dateDisplay/types.ts
  assets/src/application/ui/input/DateTimeRangePicker/index.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/cardView/DateCardSidebar.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/cardView/TicketCardSidebar.tsx
  assets/src/infrastructure/ui/inputs/dateTime/DatePicker/index.tsx
  assets/src/infrastructure/ui/inputs/dateTime/DateTimeRangePicker/index.tsx
  assets/src/infrastructure/ui/inputs/dateTime/TimePicker/index.tsx
  assets/src/infrastructure/ui/inputs/dateTime/index.tsx
  assets/src/infrastructure/ui/inputs/dateTime/types.ts
Labels: EDTR v2, status:review, type:enhancement 🎉

#3091 Change Default Values for Start and End Dates
  assets/src/application/services/utilities/date/misc.ts
  assets/src/application/ui/calendars/dateDisplay/CalendarDateSwitcher/index.tsx
  assets/src/domain/eventEditor/ui/datetimes/dateForm/useDateFormConfig.ts
  assets/src/domain/eventEditor/ui/tickets/ticketForm/useTicketFormConfig.tsx
Labels: EDTR v2, category:admin-page-ui-&-ux, status:review

#2916 Add Foreign Key Alias
  core/db_models/EEM_Base.model.php
  core/db_models/EEM_Event_Message_Template.model.php
  core/db_models/EEM_Payment_Method.model.php
  core/db_models/EEM_WP_User.model.php
  core/db_models/fields/EE_Email_Field.php
Labels: category:models-and-data-infrastructure, status:feedback-needed, type:bug 🐞

#3081 GQL: Add bulk delete support for prices
  .travis.yml
  core/domain/services/graphql/enums/ModelNameEnum.php
  core/domain/services/graphql/mutators/BulkEntityDelete.php
  tests/includes/CoreLoader.php
Labels: EDTR v2, category:models-and-data-infrastructure, status:review, type:enhancement 🎉

#3085 Don't Double Tax
  core/db_classes/EE_Line_Item.class.php
  core/db_classes/EE_Ticket.class.php
  core/helpers/EEH_Line_Item.helper.php
Labels: EDTR v2, category:models-and-data-infrastructure, status:review, type:enhancement 🎉

#3104 Add session_write_close() directly after any time we call start_session()
  core/services/session/SessionStartHandler.php
Labels: status:needs-testing
