Repository eventespresso/event-espresso-core, pull requests merged in 2020-07, with the labels that each got.

#3020 Fix Assets Not Loading for EDTR
  config/webpack.config.js
  core/domain/services/assets/EspressoEditorAssetManager.php
Labels: EDTR v2, category:assets, type:bug 🐞

#3021 Add filters to GQL shema for addons
  core/domain/services/graphql/connection_resolvers/AttendeeConnectionResolver.php
  core/domain/services/graphql/connection_resolvers/DatetimeConnectionResolver.php
  core/domain/services/graphql/connection_resolvers/PriceConnectionResolver.php
  core/domain/services/graphql/connection_resolvers/PriceTypeConnectionResolver.php
  core/domain/services/graphql/connection_resolvers/TicketConnectionResolver.php
  core/domain/services/graphql/connection_resolvers/VenueConnectionResolver.php
  core/domain/services/graphql/connections/DatetimeTicketsConnection.php
  core/domain/services/graphql/connections/EventDatetimesConnection.php
  core/domain/services/graphql/connections/RootQueryAttendeesConnection.php
  core/domain/services/graphql/connections/TicketPricesConnection.php
  core/domain/services/graphql/data/mutations/DatetimeMutation.php
  core/domain/services/graphql/data/mutations/EventMutation.php
  core/domain/services/graphql/data/mutations/PriceMutation.php
  core/domain/services/graphql/data/mutations/TicketMutation.php
  core/domain/services/graphql/data/mutations/VenueMutation.php
  core/domain/services/graphql/types/Attendee.php
  core/domain/services/graphql/types/Country.php
  core/domain/services/graphql/types/Datetime.php
  core/domain/services/graphql/types/Event.php
  core/domain/services/graphql/types/Price.php
  core/domain/services/graphql/types/PriceType.php
  core/domain/services/graphql/types/State.php
  core/domain/services/graphql/types/Ticket.php
  core/domain/services/graphql/types/Venue.php
Labels: EDTR v2, category:models-and-data-infrastructure, type:enhancement 🎉

#3026 i18n for blocks and plugins page
  assets/src/domain/blocks/i18nInit.ts
  assets/src/domain/blocks/index.ts
  assets/src/domain/wpPluginsPage/exitSurvey/ExitSurvey.tsx
  assets/src/domain/wpPluginsPage/exitSurvey/hooks/index.ts
  assets/src/domain/wpPluginsPage/exitSurvey/hooks/useI18nData.ts
  assets/src/domain/wpPluginsPage/exitSurvey/hooks/useInitialization.ts
Labels: EDTR v2, category:admin-page-ui-&-ux, type:bug 🐞

#3023 Normie Headings closes #3000
  assets/src/application/ui/input/Button/ButtonRow/style.scss
  assets/src/application/ui/layout/entityList/style.scss
  assets/src/application/ui/styles/mixins/breakpoints.scss
Labels: EDTR v2, category:admin-page-ui-&-ux, type:enhancement 🎉

#3022 UI tweaks.
  assets/src/application/ui/display/EntityIDs/index.tsx
  assets/src/application/ui/display/EntityIDs/style.css
  assets/src/application/ui/display/EntityIDs/style.scss
  assets/src/application/ui/display/entityDetailsPanel/DetailsSeparator.tsx
  assets/src/application/ui/display/entityDetailsPanel/EntityDetail.tsx
  assets/src/application/ui/display/entityDetailsPanel/EntityDetailsPanel.tsx
  assets/src/application/ui/display/entityDetailsPanel/Sold.tsx
  assets/src/application/ui/display/entityDetailsPanel/index.ts
  assets/src/application/ui/display/entityDetailsPanel/style.scss
  assets/src/application/ui/input/Button/Link.tsx
  assets/src/application/ui/input/Button/types.ts
  assets/src/application/ui/input/InlineEditInput/style.scss
  assets/src/application/ui/layout/entityList/RegistrationsLink/index.tsx
  assets/src/application/ui/layout/entityList/RegistrationsLink/style.scss
  assets/src/domain/eventEditor/ui/datetimes/datesList/cardView/DateDetailsPanel.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/cardView/TicketDetailsPanel.tsx
Labels: EDTR v2, category:admin-page-ui-&-ux

#3028 Changed default entity list sort order.
  assets/src/domain/eventEditor/services/filterState/datetimes/useDatesListFilterStateManager.ts
  assets/src/domain/eventEditor/services/filterState/tickets/useTicketsListFilterStateManager.ts
Labels: EDTR v2, category:admin-page-ui-&-ux

#3030 Ensure WPGraphQL is Loaded Fixes #3024
  core/domain/entities/routing/data_nodes/core/CurrentUser.php
Labels: EDTR v2, category:admin-pages, type:bug 🐞

#3031 Add DOM Data for Gutenberg Blocks closes #3027
  assets/src/domain/index.ts
  core/EE_System.core.php
  core/domain/entities/editor/CoreBlocksAssetManager.php
  core/domain/entities/routing/data_nodes/EventEspressoData.php
  core/domain/entities/routing/data_nodes/domains/GutenbergEditorData.php
  core/domain/entities/routing/handlers/admin/EspressoEventEditor.php
  core/domain/entities/routing/handlers/admin/GutenbergEditor.php
  core/domain/entities/routing/handlers/admin/WordPressPluginsPage.php
  core/domain/entities/routing/handlers/shared/GQLRequests.php
  core/domain/entities/routing/handlers/shared/RoutingRequests.php
  core/services/assets/BlockAssetManager.php
  core/services/json/PrimaryJsonDataNode.php
  tsconfig.json
Labels: EDTR v2, category:models-and-data-infrastructure, type:bug 🐞

#3032 Fix base price when ticket price is changed inline
  assets/src/domain/eventEditor/ui/tickets/hooks/useRecalculateBasePrice.ts
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/hooks/index.ts
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/hooks/useAddDefaultPrices.ts
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/hooks/useDefaultBasePrice.ts
  assets/src/domain/eventEditor/ui/tickets/ticketsList/editable/EditablePrice.tsx
Labels: EDTR v2, category:models-and-data-infrastructure, status:review, type:bug 🐞

#3035 Fix missing prices after creating a ticket
  assets/src/domain/eventEditor/services/apollo/mutations/tickets/updatePriceCache.ts
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/components/DefaultTaxesInfo.tsx
Labels: EDTR v2, category:models-and-data-infrastructure, status:review, type:bug 🐞

#3036 Fix price update when ticket is made free
  assets/src/domain/eventEditor/ui/tickets/hooks/useRecalculateBasePrice.ts
  assets/src/domain/eventEditor/ui/tickets/ticketsList/editable/EditablePrice.tsx
  core/domain/services/graphql/data/mutations/PriceMutation.php
Labels: EDTR v2, category:models-and-data-infrastructure, status:review, type:bug 🐞

#3037 New Date Picker
  assets/src/application/ui/calendars/dateDisplay/BiggieCalendarDate/index.tsx
  assets/src/application/ui/display/TimezoneTimeInfo/Trigger.tsx
  assets/src/application/ui/display/TimezoneTimeInfo/index.tsx
  assets/src/application/ui/display/icons/svgs/clockOutlined.svg
  assets/src/application/ui/display/icons/svgs/index.ts
  assets/src/application/ui/forms/espressoForm/adapters/DatePicker.tsx
  assets/src/application/ui/forms/espressoForm/adapters/TimePicker.tsx
  assets/src/application/ui/layout/espressoTable/TableBody.tsx
  assets/src/application/ui/layout/espressoTable/TableFooter.tsx
  assets/src/application/ui/layout/espressoTable/TableHeader.tsx
  assets/src/infrastructure/ui/inputs/dateTime/BaseUIProvider.tsx
  assets/src/infrastructure/ui/inputs/dateTime/Datepicker/index.tsx
  assets/src/infrastructure/ui/inputs/dateTime/Datepicker/style.scss
  assets/src/infrastructure/ui/inputs/dateTime/Timepicker/index.tsx
  assets/src/infrastructure/ui/inputs/dateTime/Timepicker/style.scss
  assets/src/infrastructure/ui/inputs/dateTime/types.ts
  assets/src/infrastructure/ui/inputs/dateTime/utilities.ts
  assets/src/infrastructure/ui/inputs/dateTime/withBaseProvider.tsx
  assets/src/infrastructure/ui/inputs/style.scss
  package.json
  yarn.lock
Labels: EDTR v2, category:admin-page-ui-&-ux, status:review, type:enhancement 🎉

#3038 Fixed pagination missing arrows and TAM close button.
  assets/src/infrastructure/ui/display/pagination/Pagination.tsx
  assets/src/infrastructure/ui/display/pagination/style.scss
  assets/src/infrastructure/ui/layout/modal/modalCloseButtonProps.tsx
  assets/src/infrastructure/ui/layout/modal/modalCloseButtonProps/styles.scss
  assets/src/infrastructure/ui/layout/modal/styles.scss
Labels: EDTR v2, category:admin-page-ui-&-ux

#3039 Add Datetime Range Picker
  assets/src/application/ui/calendars/dateDisplay/BiggieCalendarDate/index.tsx
  assets/src/application/ui/calendars/dateDisplay/BiggieCalendarDate/style.scss
  assets/src/application/ui/calendars/dateDisplay/CalendarDateSwitcher/index.tsx
  assets/src/application/ui/calendars/dateDisplay/EditDateRangeButton.tsx
  assets/src/application/ui/calendars/dateDisplay/MediumCalendarDate/index.tsx
  assets/src/application/ui/calendars/dateDisplay/MediumCalendarDate/style.scss
  assets/src/application/ui/calendars/dateDisplay/index.ts
  assets/src/application/ui/calendars/dateDisplay/types.ts
  assets/src/application/ui/display/Popover/index.tsx
  assets/src/application/ui/display/Popover/style.scss
  assets/src/application/ui/display/TimezoneTimeInfo/index.tsx
  assets/src/application/ui/display/TimezoneTimeInfo/style.scss
  assets/src/application/ui/display/icons/index.ts
  assets/src/application/ui/display/index.ts
  assets/src/application/ui/forms/espressoForm/adapters/DatePicker.tsx
  assets/src/application/ui/forms/espressoForm/adapters/TimePicker.tsx
  assets/src/application/ui/input/Button/Button.tsx
  assets/src/application/ui/input/Button/IconButton/index.tsx
  assets/src/application/ui/input/Button/IconButton/types.ts
  assets/src/application/ui/input/Button/types.ts
  assets/src/application/ui/input/DatePicker/index.tsx
  assets/src/application/ui/input/DateTimeRangePicker/index.tsx
  assets/src/application/ui/input/TimePicker/index.tsx
  assets/src/application/ui/input/TimePicker/style.scss
  assets/src/application/ui/input/index.ts
  assets/src/application/ui/layout/Container/ConditionalElement.tsx
  assets/src/application/ui/layout/Container/Container.tsx
  assets/src/application/ui/layout/Container/Content.tsx
  assets/src/application/ui/layout/Container/Footer.tsx
  assets/src/application/ui/layout/Container/Header.tsx
  assets/src/application/ui/layout/Container/Row.tsx
  assets/src/application/ui/layout/Container/Sidebar.tsx
  assets/src/application/ui/layout/Container/Stack.tsx
  assets/src/application/ui/layout/Container/index.tsx
  assets/src/application/ui/layout/Container/styles.scss
  assets/src/application/ui/layout/Container/types.ts
  assets/src/application/ui/layout/EntityCard/index.tsx
  assets/src/application/ui/layout/EntityCard/styles.scss
  assets/src/application/ui/layout/EntityCard/types.ts
  assets/src/application/ui/layout/entityList/style.scss
  assets/src/application/ui/styles/root/containers.css
  assets/src/application/ui/styles/themes/default/index.scss
  assets/src/domain/eventEditor/ui/datetimes/datesList/cardView/DateCard.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/cardView/TicketCard.tsx
  assets/src/infrastructure/ui/display/Popover.tsx
  assets/src/infrastructure/ui/inputs/dateTime/DatePicker/index.tsx
  assets/src/infrastructure/ui/inputs/dateTime/DateTimeRangePicker/index.tsx
  assets/src/infrastructure/ui/inputs/dateTime/Datepicker/style.scss
  assets/src/infrastructure/ui/inputs/dateTime/TimePicker/index.tsx
  assets/src/infrastructure/ui/inputs/dateTime/Timepicker/style.scss
  assets/src/infrastructure/ui/inputs/dateTime/index.tsx
  assets/src/infrastructure/ui/inputs/dateTime/style.scss
  assets/src/infrastructure/ui/inputs/dateTime/types.ts
  assets/src/infrastructure/ui/inputs/dateTime/utilities.ts
  assets/src/infrastructure/ui/inputs/index.ts
  package.json
  scripts/watch.js
  yarn.lock
Labels: EDTR v2, category:admin-page-ui-&-ux, status:review, type:enhancement 🎉

#3049 InlineEditText: titles length fixes.
  assets/src/application/ui/input/InlineEditInput/InlineEditText.tsx
  package.json
  yarn.lock
Labels: EDTR v2

#3050 Popover alignment and datepicker range improvements.
  assets/src/application/ui/display/Popover/style.scss
  assets/src/infrastructure/ui/display/Popover.tsx
  assets/src/infrastructure/ui/inputs/dateTime/DateTimeRangePicker/index.tsx
  assets/src/infrastructure/ui/inputs/dateTime/style.scss
  assets/src/infrastructure/ui/inputs/dateTime/types.ts
Labels: EDTR v2

#3052 Table view: fixed name field overflow issue.
  assets/src/application/ui/input/InlineEditInput/InlineEditInfinity.tsx
  assets/src/application/ui/input/InlineEditInput/InlineEditText.tsx
  assets/src/application/ui/input/InlineEditInput/InlineEditTextArea.tsx
  assets/src/application/ui/input/InlineEditInput/Preview.tsx
  assets/src/application/ui/input/InlineEditInput/index.tsx
  assets/src/application/ui/input/InlineEditInput/types.ts
  assets/src/domain/eventEditor/ui/datetimes/datesList/editable/EditableName.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/tableView/useBodyRowGenerator.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/editable/EditableName.tsx
  assets/src/infrastructure/ui/inputs/inlineEdit/InlineEditPreview.tsx
  assets/src/infrastructure/ui/inputs/inlineEdit/types.ts
Labels: EDTR v2, category:admin-page-ui-&-ux, type:bug 🐞

#3053 DateTimeRangePicker improvements.
  assets/src/application/ui/styles/mixins/screen-reader.scss
  assets/src/domain/index.ts
  assets/src/infrastructure/ui/inputs/dateTime/DateTimeRangePicker/index.tsx
  assets/src/infrastructure/ui/inputs/dateTime/DateTimeRangePicker/style.scss
  assets/src/infrastructure/ui/inputs/dateTime/types.ts
Labels: EDTR v2

#3048 Fix Activation Issues
  core/EE_Config.core.php
  core/EE_Dependency_Map.core.php
  core/EE_Registry.core.php
  core/EE_System.core.php
  core/admin/EE_Admin.core.php
  core/domain/entities/contexts/RequestTypeContext.php
  core/domain/entities/routing/handlers/admin/ActivationRequests.php
  core/domain/entities/routing/handlers/admin/AdminRoute.php
  core/domain/entities/routing/handlers/shared/RegularRequests.php
  core/domain/services/contexts/RequestTypeContextChecker.php
  core/domain/services/contexts/RequestTypeContextDetector.php
  core/helpers/EEH_Debug_Tools.helper.php
  core/helpers/EEH_File.helper.php
  core/helpers/EEH_Sideloader.helper.php
  core/services/container/Mirror.php
  core/services/routing/PrimaryRoute.php
  core/services/routing/Route.php
  core/services/routing/RouteHandler.php
  core/services/routing/Router.php
  tests/includes/EE_UnitTestCase.class.php
  tests/mocks/core/domain/entities/routing/handlers/shared/RegularRequestsMock.php
  tests/mocks/core/services/routing/RouterMock.php
  tests/testcases/admin_pages/events_decaf/Events_Admin_Page_Decaf_Test.php
  tests/testcases/core/db_classes/EE_CPT_Base_Test.php
  tests/testcases/core/helpers/EEH_File_Test.php
Labels: EDTR v2, category:activation-installation-and-migration, status:review, type:bug 🐞, type:enhancement 🎉

#3054 Add Status Color Code Change Notice
  admin_pages/events/assets/events-admin-page.css
  admin_pages/messages/Messages_Admin_Page.core.php
  admin_pages/messages/assets/ee_message_admin.css
  admin_pages/registrations/assets/espresso_registrations_admin.css
  admin_pages/transactions/assets/espresso_transactions_admin.css
  caffeinated/admin/new/pricing/assets/event-tickets-datetimes.css
  caffeinated/admin/new/pricing/espresso_events_Pricing_Hooks.class.php
  caffeinated/admin/new/pricing/templates/event_tickets_metabox_main.template.php
  core/admin/EE_Admin_Page.core.php
  core/admin/assets/admin-menu-styles.css
  core/admin/assets/ee-admin-page.css
  core/admin/templates/admin_details_legend.template.php
  core/admin/templates/status_change_notice.template.php
  core/domain/services/assets/CoreAssetManager.php
  core/domain/services/assets/EspressoLegacyAdminAssetManager.php
  core/helpers/EEH_Template.helper.php
  core/templates/global_assets/css/espresso-admin-toolbar.css
  core/templates/global_assets/css/espresso_default.css
Labels: category:admin-page-ui-&-ux, status:review, type:enhancement 🎉

#3056 Improve Icon Button Visibility closes #3042
  assets/src/application/ui/calendars/dateDisplay/BiggieCalendarDate/style.scss
  assets/src/application/ui/calendars/dateDisplay/CalendarDateSwitcher/index.tsx
  assets/src/application/ui/calendars/dateDisplay/CalendarDateSwitcher/types.ts
  assets/src/application/ui/display/entityDetailsPanel/style.scss
  assets/src/application/ui/input/Button/IconButton/style.scss
  assets/src/application/ui/input/Button/Link.tsx
  assets/src/application/ui/input/Button/style.scss
  assets/src/application/ui/input/InlineEditInput/InlineEditInfinity.tsx
  assets/src/application/ui/input/InlineEditInput/TabbableText/index.tsx
  assets/src/application/ui/input/InlineEditInput/style.scss
  assets/src/application/ui/input/InlineEditInput/types.ts
  assets/src/application/ui/layout/EntityCard/styles.scss
  assets/src/application/ui/layout/descriptionList/styles.scss
  assets/src/application/ui/layout/dropdownMenu/DropdownToggle/style.scss
  assets/src/application/ui/layout/entityActionsMenu/style.scss
  assets/src/application/ui/styles/mixins/breakpoints.scss
  assets/src/domain/eventEditor/ui/datetimes/datesList/cardView/DateCapacity.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/cardView/DateCard.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/cardView/DateCardSidebar.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/editable/EditableDesc.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/editable/EditableName.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/cardView/TicketCard.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/cardView/TicketCardSidebar.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/cardView/TicketQuantity.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/editable/EditableDesc.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/editable/EditableName.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/editable/EditablePrice.tsx
  assets/src/infrastructure/ui/inputs/style.scss
Labels: EDTR v2, category:admin-page-ui-&-ux, status:review, type:enhancement 🎉

#3059 Fix date validation bug
  assets/src/domain/shared/services/utils/dateAndTime.ts
Labels: EDTR v2, category:admin-page-ui-&-ux, type:bug 🐞
