Repository eventespresso/event-espresso-core, pull requests merged in 2020-03, with the labels that each got.

#2469 Move Filtering and Pagination Logic into EntityList Component: closes#2424
  assets/src/application/ui/calendars/dateDisplay/BiggieCalendarDate/index.tsx
  assets/src/application/ui/display/EmptyState.tsx
  assets/src/application/ui/forms/espressoForm/renderers/RepeatableRenderer.tsx
  assets/src/application/ui/input/EspressoButton/EspressoButton.tsx
  assets/src/application/ui/input/EspressoButton/index.ts
  assets/src/application/ui/input/EspressoButton/types.ts
  assets/src/application/ui/input/index.ts
  assets/src/application/ui/layout/EntityCard/styles.scss
  assets/src/application/ui/layout/entityList/CardList.tsx
  assets/src/application/ui/layout/entityList/EntityList.tsx
  assets/src/application/ui/layout/entityList/EntityList/index.tsx
  assets/src/application/ui/layout/entityList/EntityList/style.scss
  assets/src/application/ui/layout/entityList/EntityList/types.ts
  assets/src/application/ui/layout/entityList/filterBar/EntityListFilterBar.tsx
  assets/src/application/ui/layout/entityList/filterBar/style.css
  assets/src/application/ui/layout/entityList/index.ts
  assets/src/application/ui/layout/entityList/pagination/style.scss
  assets/src/application/ui/layout/entityList/pagination/useEntityPagination.ts
  assets/src/application/ui/layout/entityList/style.scss
  assets/src/application/ui/layout/entityList/types.ts
  assets/src/application/ui/styles/root/buttons.css
  assets/src/domain/eventEditor/ui/datetimes/datesList/AddNewDateButton.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/List.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/cardView/CardView.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/cardView/index.ts
  assets/src/domain/eventEditor/ui/datetimes/datesList/cardView/styles.scss
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/DatesListEntityFilters.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/controls/DatesSortedControl.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/controls/DisplayDatesControl.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/controls/ShowDatesControl.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/useDatesListFilterState/index.test.ts
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/useDatesListFilterState/index.ts
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/useDatesListFilterState/reducer.ts
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/useDatesListFilterState/types.ts
  assets/src/domain/eventEditor/ui/datetimes/datesList/index.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/styles.scss
  assets/src/domain/eventEditor/ui/datetimes/datesList/tableView/TableView.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/List.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/cardView/index.ts
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/TicketListFilterBar.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/TicketsListEntityFilters.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/controls/TicketsChainedButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/index.ts
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/style.css
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/style.scss
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/useTicketListFilterState/index.ts
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/useTicketsListFilterState/index.test.ts
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/useTicketsListFilterState/index.ts
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/useTicketsListFilterState/reducer.ts
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/useTicketsListFilterState/types.ts
  assets/src/domain/eventEditor/ui/tickets/ticketsList/index.tsx
  assets/src/domain/shared/entities/datetimes/predicates/filters/index.ts
Labels: EDTR v2, category:assets, status:review, type:enhancement 🎉

#2472 Ticket Assignments Manager | Closes #2455
  assets/src/application/services/apollo/relations/index.ts
  assets/src/application/services/apollo/relations/types.ts
  assets/src/application/services/context/ModalProvider.tsx
  assets/src/application/services/utilities/types.ts
  assets/src/application/ui/layout/editorModal/types.ts
  assets/src/application/ui/layout/entityList/pagination/types.ts
  assets/src/application/ui/layout/entityList/pagination/useEntityPagination.ts
  assets/src/application/ui/layout/modal/useModal.ts
  assets/src/domain/eventEditor/services/apollo/queries/datetimes/index.ts
  assets/src/domain/eventEditor/services/apollo/queries/datetimes/queries.ts
  assets/src/domain/eventEditor/services/apollo/queries/index.ts
  assets/src/domain/eventEditor/services/apollo/queries/priceTypes/index.ts
  assets/src/domain/eventEditor/services/apollo/queries/priceTypes/queries.ts
  assets/src/domain/eventEditor/services/apollo/queries/prices/index.ts
  assets/src/domain/eventEditor/services/apollo/queries/prices/queries.ts
  assets/src/domain/eventEditor/services/apollo/queries/tickets/index.ts
  assets/src/domain/eventEditor/services/apollo/queries/tickets/queries.ts
  assets/src/domain/eventEditor/services/context/EventEditorContext/ContextProviders.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/AddNewDateButton.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/actionsMenu/AssignTicketsButton.tsx
  assets/src/domain/eventEditor/ui/datetimes/hooks/useDatesActionMenuHandler.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/ErrorMessage.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/RenderCell.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/RenderTable.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/TAMProvider.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/TicketAssignmentsManager.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/TicketHeader.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/styles.scss
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/types.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/useAssignmentManager.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/useCellIcon.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/useCellProps.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/useColClassName.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/useOnSubmitAssignments.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/useRowClassName.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/useTAMDatesAndTickets.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/useTAMState.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/useTAMStateManager.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/useTicketAssignmentsManager.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/useValidateTAMData.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/utils.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/withTAMProvider.tsx
  assets/src/domain/eventEditor/ui/tickets/hooks/useTicketsActionMenuHandler.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/actionsMenu/AssignDatesButton.tsx
  assets/src/domain/shared/entities/datetimes/predicates/isRecentlyExpired/index.test.ts
  package.json
  yarn.lock
Labels: EDTR v2, type:enhancement 🎉

#2482 Modal changes | Closes #2480, #2451
  assets/src/application/services/context/EditorModalProvider.tsx
  assets/src/application/services/context/FormModalProvider.tsx
  assets/src/application/ui/display/DebugInfo.tsx
  assets/src/application/ui/display/index.ts
  assets/src/application/ui/forms/espressoForm/renderers/FormRenderer.tsx
  assets/src/application/ui/forms/formModal/styles.css
  assets/src/application/ui/forms/modalForm/FormRenderer.tsx
  assets/src/application/ui/forms/modalForm/ModalForm.tsx
  assets/src/application/ui/forms/modalForm/RenderModalForm.tsx
  assets/src/application/ui/forms/modalForm/index.ts
  assets/src/application/ui/forms/modalForm/styles.scss
  assets/src/application/ui/forms/modalForm/types.ts
  assets/src/application/ui/layout/editorModal/index.ts
  assets/src/application/ui/layout/editorModal/useEditorModal.ts
  assets/src/application/ui/layout/formModal/index.ts
  assets/src/application/ui/layout/formModal/test/useFormModalManager.test.ts
  assets/src/application/ui/layout/formModal/types.ts
  assets/src/application/ui/layout/formModal/useFormModal.ts
  assets/src/application/ui/layout/formModal/useFormModalManager.ts
  assets/src/application/ui/layout/index.ts
  assets/src/domain/eventEditor/services/context/EventEditorContext/ContextProviders.tsx
  assets/src/domain/eventEditor/ui/EventEditor.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/AddNewDateButton.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/actionsMenu/EditDateButton.tsx
  assets/src/domain/eventEditor/ui/datetimes/hooks/useAddDatetimeModal.ts
  assets/src/domain/eventEditor/ui/datetimes/hooks/useDatesActionMenuHandler.tsx
  assets/src/domain/eventEditor/ui/datetimes/hooks/useEditDatetimeModal.ts
  assets/src/domain/eventEditor/ui/tickets/hooks/useAddTicketModal.ts
  assets/src/domain/eventEditor/ui/tickets/hooks/useEditTicketModal.ts
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/TicketPriceCalculatorForm.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/buttons/TicketPriceCalculatorButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/hooks/useOnSubmitPrices.ts
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/hooks/useTicketPriceCalculatorModal.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/AddNewTicketButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/actionsMenu/EditTicketButton.tsx
  assets/src/domain/shared/ui/editorModal/index.ts
  assets/src/domain/shared/ui/editorModal/types.ts
  assets/src/domain/shared/ui/editorModal/useEditors.ts
  assets/src/domain/shared/ui/formModal/FormModal.tsx
  assets/src/domain/shared/ui/formModal/index.ts
  assets/src/domain/shared/ui/formModal/types.ts
  assets/src/domain/shared/ui/formModal/useEditors.ts
Labels: EDTR v2, category:assets, type:enhancement 🎉

#2484 Fix guid length in shortenGuid | Closes #2474
  assets/src/application/services/utilities/text/shortenGuid/index.test.ts
  assets/src/application/services/utilities/text/shortenGuid/index.ts
Labels: EDTR v2, category:unit-tests, type:task 🧹

#2486 Improve EspressoIcon/EspressoButton and use Dashicons | Closes #2477
  assets/src/application/ui/display/espressoIcon/EspressoIcon.tsx
  assets/src/application/ui/display/espressoIcon/isEspressoIcon.ts
  assets/src/application/ui/display/espressoIcon/svgPaths.ts
  assets/src/application/ui/display/espressoIcon/types.ts
  assets/src/application/ui/input/EspressoButton/EspressoButton.tsx
  assets/src/application/ui/input/EspressoButton/types.ts
  assets/src/domain/eventEditor/ui/datetimes/datesList/AddNewDateButton.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/actionsMenu/AssignTicketsButton.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/actionsMenu/DeleteDateButton.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/actionsMenu/EditDateButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/AddNewTicketButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/actionsMenu/AssignDatesButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/actionsMenu/DeleteTicketButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/actionsMenu/EditTicketButton.tsx
Labels: EDTR v2, category:assets, type:enhancement 🎉

#2495 Fix TPC ticket update | Closes #2493
  assets/src/domain/shared/entities/prices/predicates/priceFields.ts
  assets/src/domain/shared/entities/tickets/predicates/ticketFields.ts
Labels: EDTR v2, status:review, type:bug 🐞

#2497 Fix console warnings | Closes #2496, #2498, #2483
  assets/src/application/services/apollo/relations/test/useRelationsManager/getData.test.ts
  assets/src/application/services/apollo/relations/test/useRelationsManager/getRelations.test.ts
  assets/src/application/services/apollo/relations/test/useRelationsManager/initialize.test.ts
  assets/src/application/services/apollo/relations/types.ts
  assets/src/application/services/apollo/relations/useRelationsManager.ts
  assets/src/application/services/config/types.ts
  assets/src/application/services/config/useConfig.ts
  assets/src/application/services/context/ConfigProvider.tsx
  assets/src/application/services/context/test/ConfigProvider.test.tsx
  assets/src/application/services/context/test/RelationsProvider.test.tsx
  assets/src/application/services/hooks/useTimeZoneTime.ts
  assets/src/application/services/toaster/useToastManager.tsx
  assets/src/application/services/utilities/money/useMoneyDisplay.ts
  assets/src/application/ui/display/EmptyState.tsx
  assets/src/application/ui/display/ErrorIndicator.tsx
  assets/src/application/ui/display/LoadingIndicator.js
  assets/src/application/ui/input/CurrencyInput/index.tsx
  assets/src/application/ui/input/DateTimePicker/DatePickerBase.tsx
  assets/src/application/ui/layout/entityActionsMenu/useEntityActions.ts
  assets/src/application/ui/layout/entityActionsMenu/useEntityActionsMenuItems.tsx
  assets/src/application/ui/layout/entityActionsMenu/useEntityActionsMenuSubscription.ts
  assets/src/application/ui/layout/entityList/filterBar/EntityListFilterBar.tsx
  assets/src/application/ui/layout/espressoTable/ResponsiveTable.tsx
  assets/src/domain/eventEditor/hooks/index.ts
  assets/src/domain/eventEditor/hooks/useEditorInitialization.ts
  assets/src/domain/eventEditor/index.tsx
  assets/src/domain/eventEditor/services/apollo/index.ts
  assets/src/domain/eventEditor/services/apollo/initialization/index.ts
  assets/src/domain/eventEditor/services/apollo/initialization/useCacheRehydration.ts
  assets/src/domain/eventEditor/services/apollo/queries/index.ts
  assets/src/domain/eventEditor/services/context/TestContext/useSetRelationalData.ts
  assets/src/domain/eventEditor/ui/EventEditor.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/actionsMenu/DeleteDateButton.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/types.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/useAssignmentManager.ts
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/controls/DisplayTicketsControl.tsx
  assets/src/domain/shared/services/apollo/queries/currentUser/index.ts
  assets/src/domain/shared/services/apollo/queries/currentUser/queries.ts
  assets/src/domain/shared/services/apollo/queries/currentUser/useCurrentUser.ts
  assets/src/domain/shared/services/apollo/queries/currentUser/useCurrentUserQueryOptions.ts
  assets/src/domain/shared/services/apollo/queries/currentUser/useFetchCurrentUser.ts
  assets/src/domain/shared/services/apollo/queries/generalSettings/index.ts
  assets/src/domain/shared/services/apollo/queries/generalSettings/queries.ts
  assets/src/domain/shared/services/apollo/queries/generalSettings/useFetchGeneralSettings.ts
  assets/src/domain/shared/services/apollo/queries/generalSettings/useGeneralSettings.ts
  assets/src/domain/shared/services/apollo/queries/generalSettings/useGeneralSettingsQueryOptions.ts
  jest.config.js
  package.json
  yarn.lock
Labels: EDTR v2, status:review, type:bug 🐞

#2501 Random Bunch O Fixes
  assets/src/application/ui/display/espressoIcon/svgPaths.ts
  assets/src/application/ui/display/espressoIcon/types.ts
  assets/src/application/ui/forms/espressoForm/renderers/FieldRenderer.tsx
  assets/src/application/ui/forms/modalForm/styles.scss
  assets/src/application/ui/input/CurrencyInput/index.tsx
  assets/src/application/ui/input/EspressoButton/EspressoButton.tsx
  assets/src/application/ui/input/InlineEditInput/Editable.tsx
  assets/src/application/ui/input/InlineEditInput/InlineEditHeading.tsx
  assets/src/application/ui/input/InlineEditInput/InlineEditText.tsx
  assets/src/application/ui/input/InlineEditInput/InlineEditTextArea.tsx
  assets/src/application/ui/input/InlineEditInput/style.css
  assets/src/application/ui/input/InlineEditInput/types.ts
  assets/src/application/ui/layout/EntityCard/styles.scss
  assets/src/application/ui/layout/EntityPaperFrame/style.css
  assets/src/application/ui/layout/entityList/filterBar/EntityListFilterBar.tsx
  assets/src/application/ui/layout/entityList/filterBar/style.css
  assets/src/application/ui/layout/entityList/style.scss
  assets/src/application/ui/styles/root/buttons.css
  assets/src/domain/eventEditor/ui/datetimes/datesList/cardView/DateCard.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/actionsMenu/AssignDatesButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/cardView/TicketCard.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/controls/TicketsChainedButton.tsx
Labels: EDTR v2, category:assets, status:review, type:enhancement 🎉

#2500 Dates List TableView Changes; closes #2473.
  assets/src/application/constants/dateFnsFormats.ts
  assets/src/application/services/utilities/text/index.ts
  assets/src/application/ui/input/InlineEditInput/Editable.tsx
  assets/src/application/ui/input/InlineEditInput/InlineEditText.tsx
  assets/src/application/ui/layout/entityList/types.ts
  assets/src/application/ui/layout/espressoTable/TableBody.tsx
  assets/src/application/ui/layout/espressoTable/TableHeader.tsx
  assets/src/application/ui/layout/espressoTable/types.ts
  assets/src/application/ui/layout/espressoTable/utils.js
  assets/src/domain/eventEditor/ui/datetimes/datesList/cardView/DateCard.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/index.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/tableView/TableView.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/tableView/datesListTableHeader.js
  assets/src/domain/eventEditor/ui/datetimes/datesList/tableView/datesListTableHeader.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/tableView/datesListTableRow.js
  assets/src/domain/eventEditor/ui/datetimes/datesList/tableView/datesListTableRow.tsx
  assets/src/domain/shared/entities/datetimes/helpers/getBackgroundColorClassName.ts
  assets/src/domain/shared/entities/datetimes/helpers/index.ts
Labels: EDTR v2, category:assets, type:task 🧹

#2503 Add Confirmation Popup to Delete Buttons | Closes #2494
  assets/src/application/ui/input/EspressoButton/EspressoButton.tsx
  assets/src/application/ui/input/EspressoButton/types.ts
  assets/src/application/ui/layout/confirmDelete/ConfirmDelete.tsx
  assets/src/application/ui/layout/confirmDelete/index.ts
  assets/src/domain/eventEditor/ui/datetimes/datesList/actionsMenu/DeleteDateButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/actionsMenu/DeleteTicketButton.tsx
Labels: EDTR v2, status:review, type:enhancement 🎉

#2505 Reset pagination when entity count changes | Closes #2492
  assets/src/application/ui/layout/entityList/pagination/useEntityPagination.ts
Labels: EDTR v2, status:review, type:bug 🐞

#2504 Destroy wp components | Closes #2454
  assets/src/application/ui/input/BaseInput/BaseInput.tsx
  assets/src/application/ui/input/BaseInput/index.ts
  assets/src/application/ui/input/BaseInput/style.scss
  assets/src/application/ui/input/SearchInput/index.tsx
  assets/src/application/ui/input/SelectInput/SelectInput.tsx
  assets/src/application/ui/input/SelectInput/index.ts
  assets/src/application/ui/layout/entityList/filterBar/Collapsible.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/controls/DatesSortedControl.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/controls/DisplayDatesControl.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/controls/ShowDatesControl.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/controls/DisplayTicketsControl.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/controls/ShowTicketsControl.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/controls/TicketsChainedButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/controls/TicketsSortedByControl.tsx
Labels: EDTR v2, status:review, type:enhancement 🎉

#2506 Convert Dates List Table View to TypeScript; closes #2450.
  assets/src/application/ui/layout/espressoTable/types.ts
  assets/src/application/ui/styles/mixins/breakpoints.scss
  assets/src/domain/eventEditor/ui/datetimes/datesList/tableView/TableView.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/tableView/datesListTableRow.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/tableView/editor-date-entities-list-view.css
  assets/src/domain/eventEditor/ui/datetimes/datesList/tableView/styles.scss
  assets/src/domain/eventEditor/ui/datetimes/datesList/tableView/types.ts
Labels: EDTR v2, type:enhancement 🎉

#2470 Fixed issue of wait list button when Google recaptcha is enabled
  caffeinated/modules/recaptcha_invisible/assets/espresso_invisible_recaptcha.js
  modules/ticket_selector/DisplayTicketSelector.php
Labels: status:needs-testing, type:bug 🐞

#2487 Extract the logic for recalculating line items into the EE_Transaction class
  admin_pages/transactions/Transactions_Admin_Page.core.php
  core/db_classes/EE_Transaction.class.php
Labels: category:admin-pages, status:review

#2511 MOAR Filter Bar Tweaks and Other Various Style Fixes
  assets/src/application/services/utilities/cancelClickEvent.ts
  assets/src/application/ui/forms/espressoForm/styles.scss
  assets/src/application/ui/input/BaseInput/BaseInput.tsx
  assets/src/application/ui/input/BaseInput/style.scss
  assets/src/application/ui/input/InlineEditInput/InlineEditHeading.tsx
  assets/src/application/ui/input/InlineEditInput/InlineEditText.tsx
  assets/src/application/ui/input/InlineEditInput/InlineEditTextArea.tsx
  assets/src/application/ui/layout/EntityCard/styles.scss
  assets/src/application/ui/layout/EntityPaperFrame/style.css
  assets/src/application/ui/layout/entityList/filterBar/Collapsible.tsx
  assets/src/application/ui/layout/entityList/filterBar/EntityListFilterBar.tsx
  assets/src/application/ui/layout/entityList/filterBar/buttons/GridView.tsx
  assets/src/application/ui/layout/entityList/filterBar/buttons/ListView.tsx
  assets/src/application/ui/layout/entityList/filterBar/buttons/ToggleFilters.tsx
  assets/src/application/ui/layout/entityList/filterBar/style.scss
  assets/src/application/ui/layout/entityList/filterBar/types.ts
  assets/src/application/ui/layout/entityList/pagination/style.scss
  assets/src/application/ui/styles/root/buttons.css
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/DatesListEntityFilters.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/controls/DatesSortedControl.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/controls/DisplayDatesControl.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/controls/ShowDatesControl.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/useDatesListFilterState/types.ts
  assets/src/domain/eventEditor/ui/tickets/ticketsList/actionsMenu/AssignDatesButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/TicketsListEntityFilters.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/controls/DisplayTicketsControl.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/controls/ShowTicketsControl.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/controls/TicketsChainedButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/controls/TicketsSortedByControl.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/useTicketsListFilterState/types.ts
Labels: EDTR v2, category:assets, status:review, type:enhancement 🎉

#2513 Refactor and centralize enity filter state | Closes #2507
  assets/src/application/ui/layout/entityList/EntityList.tsx
  assets/src/application/ui/layout/entityList/filterBar/EntityListFilterBar.tsx
  assets/src/application/ui/layout/entityList/filterBar/filterState/index.ts
  assets/src/application/ui/layout/entityList/filterBar/filterState/reducer.ts
  assets/src/application/ui/layout/entityList/filterBar/filterState/types.ts
  assets/src/application/ui/layout/entityList/filterBar/filterState/useEntityListFilterStateManager.ts
  assets/src/application/ui/layout/entityList/filterBar/index.ts
  assets/src/application/ui/layout/entityList/filterBar/types.ts
  assets/src/application/ui/layout/entityList/filterBar/useEntityListFilterState.ts
  assets/src/application/ui/layout/entityList/pagination/EntityPagination.tsx
  assets/src/application/ui/layout/entityList/pagination/index.js
  assets/src/application/ui/layout/entityList/pagination/index.ts
  assets/src/application/ui/layout/entityList/pagination/useEntityPagination.ts
  assets/src/application/ui/layout/entityList/types.ts
  assets/src/application/ui/layout/entityList/withValidFilterState.tsx
  assets/src/domain/eventEditor/interfaces/datetimes/types.ts
  assets/src/domain/eventEditor/services/apollo/queries/datetimes/useDatetimes.ts
  assets/src/domain/eventEditor/services/context/EntityListContext/index.tsx
  assets/src/domain/eventEditor/services/context/types.ts
  assets/src/domain/eventEditor/services/filterState/datetimes/index.ts
  assets/src/domain/eventEditor/services/filterState/datetimes/reducer.ts
  assets/src/domain/eventEditor/services/filterState/datetimes/test/useDatesListFilterStateManager.test.ts
  assets/src/domain/eventEditor/services/filterState/datetimes/types.ts
  assets/src/domain/eventEditor/services/filterState/datetimes/useDatesListFilterState.ts
  assets/src/domain/eventEditor/services/filterState/datetimes/useDatesListFilterStateManager.ts
  assets/src/domain/eventEditor/services/filterState/datetimes/useFilteredDatetimes.ts
  assets/src/domain/eventEditor/services/filterState/index.ts
  assets/src/domain/eventEditor/ui/EventEditor.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/DatesListEntityFilters.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/controls/DatesSortedControl.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/controls/DatetimesToShowControl.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/controls/DisplayDatesControl.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/controls/DisplayStartOrEndDateControl.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/controls/ShowDatesControl.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/controls/SortByControl.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/useDatesListFilterState/index.test.ts
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/useDatesListFilterState/index.ts
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/useDatesListFilterState/reducer.ts
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/useDatesListFilterState/types.ts
  assets/src/domain/eventEditor/ui/datetimes/datesList/index.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/tableView/TableView.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/tableView/datesListTableHeader.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/tableView/datesListTableRow.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/tableView/types.ts
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/controls/TicketsSortedByControl.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/tableView/TableView.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/tableView/types.ts
  assets/src/domain/shared/entities/datetimes/predicates/filters/index.ts
  assets/src/domain/shared/entities/datetimes/predicates/sorters/index.test.ts
  assets/src/domain/shared/entities/datetimes/predicates/sorters/index.ts
  assets/src/domain/shared/services/filterState/index.ts
  assets/src/domain/shared/services/filterState/types.ts
Labels: EDTR v2, status:review, type:code-quality 👾, type:enhancement 🎉

#2515 IconMenuItem Refactor; closes #2481.
  assets/src/application/ui/display/IconMenuItem/index.tsx
  assets/src/application/ui/display/IconMenuItem/style.scss
  assets/src/application/ui/display/ItemCount/index.tsx
  assets/src/application/ui/display/ItemCount/style.scss
  assets/src/domain/eventEditor/ui/datetimes/datesList/actionsMenu/AssignTicketsButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/actionsMenu/AssignDatesButton.tsx
Labels: EDTR v2, type:task 🧹

#2519 Entity Details Panel Changes; closes #2508.
  assets/ZZZ/editor/events/dates-and-times/editor-date/event-date-registrations-link.js
  assets/ZZZ/editor/events/tickets/editor-ticket/ticket-registrations-link.js
  assets/ZZZ/eejs/constants.js
  assets/ZZZ/eejs/currency_config.js
  assets/ZZZ/eejs/data.js
  assets/ZZZ/eejs/index.js
  assets/ZZZ/eejs/locale.js
  assets/ZZZ/eejs/timezone-config.js
  assets/src/application/services/config/useConfigData.ts
  assets/src/application/ui/display/espressoIcon/EspressoIcon.tsx
  assets/src/application/ui/display/espressoIcon/svgPaths.ts
  assets/src/application/ui/display/espressoIcon/types.ts
  assets/src/domain/eventEditor/services/context/EventContext/index.tsx
  assets/src/domain/eventEditor/ui/datetimes/DateRegistrationsLink.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/cardView/DateDetails.tsx
  assets/src/domain/eventEditor/ui/tickets/TicketRegistrationsLink.tsx
  assets/src/domain/shared/constants/adminRoutes.ts
  assets/src/domain/shared/services/utils/url/getAdminUrl.ts
Labels: EDTR v2, type:task 🧹

#2518 Improve tickets filter state | Closes #2516
  assets/src/application/ui/layout/espressoTable/index.ts
  assets/src/application/ui/layout/espressoTable/types.ts
  assets/src/application/ui/layout/espressoTable/utils.ts
  assets/src/domain/eventEditor/interfaces/shared/types.ts
  assets/src/domain/eventEditor/interfaces/ticket/types.ts
  assets/src/domain/eventEditor/services/context/EntityListContext/DatetimesListContext.tsx
  assets/src/domain/eventEditor/services/context/EntityListContext/TicketsListContext.tsx
  assets/src/domain/eventEditor/services/context/EntityListContext/index.ts
  assets/src/domain/eventEditor/services/context/EntityListContext/withEntityListContext.tsx
  assets/src/domain/eventEditor/services/filterState/datetimes/useFilteredDatetimes.ts
  assets/src/domain/eventEditor/services/filterState/index.ts
  assets/src/domain/eventEditor/services/filterState/tickets/index.ts
  assets/src/domain/eventEditor/services/filterState/tickets/reducer.ts
  assets/src/domain/eventEditor/services/filterState/tickets/test/useTicketsListFilterStateManager.test.ts
  assets/src/domain/eventEditor/services/filterState/tickets/types.ts
  assets/src/domain/eventEditor/services/filterState/tickets/useFilteredTickets.ts
  assets/src/domain/eventEditor/services/filterState/tickets/useTicketsListFilterState.ts
  assets/src/domain/eventEditor/services/filterState/tickets/useTicketsListFilterStateManager.ts
  assets/src/domain/eventEditor/ui/EventEditor.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/DatesListEntityFilters.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/controls/index.ts
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/index.ts
  assets/src/domain/eventEditor/ui/datetimes/datesList/index.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/tableView/TableView.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/tableView/datesListTableHeader.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/tableView/datesListTableRow.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/tableView/types.ts
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/TicketsListEntityFilters.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/controls/DisplayStartOrEndDateControl.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/controls/DisplayTicketsControl.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/controls/ShowTicketsControl.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/controls/SortByControl.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/controls/TicketsSortedByControl.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/controls/TicketsToShowControl.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/controls/index.ts
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/index.ts
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/useTicketsListFilterState/index.test.ts
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/useTicketsListFilterState/index.ts
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/useTicketsListFilterState/reducer.ts
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/useTicketsListFilterState/types.ts
  assets/src/domain/eventEditor/ui/tickets/ticketsList/index.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/tableView/TableView.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/tableView/ticketsListTableHeader.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/tableView/ticketsListTableRow.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/tableView/types.ts
  assets/src/domain/shared/entities/tickets/predicates/filters/index.ts
  assets/src/domain/shared/entities/tickets/predicates/sorters/index.test.ts
  assets/src/domain/shared/entities/tickets/predicates/sorters/index.ts
  assets/src/domain/shared/services/filterState/index.ts
  assets/src/domain/shared/services/filterState/utils.ts
Labels: EDTR v2, status:review, type:code-quality 👾

#2521 Migrate Price Type Sign; closes #2362.
  assets/ZZZ/components/ui/price-type-sign/currency-sign-utils.js
  assets/ZZZ/components/ui/price-type-sign/currency-sign.js
  assets/ZZZ/components/ui/price-type-sign/index.js
  assets/ZZZ/components/ui/price-type-sign/percent-sign.js
  assets/ZZZ/components/ui/price-type-sign/price-type-sign.js
  assets/ZZZ/components/ui/price-type-sign/use-price-type-html-class.js
  assets/src/application/ui/input/priceTypeSign/CurrencySign.tsx
  assets/src/application/ui/input/priceTypeSign/PercentSign.tsx
  assets/src/application/ui/input/priceTypeSign/PriceTypeSign.tsx
  assets/src/application/ui/input/priceTypeSign/index.ts
  assets/src/application/ui/input/priceTypeSign/usePriceTypeHtmlClassName.tsx
  assets/src/application/ui/input/priceTypeSign/utils.ts
Labels: EDTR v2, type:task 🧹

#2527 Fix submit on enter for search input | Closes #2522
  assets/src/application/ui/input/SearchInput/index.tsx
Labels: EDTR v2, category:assets, status:review, type:bug 🐞

#2528 Refactor Loading Indicator and Migrate Loading Notice; closes #2360.
  assets/ZZZ/components/ui/loading-notice/index.js
  assets/ZZZ/components/ui/loading-notice/style.css
  assets/src/application/ui/display/LoadingIndicator.js
  assets/src/application/ui/display/index.ts
  assets/src/application/ui/display/loadingIndicator/LoadingIndicator.tsx
  assets/src/application/ui/display/loadingIndicator/index.ts
  assets/src/application/ui/display/loadingNotice/LoadingNotice.tsx
  assets/src/application/ui/display/loadingNotice/index.ts
  assets/src/application/ui/display/loadingNotice/types.ts
  assets/src/application/ui/layout/entityList/EntityList.tsx
Labels: EDTR v2, type:task 🧹

#2529 Move related entities to badge | Closes #2526
  assets/src/application/services/apollo/relations/reducer.ts
  assets/src/application/services/apollo/relations/test/useRelationsManager/addRelation.test.ts
  assets/src/application/services/apollo/relations/test/useRelationsManager/dropRelations.test.ts
  assets/src/application/services/apollo/relations/test/useRelationsManager/removeRelation.test.ts
  assets/src/application/services/apollo/relations/test/useRelationsManager/updateRelations.test.ts
  assets/src/application/services/apollo/relations/types.ts
  assets/src/application/services/apollo/relations/useRelationsManager.ts
  assets/src/application/ui/display/ItemCount/index.tsx
  assets/src/domain/eventEditor/services/apollo/queries/datetimes/index.ts
  assets/src/domain/eventEditor/services/apollo/queries/datetimes/test/useDatetimeItem.test.ts
  assets/src/domain/eventEditor/services/apollo/queries/datetimes/useDatetimeItem.ts
  assets/src/domain/eventEditor/services/apollo/queries/datetimes/useDatetimes.ts
  assets/src/domain/eventEditor/services/apollo/queries/datetimes/useRelatedDatetimes.ts
  assets/src/domain/eventEditor/services/apollo/queries/events/useEvent.ts
  assets/src/domain/eventEditor/services/apollo/queries/priceTypes/usePriceTypes.ts
  assets/src/domain/eventEditor/services/apollo/queries/prices/index.ts
  assets/src/domain/eventEditor/services/apollo/queries/prices/test/usePrices.test.ts
  assets/src/domain/eventEditor/services/apollo/queries/prices/usePrices.ts
  assets/src/domain/eventEditor/services/apollo/queries/prices/useRelatedPrices.ts
  assets/src/domain/eventEditor/services/apollo/queries/tickets/index.ts
  assets/src/domain/eventEditor/services/apollo/queries/tickets/test/useTicketItem.test.ts
  assets/src/domain/eventEditor/services/apollo/queries/tickets/test/useTicketPrices.test.ts
  assets/src/domain/eventEditor/services/apollo/queries/tickets/useRelatedTickets.ts
  assets/src/domain/eventEditor/services/apollo/queries/tickets/useTicketItem.ts
  assets/src/domain/eventEditor/services/apollo/queries/tickets/useTicketPrices.ts
  assets/src/domain/eventEditor/services/apollo/queries/tickets/useTickets.ts
  assets/src/domain/eventEditor/ui/datetimes/datesList/actionsMenu/AssignTicketsButton.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/cardView/DateCard.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/types.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/useAssignmentManager.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/useOnSubmitAssignments.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/useValidateTAMData.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/utils.ts
  assets/src/domain/eventEditor/ui/tickets/ticketsList/actionsMenu/AssignDatesButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/cardView/TicketCard.tsx
  assets/src/domain/shared/services/apollo/queries/currentUser/test/useCurrentUser.test.ts
  assets/src/domain/shared/services/apollo/queries/currentUser/useCurrentUser.ts
  assets/src/domain/shared/services/apollo/queries/generalSettings/test/useGeneralSettings.test.ts
  assets/src/domain/shared/services/apollo/queries/generalSettings/useGeneralSettings.ts
  assets/src/domain/shared/services/apollo/queries/types.ts
  assets/src/domain/shared/services/apollo/queries/useUpdateCache.ts
Labels: EDTR v2, status:review, type:task 🧹

#2530 LoadingNotice hotfix.
  assets/src/application/ui/display/loadingNotice/LoadingNotice.tsx
Labels: EDTR v2

#2531 Lockfile update.
  package-lock.json
Labels: type:build-process 🔨

#2532 Create Inline Infinity Edit Fields for Capacity and Quantity | Closes #2525
  assets/src/application/services/utilities/number/isInfinite.ts
  assets/src/application/services/utilities/number/parseInfinity.ts
  assets/src/application/services/utilities/parseInfinity.ts
  assets/src/application/ui/display/ItemCount/index.tsx
  assets/src/application/ui/display/ItemCount/style.scss
  assets/src/application/ui/display/enityDetails/EntityDetailsPanel.tsx
  assets/src/application/ui/display/enityDetails/style.css
  assets/src/application/ui/display/enityDetails/style.scss
  assets/src/application/ui/input/InlineEditInput/Editable.tsx
  assets/src/application/ui/input/InlineEditInput/InlineEditInfinity.tsx
  assets/src/application/ui/input/InlineEditInput/index.tsx
  assets/src/application/ui/input/InlineEditInput/style.css
  assets/src/application/ui/input/InlineEditInput/style.scss
  assets/src/application/valueObjects/InfinitySymbol.tsx
  assets/src/domain/eventEditor/services/apollo/mutations/datetimes/index.ts
  assets/src/domain/eventEditor/services/apollo/mutations/datetimes/useUpdateRelatedTickets.ts
  assets/src/domain/eventEditor/services/apollo/mutations/tickets/index.ts
  assets/src/domain/eventEditor/services/apollo/mutations/tickets/useTicketQuantityForCapacity.ts
  assets/src/domain/eventEditor/ui/datetimes/DateRegistrationsLink.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/actionsMenu/AssignTicketsButton.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/cardView/DateCapacity.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/cardView/DateCard.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/cardView/DateDetails.tsx
  assets/src/domain/eventEditor/ui/tickets/TicketRegistrationsLink.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/actionsMenu/AssignDatesButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/cardView/TicketCard.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/cardView/TicketDetails.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/cardView/TicketQuantity.tsx
Labels: EDTR v2, status:review, type:task 🧹

#2539 Improve and wire up entity search | Closes #2538
  assets/src/application/services/utilities/text/entityFieldSearch/index.test.ts
  assets/src/application/services/utilities/text/entityFieldSearch/index.ts
  assets/src/application/services/utilities/text/entityListSearch/index.test.ts
  assets/src/application/services/utilities/text/entityListSearch/index.ts
  assets/src/application/services/utilities/text/entityListSearch/types.ts
  assets/src/application/services/utilities/text/index.ts
  assets/src/domain/eventEditor/services/filterState/datetimes/useFilteredDatetimes.ts
  assets/src/domain/eventEditor/services/filterState/tickets/useFilteredTickets.ts
Labels: EDTR v2, status:review, type:enhancement 🎉

#2540 Convert Ticket Assignments Manager to use Responsive Table; closes #2491.
  assets/src/application/ui/layout/espressoTable/ResponsiveTable.tsx
  assets/src/application/ui/layout/espressoTable/TableBody.tsx
  assets/src/application/ui/layout/espressoTable/TableRow.tsx
  assets/src/application/ui/layout/espressoTable/types.ts
  assets/src/domain/eventEditor/ui/datetimes/datesList/tableView/TableView.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/RenderTable.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/TicketAssignmentsManager.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/TicketHeader.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/table/BodyCell.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/table/Table.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/table/getBodyRows.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/table/getHeaderRows.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/table/index.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/table/styles.scss
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/table/useCellIcon.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/types.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/useCellProps.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/useRowClassName.ts
  assets/src/domain/eventEditor/ui/tickets/ticketsList/tableView/TableView.tsx
  yarn.lock
Labels: EDTR v2

#2541 Create Application subscription service | Partially closes #2520
  assets/src/application/services/subscription/index.ts
  assets/src/application/services/subscription/types.ts
  assets/src/application/services/subscription/useSubscriptionService.ts
  assets/src/application/ui/layout/entityActionsMenu/constants.ts
  assets/src/application/ui/layout/entityActionsMenu/index.ts
  assets/src/application/ui/layout/entityActionsMenu/types.ts
  assets/src/application/ui/layout/entityActionsMenu/useEntityActions.ts
  assets/src/application/ui/layout/entityActionsMenu/useEntityActionsMenu.ts
  assets/src/application/ui/layout/entityActionsMenu/useEntityActionsMenuItems.tsx
  assets/src/application/ui/layout/entityActionsMenu/useEntityActionsService.ts
  assets/src/application/ui/layout/entityList/filterBar/index.ts
  assets/src/application/ui/layout/entityList/filterBar/subscription/constants.ts
  assets/src/application/ui/layout/entityList/filterBar/subscription/index.ts
  assets/src/application/ui/layout/entityList/filterBar/subscription/types.ts
  assets/src/application/ui/layout/entityList/filterBar/subscription/useFilterBarService.ts
  assets/src/domain/eventEditor/hooks/entityActionsMenu/index.ts
  assets/src/domain/eventEditor/hooks/entityActionsMenu/useEntityActionsMenuItems.tsx
  assets/src/domain/eventEditor/hooks/entityActionsMenu/useEntityActionsMenuSubscription.ts
  assets/src/domain/eventEditor/hooks/entityContext/index.ts
  assets/src/domain/eventEditor/hooks/entityContext/test/useDatetimeContext.test.tsx
  assets/src/domain/eventEditor/hooks/entityContext/test/useTicketContext.test.tsx
  assets/src/domain/eventEditor/hooks/entityContext/useDatetimeContext.ts
  assets/src/domain/eventEditor/hooks/entityContext/useTicketContext.ts
  assets/src/domain/eventEditor/hooks/entityListCacheUpdates/index.ts
  assets/src/domain/eventEditor/hooks/entityListCacheUpdates/test/useUpdateDatetimeList.test.ts
  assets/src/domain/eventEditor/hooks/entityListCacheUpdates/test/useUpdatePriceTypeList.test.ts
  assets/src/domain/eventEditor/hooks/entityListCacheUpdates/test/useUpdatePricetList.test.ts
  assets/src/domain/eventEditor/hooks/entityListCacheUpdates/test/useUpdateTicketList.test.ts
  assets/src/domain/eventEditor/hooks/entityListCacheUpdates/useUpdateDatetimeList.ts
  assets/src/domain/eventEditor/hooks/entityListCacheUpdates/useUpdateEntityList.ts
  assets/src/domain/eventEditor/hooks/entityListCacheUpdates/useUpdatePriceList.ts
  assets/src/domain/eventEditor/hooks/entityListCacheUpdates/useUpdatePriceTypeList.ts
  assets/src/domain/eventEditor/hooks/entityListCacheUpdates/useUpdateTicketList.ts
  assets/src/domain/eventEditor/hooks/filterBar/index.ts
  assets/src/domain/eventEditor/hooks/filterBar/useFilterBarSubscription.ts
  assets/src/domain/eventEditor/hooks/index.ts
  assets/src/domain/eventEditor/hooks/useEditorInitialization.ts
  assets/src/domain/eventEditor/hooks/useUpdateEntityList.ts
  assets/src/domain/eventEditor/ui/datetimes/datesList/actionsMenu/DateActionsMenu.tsx
  assets/src/domain/eventEditor/ui/datetimes/hooks/useDatesActionMenuHandler.tsx
  assets/src/domain/eventEditor/ui/datetimes/hooks/useDatesActionMenuItems.ts
  assets/src/domain/eventEditor/ui/datetimes/types.ts
  assets/src/domain/eventEditor/ui/tickets/hooks/useTicketsActionMenuHandler.tsx
  assets/src/domain/eventEditor/ui/tickets/hooks/useTicketsActionMenuItems.ts
  assets/src/domain/eventEditor/ui/tickets/ticketsList/actionsMenu/TicketActionsMenu.tsx
  assets/src/domain/eventEditor/ui/tickets/types.ts
  assets/src/domain/shared/services/apollo/queries/index.ts
  assets/src/domain/shared/types.d.ts
  assets/src/domain/shared/ui/hoc/withIsLoaded.tsx
Labels: EDTR v2, status:review, type:enhancement 🎉

#2543 Migrate DropDownMenu; closes #2351.
  assets/src/application/ui/layout/EspressoDropdownMenu/LICENSE.md
  assets/src/application/ui/layout/EspressoDropdownMenu/index.tsx
  assets/src/application/ui/layout/EspressoDropdownMenu/style.scss
  assets/src/application/ui/layout/EspressoDropdownMenu/types.ts
  assets/src/application/ui/layout/index.ts
  js-green-licenses.json
  package-lock.json
  package.json
  yarn.lock
Labels: EDTR v2

#2545 Create subscription UI Registry | Closes #2542
  assets/src/application/services/subscription/index.ts
  assets/src/application/services/subscription/types.ts
  assets/src/application/services/subscription/useUIRegistry.ts
  assets/src/application/services/utilities/types.ts
  assets/src/application/ui/layout/entityActionsMenu/index.ts
  assets/src/application/ui/layout/entityActionsMenu/types.ts
  assets/src/application/ui/layout/entityActionsMenu/useEntityActionsMenu.ts
  assets/src/application/ui/layout/entityActionsMenu/useEntityActionsMenuRegistry.ts
  assets/src/application/ui/layout/entityActionsMenu/useEntityActionsService.ts
  assets/src/application/ui/layout/entityActionsMenu/useEntityActionsSubscription.ts
  assets/src/application/ui/layout/entityList/EntityList.tsx
  assets/src/application/ui/layout/entityList/filterBar/EntityListFilterBar.tsx
  assets/src/application/ui/layout/entityList/filterBar/subscription/index.ts
  assets/src/application/ui/layout/entityList/filterBar/subscription/types.ts
  assets/src/application/ui/layout/entityList/filterBar/subscription/useFilterBarService.ts
  assets/src/application/ui/layout/entityList/filterBar/subscription/useFilterBarUIElements.tsx
  assets/src/application/ui/layout/entityList/filterBar/subscription/useFilterBarUIRegistry.ts
  assets/src/application/ui/layout/entityList/filterBar/subscription/useFilterBarUISubscription.ts
  assets/src/application/ui/layout/entityList/filterBar/types.ts
  assets/src/application/ui/layout/entityList/types.ts
  assets/src/application/ui/layout/entityList/withValidFilterState.tsx
  assets/src/domain/eventEditor/hooks/entityActionsMenu/useEntityActionsMenuItems.tsx
  assets/src/domain/eventEditor/hooks/entityActionsMenu/useEntityActionsMenuSubscription.ts
  assets/src/domain/eventEditor/hooks/filterBar/useFilterBarSubscription.ts
  assets/src/domain/eventEditor/services/constants.ts
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/DatesListEntityFilters.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/index.ts
  assets/src/domain/eventEditor/ui/datetimes/datesList/index.tsx
  assets/src/domain/eventEditor/ui/datetimes/hooks/useDatesActionMenuHandler.tsx
  assets/src/domain/eventEditor/ui/datetimes/hooks/useDatesListFilterBar.tsx
  assets/src/domain/eventEditor/ui/tickets/hooks/useTicketsActionMenuHandler.tsx
  assets/src/domain/eventEditor/ui/tickets/hooks/useTicketsListFilterBar.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/TicketsListEntityFilters.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/index.ts
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/style.scss
  assets/src/domain/eventEditor/ui/tickets/ticketsList/index.tsx
Labels: EDTR v2, status:review, type:design 📐

#2548 Move all filtering to EntityList component | Closes #2517
  assets/src/application/services/subscription/types.ts
  assets/src/application/services/subscription/useSubscriptionService.ts
  assets/src/application/ui/layout/entityActionsMenu/types.ts
  assets/src/application/ui/layout/entityList/EntityList.tsx
  assets/src/application/ui/layout/entityList/filterBar/filterState/index.ts
  assets/src/application/ui/layout/entityList/filterBar/filterState/types.ts
  assets/src/application/ui/layout/entityList/filterBar/filterState/useEntityFilterService.ts
  assets/src/application/ui/layout/entityList/filterBar/filterState/useFilteredEntities.ts
  assets/src/application/ui/layout/entityList/filterBar/subscription/constants.ts
  assets/src/application/ui/layout/entityList/filterBar/subscription/index.ts
  assets/src/application/ui/layout/entityList/filterBar/subscription/types.ts
  assets/src/application/ui/layout/entityList/filterBar/subscription/useFilterBarService.ts
  assets/src/application/ui/layout/entityList/filterBar/subscription/useFilterBarUIElements.tsx
  assets/src/application/ui/layout/entityList/filterBar/subscription/useFilterBarUIRegistry.ts
  assets/src/application/ui/layout/entityList/filterBar/subscription/useFilterBarUISubscription.ts
  assets/src/domain/eventEditor/hooks/entityActionsMenu/useEntityActionsMenuItems.tsx
  assets/src/domain/eventEditor/hooks/filterBar/index.ts
  assets/src/domain/eventEditor/hooks/filterBar/useFilterBarService.ts
  assets/src/domain/eventEditor/hooks/filterBar/useFilterBarUISubscription.ts
  assets/src/domain/eventEditor/hooks/useEditorInitialization.ts
  assets/src/domain/eventEditor/services/constants.ts
  assets/src/domain/eventEditor/services/filterState/datetimes/index.ts
  assets/src/domain/eventEditor/services/filterState/datetimes/useDatesFilterBarService.ts
  assets/src/domain/eventEditor/services/filterState/datetimes/useFilteredDatetimes.ts
  assets/src/domain/eventEditor/services/filterState/tickets/index.ts
  assets/src/domain/eventEditor/services/filterState/tickets/useFilteredTickets.ts
  assets/src/domain/eventEditor/services/filterState/tickets/useTicketsFilterBarService.ts
  assets/src/domain/eventEditor/ui/datetimes/datesList/index.tsx
  assets/src/domain/eventEditor/ui/datetimes/hooks/useDatesActionMenuHandler.tsx
  assets/src/domain/eventEditor/ui/datetimes/hooks/useDatesListFilterBar.tsx
  assets/src/domain/eventEditor/ui/tickets/hooks/useTicketsActionMenuHandler.tsx
  assets/src/domain/eventEditor/ui/tickets/hooks/useTicketsListFilterBar.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/index.tsx
Labels: EDTR v2, status:review, type:design 📐

#2552 TAM validations fix | Closes #2489
  assets/src/application/ui/layout/espressoTable/types.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/ErrorMessage.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/table/Table.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/table/getBodyRows.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/table/getHeaderRows.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/table/useColClassName.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/table/useRowClassName.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/useTicketAssignmentsManager.tsx
  core/domain/services/admin/events/editor/AdvancedEditorData.php
Labels: EDTR v2, category:assets, type:enhancement 🎉

#2551 EntityList fixes and Improvements | Closes #2550
  assets/src/application/ui/forms/espressoForm/adapters/MappedField.tsx
  assets/src/application/ui/forms/espressoForm/types.ts
  assets/src/application/ui/layout/entityActionsMenu/types.ts
  assets/src/application/ui/layout/entityList/CardList.tsx
  assets/src/application/ui/layout/entityList/EntityCardList.tsx
  assets/src/application/ui/layout/entityList/EntityList.tsx
  assets/src/application/ui/layout/entityList/index.ts
  assets/src/application/ui/layout/entityList/types.ts
  assets/src/application/ui/layout/entityList/withValidFilterState.tsx
  assets/src/domain/eventEditor/interfaces/types.ts
  assets/src/domain/eventEditor/services/context/EntityListContext/withEntityListContext.tsx
  assets/src/domain/eventEditor/ui/datetimes/DatetimeIdTag.tsx
  assets/src/domain/eventEditor/ui/datetimes/dateForm/types.ts
  assets/src/domain/eventEditor/ui/datetimes/datesList/actionsMenu/AssignTicketsButton.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/actionsMenu/DeleteDateButton.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/actionsMenu/EditDateButton.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/cardView/CardView.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/cardView/DateCard.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/cardView/index.ts
  assets/src/domain/eventEditor/ui/datetimes/datesList/index.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/tableView/TableView.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/tableView/datesListTableRow.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/tableView/types.ts
  assets/src/domain/eventEditor/ui/datetimes/datesList/types.ts
  assets/src/domain/eventEditor/ui/datetimes/types.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/withTAMProvider.tsx
  assets/src/domain/eventEditor/ui/tickets/TicketIdTag.tsx
  assets/src/domain/eventEditor/ui/tickets/hooks/useDeleteTicketHandler.ts
  assets/src/domain/eventEditor/ui/tickets/hooks/useTicketsActionMenuHandler.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/actionsMenu/AssignDatesButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/actionsMenu/DeleteTicketButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/actionsMenu/EditTicketButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/cardView/CardView.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/cardView/TicketCard.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/cardView/index.ts
  assets/src/domain/eventEditor/ui/tickets/ticketsList/index.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/tableView/TableView.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/tableView/ticketsListTableRow.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/types.ts
  assets/src/domain/eventEditor/ui/tickets/types.ts
Labels: EDTR v2, type:code-quality 👾

#2554 Move Usage of withIsLoaded HOC into action Components | Closes #2544
  assets/src/domain/eventEditor/ui/datetimes/datesList/actionsMenu/AssignTicketsButton.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/actionsMenu/DeleteDateButton.tsx
  assets/src/domain/eventEditor/ui/datetimes/hooks/useDatesActionMenuHandler.tsx
  assets/src/domain/eventEditor/ui/tickets/hooks/useTicketsActionMenuHandler.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/buttons/TicketPriceCalculatorButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/actionsMenu/AssignDatesButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/actionsMenu/DeleteTicketButton.tsx
  assets/src/domain/shared/ui/hoc/withIsLoaded.tsx
Labels: EDTR v2, status:review, type:task 🧹

#2558 TAM - fix errors | Closes #2555
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/TicketAssignmentsManager.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/types.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/useAssignmentManager.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/useTAMDatesAndTickets.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/useTAMStateManager.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/useValidateTAMData.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/utils.ts
Labels: EDTR v2, category:assets, status:review, type:bug 🐞

#2559 Create EntityTable Component | Closes #2553
  assets/src/application/ui/calendars/dateDisplay/CalendarDateRange/index.tsx
  assets/src/application/ui/calendars/dateDisplay/CalendarPageDate/index.tsx
  assets/src/application/ui/display/loadingNotice/LoadingNotice.tsx
  assets/src/application/ui/input/priceTypeSign/PercentSign.tsx
  assets/src/application/ui/layout/entityList/EntityTable.tsx
  assets/src/application/ui/layout/entityList/index.ts
  assets/src/application/ui/layout/entityList/types.ts
  assets/src/domain/eventEditor/ui/datetimes/datesList/tableView/TableView.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/tableView/bodyRowGenerator.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/tableView/headerRowGenerator.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/tableView/TableView.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/tableView/bodyRowGenerator.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/tableView/headerRowGenerator.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/tableView/styles.scss
Labels: EDTR v2, category:assets, status:review, type:enhancement 🎉

#2560 Entity edit forms: Empty box for no limit | Closes #1699
  assets/src/application/services/utilities/number/formatInfinity.ts
  assets/src/application/services/utilities/number/index.ts
  assets/src/application/ui/forms/espressoForm/fields/Field.tsx
  assets/src/application/ui/forms/espressoForm/types.ts
  assets/src/domain/eventEditor/ui/datetimes/dateForm/useDateFormConfig.ts
  assets/src/domain/eventEditor/ui/tickets/ticketForm/useTicketFormConfig.tsx
Labels: EDTR v2, category:assets, status:review, type:enhancement 🎉

#2569 Fix WP GraphQL v0.6.0 fatal error | Closes #2562
  assets/src/application/ui/input/InlineEditInput/Editable.tsx
  core/domain/services/graphql/connection_resolvers/AbstractConnectionResolver.php
Labels: EDTR v2, category:third-party-libs, status:review, type:bug 🐞

#2565 Add individual question edit links to the question group editor
  admin_pages/registration_form/assets/espresso_registration_form_admin.css
  caffeinated/admin/extend/registration_form/templates/question_groups_main_meta_box.template.php
Labels: status:needs-testing

#2570 Create TAM filters | Closes #2490
  assets/src/application/ui/input/SelectInput/index.ts
  assets/src/application/ui/input/SwitchInput/SwitchInput.tsx
  assets/src/application/ui/input/SwitchInput/index.ts
  assets/src/domain/eventEditor/services/apollo/queries/tickets/useTickets.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/TAMProvider.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/TicketAssignmentsManager.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/components/ErrorMessage.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/components/TicketAssignmentsManager.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/components/index.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/components/style.scss
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/components/table/BodyCell.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/components/table/Table.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/components/table/getBodyRows.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/components/table/getHeaderRows.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/components/table/index.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/components/table/styles.scss
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/components/table/useCellIcon.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/components/table/useColClassName.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/components/table/useRowClassName.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/context/ContextProvider.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/context/index.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/context/types.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/context/useTAMContext.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/context/withContext.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/data/index.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/data/useAssignmentManager.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/data/useDataState.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/data/useDataStateManager.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/data/useDatesAndTickets.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/data/useFilteredDatetimes.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/data/useFilteredTickets.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/data/useOnSubmitAssignments.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/data/useValidation.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/filters/FilterBar.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/filters/controls/DatesByMonthControl.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/filters/controls/ShowExpiredTicketsControl.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/filters/controls/ShowTrashedDatesControl.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/filters/controls/ShowTrashedTicketsControl.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/filters/controls/index.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/filters/filterState/index.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/filters/filterState/reducer.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/filters/filterState/types.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/filters/filterState/useFilterState.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/filters/filterState/useFilterStateManager.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/filters/index.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/index.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/types.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/useColClassName.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/useTAMDatesAndTickets.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/useTAMState.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/useTicketAssignmentsManager.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/utils.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/withTAMProvider.tsx
  assets/src/domain/shared/entities/datetimes/predicates/filters/inYearAndMonth/index.ts
  assets/src/domain/shared/entities/datetimes/predicates/isInMonth.ts
  assets/src/domain/shared/entities/datetimes/predicates/isInYear.ts
  assets/src/domain/shared/services/predicates/isTrashed/index.ts
Labels: EDTR v2, status:review, type:enhancement 🎉

#2561 Add Entity List Legend Components; closes #2547.
  assets/src/application/ui/display/ColorSwatch/index.tsx
  assets/src/application/ui/display/ColorSwatch/style.scss
  assets/src/application/ui/display/EntityListLegend/index.tsx
  assets/src/application/ui/display/EntityListLegend/types.ts
  assets/src/application/ui/display/ErrorIndicator.tsx
  assets/src/application/ui/display/index.ts
  assets/src/application/ui/input/EspressoButton/EspressoButton.tsx
  assets/src/application/ui/layout/descriptionList/DescriptionList.tsx
  assets/src/application/ui/layout/descriptionList/DescriptionListItem.tsx
  assets/src/application/ui/layout/descriptionList/index.ts
  assets/src/application/ui/layout/descriptionList/styles.scss
  assets/src/application/ui/layout/descriptionList/types.ts
  assets/src/application/ui/layout/entityList/EntityList.tsx
  assets/src/application/ui/layout/entityList/filterBar/Collapsible.tsx
  assets/src/application/ui/layout/entityList/filterBar/EntityListFilterBar.tsx
  assets/src/application/ui/layout/entityList/filterBar/buttons/GridView.tsx
  assets/src/application/ui/layout/entityList/filterBar/buttons/LegendButton/index.tsx
  assets/src/application/ui/layout/entityList/filterBar/buttons/LegendButton/style.scss
  assets/src/application/ui/layout/entityList/filterBar/buttons/ListView.tsx
  assets/src/application/ui/layout/entityList/filterBar/buttons/ToggleFilters.tsx
  assets/src/application/ui/layout/entityList/filterBar/types.ts
  assets/src/application/ui/layout/entityList/types.ts
  assets/src/application/ui/styles/root/buttons.css
  assets/src/domain/eventEditor/ui/datetimes/datesList/config.ts
  assets/src/domain/eventEditor/ui/datetimes/datesList/index.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/config.ts
  assets/src/domain/eventEditor/ui/tickets/ticketsList/index.tsx
Labels: EDTR v2

#2523 Implement email verification in check-out #121
  admin_pages/registration_form/templates/questions_main_meta_box.template.php
  core/db_classes/EE_Question.class.php
  core/db_models/EEM_Attendee.model.php
  core/db_models/EEM_Question.model.php
  core/helpers/EEH_Activation.helper.php
  core/libraries/form_sections/inputs/EE_Email_Confirm_Input.input.php
  core/libraries/form_sections/strategies/validation/EE_Equal_To_Validation_Strategy.strategy.php
  modules/single_page_checkout/reg_steps/attendee_information/EE_SPCO_Reg_Step_Attendee_Information.class.php
Labels: type:feature-request 🙏

#2563 Add space option for thousands separator currency format
  admin_pages/general_settings/General_Settings_Admin_Page.core.php
Labels: category:community-contribution, category:i18n, type:enhancement 🎉

#2546 Added main menu item to date action menu.
  assets/src/application/ui/display/espressoIcon/svgPaths.ts
  assets/src/application/ui/display/espressoIcon/types.ts
  assets/src/application/ui/layout/EntityCard/index.tsx
  assets/src/application/ui/layout/EspressoDropdownMenu/index.tsx
  assets/src/application/ui/layout/EspressoDropdownMenu/types.ts
  assets/src/application/ui/layout/entityActionsMenu/entityMenuItems/Copy.tsx
  assets/src/application/ui/layout/entityActionsMenu/entityMenuItems/Edit.tsx
  assets/src/application/ui/layout/entityActionsMenu/entityMenuItems/Trash.tsx
  assets/src/application/ui/layout/entityActionsMenu/entityMenuItems/index.ts
  assets/src/application/ui/layout/entityActionsMenu/entityMenuItems/types.ts
  assets/src/application/ui/layout/espressoDropdownMenu/Content.tsx
  assets/src/application/ui/layout/espressoDropdownMenu/LICENSE.md
  assets/src/application/ui/layout/espressoDropdownMenu/Menu.tsx
  assets/src/application/ui/layout/espressoDropdownMenu/MenuItem.tsx
  assets/src/application/ui/layout/espressoDropdownMenu/Toggle.tsx
  assets/src/application/ui/layout/espressoDropdownMenu/index.ts
  assets/src/application/ui/layout/espressoDropdownMenu/style.scss
  assets/src/application/ui/layout/espressoDropdownMenu/types.ts
  assets/src/application/ui/layout/espressoDropdownMenu/utils.ts
  assets/src/application/ui/layout/index.ts
  assets/src/domain/eventEditor/ui/datetimes/datesList/actionsMenu/DeleteDateButton.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/actionsMenu/EditDateButton.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/actionsMenu/dateEntityMainMenuItem/CopyDate.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/actionsMenu/dateEntityMainMenuItem/DateEntityMainMenuItem.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/actionsMenu/dateEntityMainMenuItem/EditDate.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/actionsMenu/dateEntityMainMenuItem/TrashDate.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/actionsMenu/dateEntityMainMenuItem/index.ts
  assets/src/domain/eventEditor/ui/datetimes/hooks/useDatesActionMenuHandler.tsx
Labels: EDTR v2

#2574 Fix Labels, Layout, and Responsive Styles for Entity List Filter Bar and Legend
  assets/src/application/ui/display/EntityListLegend/index.tsx
  assets/src/application/ui/layout/descriptionList/styles.scss
  assets/src/application/ui/layout/entityList/filterBar/EntityListFilterBar.tsx
  assets/src/application/ui/layout/entityList/filterBar/buttons/FilterButtonWrap.tsx
  assets/src/application/ui/layout/entityList/filterBar/buttons/GridView.tsx
  assets/src/application/ui/layout/entityList/filterBar/buttons/LegendButton/style.scss
  assets/src/application/ui/layout/entityList/filterBar/buttons/ListView.tsx
  assets/src/application/ui/layout/entityList/filterBar/buttons/ToggleFilters.tsx
  assets/src/application/ui/layout/entityList/filterBar/buttons/ToggleLegend.tsx
  assets/src/application/ui/layout/entityList/filterBar/style.scss
  assets/src/application/ui/layout/entityList/filterBar/types.ts
  assets/src/application/ui/layout/entityList/style.scss
Labels: EDTR v2, category:admin-page-ui-&-ux, type:enhancement 🎉

#2573 Prevent Form Submission when ENTER Key Pressed on AntD Select Inputs; closes #2568.
  assets/src/application/ui/input/MultiCheck.tsx
  assets/src/application/ui/input/Number.tsx
  assets/src/application/ui/input/SearchInput/index.tsx
  assets/src/application/ui/input/Select.tsx
  assets/src/application/ui/input/SelectInput/SelectInput.tsx
  assets/src/application/ui/input/SelectInput/index.ts
  assets/src/application/ui/input/SelectInput/types.ts
  assets/src/application/ui/input/Text.tsx
  assets/src/application/ui/input/TextArea.tsx
  assets/src/application/ui/layout/espressoDropdownMenu/Menu.tsx
Labels: EDTR v2, category:admin-page-ui-&-ux, type:bug 🐞

#2575 Hide Pagination When Only One Page of Content Exists; closes #2566.
  assets/src/application/ui/layout/entityList/pagination/EntityPagination.tsx
  assets/src/application/ui/layout/entityList/pagination/style.scss
Labels: EDTR v2, category:admin-page-ui-&-ux, type:enhancement 🎉

#2578 Filter Bar Changes: part one; partially closes #2476.
  assets/src/application/ui/display/espressoIcon/svgPaths.ts
  assets/src/application/ui/display/espressoIcon/types.ts
  assets/src/application/ui/layout/entityList/EntityList.tsx
  assets/src/application/ui/layout/entityList/filterBar/Collapsible.tsx
  assets/src/application/ui/layout/entityList/filterBar/EntityListFilterBar.tsx
  assets/src/application/ui/layout/entityList/filterBar/buttons/CardView.tsx
  assets/src/application/ui/layout/entityList/filterBar/buttons/FilterButtonWrap.tsx
  assets/src/application/ui/layout/entityList/filterBar/buttons/GridView.tsx
  assets/src/application/ui/layout/entityList/filterBar/buttons/ListView.tsx
  assets/src/application/ui/layout/entityList/filterBar/buttons/TableView.tsx
  assets/src/application/ui/layout/entityList/filterBar/buttons/ToggleFilters.tsx
  assets/src/application/ui/layout/entityList/filterBar/buttons/ToggleLegend.tsx
  assets/src/application/ui/layout/entityList/filterBar/filterState/types.ts
  assets/src/application/ui/layout/entityList/filterBar/filterState/useEntityListFilterStateManager.ts
  assets/src/application/ui/layout/entityList/filterBar/style.scss
  assets/src/application/ui/layout/entityList/filterBar/types.ts
Labels: EDTR v2, type:enhancement 🎉

#2576 Move Venue virtual URL field textarea contents into one line to avoid line breaks
  admin_pages/venues/templates/venue_virtual_location_metabox_content.template.php
Labels: category:admin-pages, type:bug 🐞

#2587 Add eventStatus schema
  core/helpers/EEH_Schema.helper.php
  core/templates/json_linked_data_for_event.template.php
Labels: category:templates-shortcodes-and-widgets, type:enhancement 🎉

#2585 Sales and Status controls - for dates and tickets; closes #2476.
  assets/src/application/ui/layout/entityList/filterBar/EntityListFilterBar.tsx
  assets/src/application/ui/layout/entityList/filterBar/style.scss
  assets/src/domain/eventEditor/services/filterState/datetimes/reducer.ts
  assets/src/domain/eventEditor/services/filterState/datetimes/test/useDatesListFilterStateManager.test.ts
  assets/src/domain/eventEditor/services/filterState/datetimes/types.ts
  assets/src/domain/eventEditor/services/filterState/datetimes/useDatesFilterBarService.ts
  assets/src/domain/eventEditor/services/filterState/datetimes/useDatesListFilterStateManager.ts
  assets/src/domain/eventEditor/services/filterState/tickets/reducer.ts
  assets/src/domain/eventEditor/services/filterState/tickets/test/useTicketsListFilterStateManager.test.ts
  assets/src/domain/eventEditor/services/filterState/tickets/types.ts
  assets/src/domain/eventEditor/services/filterState/tickets/useTicketsFilterBarService.ts
  assets/src/domain/eventEditor/services/filterState/tickets/useTicketsListFilterStateManager.ts
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/controls/DatetimesToShowControl.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/controls/SalesControl.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/controls/SortByControl.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/controls/StatusControl.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/controls/index.ts
  assets/src/domain/eventEditor/ui/datetimes/hooks/useDatesListFilterBar.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/filters/filterState/useFilterStateManager.ts
  assets/src/domain/eventEditor/ui/tickets/hooks/useTicketsListFilterBar.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/controls/SalesControl.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/controls/StatusControl.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/controls/TicketsToShowControl.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/controls/index.ts
  assets/src/domain/shared/entities/datetimes/predicates/filters/index.ts
  assets/src/domain/shared/entities/datetimes/predicates/filters/salesFilter.ts
  assets/src/domain/shared/entities/datetimes/predicates/filters/statusFilter.ts
  assets/src/domain/shared/entities/datetimes/predicates/filters/types.ts
  assets/src/domain/shared/entities/datetimes/predicates/isActive.ts
  assets/src/domain/shared/entities/datetimes/predicates/isExpired.ts
  assets/src/domain/shared/entities/datetimes/predicates/isRecentlyExpired/index.ts
  assets/src/domain/shared/entities/datetimes/predicates/isUpcoming.ts
  assets/src/domain/shared/entities/tickets/predicates/filters/allOnSaleAndPending/index.test.ts
  assets/src/domain/shared/entities/tickets/predicates/filters/expiredOnly/index.test.ts
  assets/src/domain/shared/entities/tickets/predicates/filters/index.ts
  assets/src/domain/shared/entities/tickets/predicates/filters/onSaleOnly/index.test.ts
  assets/src/domain/shared/entities/tickets/predicates/filters/pendingOnly/index.test.ts
  assets/src/domain/shared/entities/tickets/predicates/filters/salesFilter.ts
  assets/src/domain/shared/entities/tickets/predicates/filters/statusFilter.ts
  assets/src/domain/shared/entities/tickets/predicates/filters/types.ts
  assets/src/domain/shared/entities/tickets/predicates/index.ts
  assets/src/domain/shared/entities/tickets/predicates/isExpired/index.test.ts
  assets/src/domain/shared/entities/tickets/predicates/isExpired/index.ts
  assets/src/domain/shared/entities/tickets/predicates/isOnSale/index.test.ts
  assets/src/domain/shared/entities/tickets/predicates/isOnSale/index.ts
  assets/src/domain/shared/entities/tickets/predicates/isPending/index.test.ts
  assets/src/domain/shared/entities/tickets/predicates/isPending/index.ts
  assets/src/domain/shared/services/utils/dateAndTime.ts
Labels: EDTR v2, type:enhancement 🎉

#2593 Fix mutation cache updates | Closes #2584
  assets/src/application/services/index.js
  assets/src/application/services/index.ts
  assets/src/application/services/utilities/index.ts
  assets/src/application/services/utilities/predicates/index.ts
  assets/src/domain/eventEditor/services/apollo/initialization/useCacheRehydration.ts
  assets/src/domain/eventEditor/services/apollo/initialization/useCacheRehydrationData.ts
  assets/src/domain/eventEditor/services/apollo/initialization/useInitQueries.ts
  assets/src/domain/eventEditor/services/apollo/mutations/datetimes/index.ts
  assets/src/domain/eventEditor/services/apollo/mutations/datetimes/updateTicketCache.ts
  assets/src/domain/eventEditor/services/apollo/mutations/datetimes/useDatetimeMutationHandler.ts
  assets/src/domain/eventEditor/services/apollo/mutations/datetimes/useDatetimeMutator.ts
  assets/src/domain/eventEditor/services/apollo/mutations/datetimes/useMutationVariables.ts
  assets/src/domain/eventEditor/services/apollo/mutations/datetimes/useOnCreateDatetime.ts
  assets/src/domain/eventEditor/services/apollo/mutations/datetimes/useOnDeleteDatetime.ts
  assets/src/domain/eventEditor/services/apollo/mutations/datetimes/useOnUpdateDatetime.ts
  assets/src/domain/eventEditor/services/apollo/mutations/datetimes/useOptimisticResponse.ts
  assets/src/domain/eventEditor/services/apollo/mutations/datetimes/useUpdateDatetimeCache.ts
  assets/src/domain/eventEditor/services/apollo/mutations/datetimes/useUpdateRelatedTickets.ts
  assets/src/domain/eventEditor/services/apollo/mutations/prices/index.ts
  assets/src/domain/eventEditor/services/apollo/mutations/prices/useOnCreatePrice.ts
  assets/src/domain/eventEditor/services/apollo/mutations/prices/useOnDeletePrice.ts
  assets/src/domain/eventEditor/services/apollo/mutations/prices/useOnUpdatePrice.ts
  assets/src/domain/eventEditor/services/apollo/mutations/prices/usePriceMutationHandler.ts
  assets/src/domain/eventEditor/services/apollo/mutations/prices/usePriceMutator.ts
  assets/src/domain/eventEditor/services/apollo/mutations/prices/useUpdatePriceCache.ts
  assets/src/domain/eventEditor/services/apollo/mutations/tickets/index.ts
  assets/src/domain/eventEditor/services/apollo/mutations/tickets/updatePriceCache.ts
  assets/src/domain/eventEditor/services/apollo/mutations/tickets/useOnCreateTicket.ts
  assets/src/domain/eventEditor/services/apollo/mutations/tickets/useOnDeleteTicket.ts
  assets/src/domain/eventEditor/services/apollo/mutations/tickets/useOnUpdateTicket.ts
  assets/src/domain/eventEditor/services/apollo/mutations/tickets/useOptimisticResponse.ts
  assets/src/domain/eventEditor/services/apollo/mutations/tickets/useTicketMutationHandler.ts
  assets/src/domain/eventEditor/services/apollo/mutations/tickets/useTicketMutator.ts
  assets/src/domain/eventEditor/services/apollo/mutations/tickets/useTicketQuantityForCapacity.ts
  assets/src/domain/eventEditor/services/apollo/mutations/tickets/useUpdateTicketCache.ts
  assets/src/domain/eventEditor/services/apollo/mutations/types.ts
  assets/src/domain/eventEditor/services/apollo/mutations/useMutator.ts
  assets/src/domain/eventEditor/services/apollo/queries/events/index.ts
  assets/src/domain/eventEditor/services/apollo/queries/events/queries.ts
  assets/src/domain/eventEditor/services/apollo/queries/index.ts
  assets/src/domain/eventEditor/services/apollo/queries/prices/test/usePriceQueryOptions.test.ts
  assets/src/domain/eventEditor/services/apollo/queries/prices/usePriceQueryOptions.ts
  assets/src/domain/eventEditor/services/apollo/queries/tickets/test/useTicketQueryOptions.test.ts
  assets/src/domain/eventEditor/services/apollo/queries/tickets/useTicketQueryOptions.ts
Labels: EDTR v2, category:assets, status:review, type:bug 🐞

#2564 Add action hooks to Questions editor admin page template
  admin_pages/registration_form/templates/questions_main_meta_box.template.php
Labels: category:admin-pages, category:community-contribution, status:review, type:enhancement 🎉

#2594 Fix Filter Bar Filter Markup and CSS Classes; closes #2592.
  assets/src/application/services/utilities/string/index.ts
  assets/src/application/services/utilities/string/isEmpty.ts
  assets/src/application/services/utilities/text/changeCase/index.ts
  assets/src/application/ui/input/BaseInput/BaseInput.tsx
  assets/src/application/ui/input/EspressoButton/EspressoButton.tsx
  assets/src/application/ui/input/SearchInput/index.tsx
  assets/src/application/ui/layout/entityList/filterBar/EntityListFilterBar.tsx
  assets/src/application/ui/layout/entityList/filterBar/style.scss
  assets/src/domain/eventEditor/ui/datetimes/hooks/useDatesListFilterBar.tsx
  assets/src/domain/eventEditor/ui/tickets/hooks/useTicketsListFilterBar.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/controls/TicketsChainedButton.tsx
Labels: EDTR v2, type:enhancement 🎉

#2596 Add eventAttendanceMode schema property
  core/helpers/EEH_Schema.helper.php
  core/templates/json_linked_data_for_event.template.php
Labels: category:templates-shortcodes-and-widgets, status:needs-testing, type:enhancement 🎉

#2606 Fix TAM relations | Closes #2601
  assets/src/domain/eventEditor/services/apollo/mutations/datetimes/useOptimisticResponse.ts
  assets/src/domain/eventEditor/services/apollo/mutations/tickets/useOptimisticResponse.ts
Labels: EDTR v2, category:admin-page-ui-&-ux, status:review, type:bug 🐞

#2579 Remove link to event's checkins when context is already viewing event's checkins
  caffeinated/admin/extend/registrations/EE_Event_Registrations_List_Table.class.php
Labels: status:needs-testing

#617 Fix sideloader using incorrect _upload_from property name.
  core/helpers/EEH_Sideloader.helper.php
Labels: category:i18n, status:needs-testing, type:bug 🐞

#2605 TimezoneTimeInfo
  assets/src/application/constants/dateFnsFormats.ts
  assets/src/application/services/config/test/data.ts
  assets/src/application/services/hooks/useTimeZoneTime.ts
  assets/src/application/ui/calendars/dateDisplay/BiggieCalendarDate/index.tsx
  assets/src/application/ui/calendars/dateDisplay/BiggieCalendarDate/style.css
  assets/src/application/ui/calendars/dateDisplay/BiggieCalendarDate/style.scss
  assets/src/application/ui/calendars/dateDisplay/CalendarDateRange/index.tsx
  assets/src/application/ui/calendars/dateDisplay/MediumCalendarDate/index.tsx
  assets/src/application/ui/calendars/dateDisplay/MediumCalendarDate/style.scss
  assets/src/application/ui/calendars/dateDisplay/TimezoneTimeInfo/index.tsx
  assets/src/application/ui/calendars/dateDisplay/TimezoneTimeInfo/style.scss
  assets/src/application/valueObjects/config/Locale.ts
Labels: EDTR v2, category:assets, type:enhancement 🎉

#2599 Tests for Ticket Price Calculator | Closes #2151
  assets/src/domain/eventEditor/services/apollo/queries/prices/test/data.ts
  assets/src/domain/eventEditor/services/apollo/queries/tickets/test/data.ts
  assets/src/domain/eventEditor/services/context/TestContext/useSetGlobalStatusFlags.ts
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/context/types.ts
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/data/test/TestWrapper.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/data/test/data.addPrice.test.ts
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/data/test/data.calculations.test.ts
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/data/test/data.deletePrice.test.ts
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/data/test/data.updatePrice.test.ts
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/data/test/useInitialState.test.ts
Labels: EDTR v2, category:unit-tests, status:review

#2602 Fix Tickets List Filter Bar isChained Filter; closess #2595.
  assets/src/application/ui/display/viewport/LICENSE.md
  assets/src/application/ui/display/viewport/index.js
  assets/src/application/ui/display/viewport/withViewportMatch.js
  assets/src/application/ui/input/BaseInput/BaseInput.tsx
  assets/src/application/ui/input/BaseInput/index.ts
  assets/src/application/ui/input/EspressoButton/EspressoButton.tsx
  assets/src/application/ui/input/EspressoButton/Tooltip.tsx
  assets/src/application/ui/input/EspressoButton/style.scss
  assets/src/application/ui/input/SearchInput/index.tsx
  assets/src/application/ui/input/SelectInput/SelectInput.tsx
  assets/src/application/ui/input/SwitchInput/SwitchInput.tsx
  assets/src/application/ui/input/index.ts
  assets/src/application/ui/input/withLabel/index.tsx
  assets/src/application/ui/input/withLabel/style.scss
  assets/src/application/ui/layout/entityList/filterBar/buttons/FilterButtonWrap.tsx
  assets/src/application/ui/layout/entityList/filterBar/style.scss
  assets/src/application/ui/layout/entityList/filterBar/types.ts
  assets/src/domain/eventEditor/services/filterState/tickets/test/useTicketsListFilterStateManager.test.ts
  assets/src/domain/eventEditor/services/filterState/tickets/useTicketsListFilterStateManager.ts
  assets/src/domain/eventEditor/ui/tickets/hooks/useTicketsListFilterBar.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/controls/StatusControl.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/controls/TicketsChainedButton.tsx
Labels: EDTR v2, type:enhancement 🎉

#2612 Fix EDTR timezone issues | Closes #2610
  assets/src/application/services/hooks/index.ts
  assets/src/application/services/hooks/test/useIfMounted.test.ts
  assets/src/application/services/hooks/test/useTimeZoneTime.test.ts
  assets/src/application/services/hooks/useTimeZoneTime.ts
  assets/src/application/services/utilities/date/index.ts
  assets/src/application/services/utilities/date/localToUtc.ts
  assets/src/application/services/utilities/date/test/localToUtc.test.ts
  assets/src/application/services/utilities/date/test/utcToLocal.test.ts
  assets/src/application/services/utilities/date/utcToLocal.ts
  assets/src/application/ui/calendars/dateDisplay/BiggieCalendarDate/index.tsx
  assets/src/application/ui/calendars/dateDisplay/CalendarDateRange/index.tsx
  assets/src/application/ui/calendars/dateDisplay/CalendarPageDate/index.tsx
  assets/src/application/ui/calendars/dateDisplay/MediumCalendarDate/index.tsx
  assets/src/domain/eventEditor/ui/datetimes/dateForm/useDateFormConfig.ts
  assets/src/domain/eventEditor/ui/tickets/ticketForm/useTicketFormConfig.tsx
  assets/src/domain/shared/services/utils/dateAndTime.ts
Labels: EDTR v2, category:i18n, status:review, type:bug 🐞

#2614 Add Component for Switching Date Display in Entity Cards; closes #2598.
  assets/ZZZ/editor/events/dates-and-times/editor-date/grid-view/event-date-calendar-date.js
  assets/src/application/ui/calendars/dateDisplay/BiggieCalendarDate/index.tsx
  assets/src/application/ui/calendars/dateDisplay/CalendarDateRange/index.tsx
  assets/src/application/ui/calendars/dateDisplay/CalendarDateSwitcher/index.tsx
  assets/src/application/ui/calendars/dateDisplay/index.ts
  assets/src/domain/eventEditor/ui/datetimes/datesList/cardView/DateCard.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/cardView/TicketCard.tsx
Labels: EDTR v2

#2623 Purge Unwanted Dependencies | Closes #2617
  assets/src/application/constants/index.ts
  assets/src/application/services/utilities/boolean/index.ts
  assets/src/application/services/utilities/dom/index.ts
  assets/src/application/ui/display/Avatar.tsx
  assets/src/application/ui/display/EntityIDs/index.tsx
  assets/src/application/ui/display/ErrorIndicator.tsx
  assets/src/application/ui/input/EspressoButton/EspressoButton.tsx
  assets/src/application/ui/input/EspressoButton/Tooltip.tsx
  assets/src/application/ui/layout/entityList/filterBar/EntityListFilterBar.tsx
  assets/src/application/ui/layout/entityList/filterBar/buttons/CardView.tsx
  assets/src/application/ui/layout/entityList/filterBar/buttons/CardViewFilterButton.tsx
  assets/src/application/ui/layout/entityList/filterBar/buttons/FilterButtonWrap.tsx
  assets/src/application/ui/layout/entityList/filterBar/buttons/TableView.tsx
  assets/src/application/ui/layout/entityList/filterBar/buttons/TableViewFilterButton.tsx
  assets/src/application/ui/layout/entityList/filterBar/buttons/ToggleFilters.tsx
  assets/src/application/ui/layout/entityList/filterBar/buttons/ToggleFiltersButton.tsx
  assets/src/application/ui/layout/entityList/filterBar/buttons/ToggleLegendButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/components/TicketPriceCalculator.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/cardView/TicketDetails.tsx
  assets/src/domain/shared/ui/RelationsSelector/index.tsx
  assets/src/domain/shared/ui/dateRangeInput/DateRangePicker.tsx
  assets/src/domain/shared/ui/dateRangeInput/dateDisplay.tsx
  assets/src/domain/shared/ui/dateRangeInput/formatSelect.ts
  assets/src/domain/shared/ui/dateRangeInput/style.css
Labels: EDTR v2, category:assets, status:review, type:task 🧹

#2620 DatePicker and TimePicker fixes | Closes #2616
  assets/src/application/ui/input/DateTimePicker/CustomDate.ts
  assets/src/application/ui/input/DateTimePicker/DatePicker.tsx
  assets/src/application/ui/input/DateTimePicker/TimePicker.tsx
Labels: EDTR v2, status:review, type:bug 🐞

#2630 EDTR Cache ID for memoization | Closes #2621
  assets/src/application/services/apollo/types.ts
  assets/src/domain/eventEditor/services/apollo/mutations/datetimes/useOptimisticResponse.ts
  assets/src/domain/eventEditor/services/apollo/mutations/tickets/useOptimisticResponse.ts
  assets/src/domain/eventEditor/services/apollo/mutations/tickets/useTicketMutationHandler.ts
  assets/src/domain/eventEditor/services/apollo/queries/datetimes/queries.ts
  assets/src/domain/eventEditor/services/apollo/queries/datetimes/test/data.ts
  assets/src/domain/eventEditor/services/apollo/queries/datetimes/useDatetimeIds.ts
  assets/src/domain/eventEditor/services/apollo/queries/datetimes/useDatetimeItem.ts
  assets/src/domain/eventEditor/services/apollo/queries/datetimes/useDatetimes.ts
  assets/src/domain/eventEditor/services/apollo/queries/datetimes/useRelatedDatetimes.ts
  assets/src/domain/eventEditor/services/apollo/queries/priceTypes/queries.ts
  assets/src/domain/eventEditor/services/apollo/queries/priceTypes/test/data.ts
  assets/src/domain/eventEditor/services/apollo/queries/priceTypes/usePriceTypeForPrice.ts
  assets/src/domain/eventEditor/services/apollo/queries/priceTypes/usePriceTypes.ts
  assets/src/domain/eventEditor/services/apollo/queries/prices/queries.ts
  assets/src/domain/eventEditor/services/apollo/queries/prices/test/data.ts
  assets/src/domain/eventEditor/services/apollo/queries/prices/usePrices.ts
  assets/src/domain/eventEditor/services/apollo/queries/prices/useRelatedPrices.ts
  assets/src/domain/eventEditor/services/apollo/queries/tickets/queries.ts
  assets/src/domain/eventEditor/services/apollo/queries/tickets/test/data.ts
  assets/src/domain/eventEditor/services/apollo/queries/tickets/test/useTicketPrices.test.ts
  assets/src/domain/eventEditor/services/apollo/queries/tickets/useRelatedTickets.ts
  assets/src/domain/eventEditor/services/apollo/queries/tickets/useTicketIds.ts
  assets/src/domain/eventEditor/services/apollo/queries/tickets/useTicketItem.ts
  assets/src/domain/eventEditor/services/apollo/queries/tickets/useTickets.ts
  assets/src/domain/eventEditor/services/apollo/types.ts
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/defaultPriceModifier.ts
  assets/src/domain/shared/entities/datetimes/predicates/filters/tests/data.ts
  assets/src/domain/shared/entities/prices/predicates/priceFields.ts
  assets/src/domain/shared/entities/tickets/predicates/test/data.ts
  assets/src/domain/shared/entities/tickets/predicates/ticketFields.ts
  assets/src/domain/shared/services/predicates/index.ts
  assets/src/domain/shared/services/predicates/listPredicates.ts
  assets/src/domain/shared/services/predicates/selectionById/index.ts
  core/domain/services/admin/events/editor/AdvancedEditorData.php
  core/domain/services/graphql/resolvers/FieldResolver.php
  core/domain/services/graphql/types/Country.php
  core/domain/services/graphql/types/Datetime.php
  core/domain/services/graphql/types/Event.php
  core/domain/services/graphql/types/Price.php
  core/domain/services/graphql/types/PriceType.php
  core/domain/services/graphql/types/State.php
  core/domain/services/graphql/types/Ticket.php
  core/domain/services/graphql/types/Venue.php
Labels: EDTR v2, category:assets, status:review, type:enhancement 🎉

#2633 Fix no prices after creating a ticket | Closes #2632
  assets/src/domain/eventEditor/hooks/entityListCacheUpdates/test/useUpdatePriceTypeList.test.ts
  assets/src/domain/eventEditor/hooks/entityListCacheUpdates/test/useUpdatePricetList.test.ts
  assets/src/domain/eventEditor/services/apollo/initialization/useCacheRehydration.ts
  assets/src/domain/eventEditor/services/apollo/mutations/datetimes/test/createDatetime.test.ts
  assets/src/domain/eventEditor/services/apollo/mutations/datetimes/test/deleteDatetime.test.ts
  assets/src/domain/eventEditor/services/apollo/mutations/datetimes/test/updateDatetime.test.ts
  assets/src/domain/eventEditor/services/apollo/mutations/datetimes/useOnCreateDatetime.ts
  assets/src/domain/eventEditor/services/apollo/mutations/datetimes/useOnDeleteDatetime.ts
  assets/src/domain/eventEditor/services/apollo/mutations/prices/test/createPrice.test.ts
  assets/src/domain/eventEditor/services/apollo/mutations/prices/test/deletePrice.test.ts
  assets/src/domain/eventEditor/services/apollo/mutations/tickets/test/createTicket.test.ts
  assets/src/domain/eventEditor/services/apollo/mutations/tickets/test/deleteTicket.test.ts
  assets/src/domain/eventEditor/services/apollo/mutations/tickets/test/updateTicket.test.ts
  assets/src/domain/eventEditor/services/apollo/mutations/tickets/useOnCreateTicket.ts
  assets/src/domain/eventEditor/services/apollo/mutations/tickets/useOnDeleteTicket.ts
  assets/src/domain/eventEditor/services/apollo/queries/datetimes/test/useDatetimeIds.test.ts
  assets/src/domain/eventEditor/services/apollo/queries/prices/test/usePriceQueryOptions.test.ts
  assets/src/domain/eventEditor/services/apollo/queries/tickets/test/useTicketIds.test.ts
  assets/src/domain/eventEditor/services/apollo/queries/tickets/test/useTicketPrices.test.ts
  assets/src/domain/eventEditor/services/apollo/queries/tickets/test/useTicketQueryOptions.test.ts
  assets/src/domain/eventEditor/ui/tickets/hooks/useDeleteTicketHandler.ts
  assets/src/domain/shared/entities/prices/predicates/selectionPredicates/index.test.ts
  assets/src/domain/shared/services/predicates/selectionById/index.test.ts
Labels: EDTR v2, category:assets, status:review, type:bug 🐞

#2635 Update RFF and React packages | Closes #2634
  package.json
  yarn.lock
Labels: EDTR v2, category:assets, status:review, type:task 🧹

#2628 Refactor Button Tooltip and Label as HOCs
  assets/src/application/ui/display/EntityListLegend/index.tsx
  assets/src/application/ui/display/EntityListLegend/types.ts
  assets/src/application/ui/display/LoadingIndicator.tsx
  assets/src/application/ui/display/entityDetailsPanel/DetailsSeparator.tsx
  assets/src/application/ui/display/entityDetailsPanel/EntityDetail.tsx
  assets/src/application/ui/display/entityDetailsPanel/EntityDetailsPanel.tsx
  assets/src/application/ui/display/entityDetailsPanel/index.ts
  assets/src/application/ui/display/entityDetailsPanel/style.scss
  assets/src/application/ui/display/entityDetailsPanel/types.ts
  assets/src/application/ui/display/index.ts
  assets/src/application/ui/display/loadingIndicator/index.ts
  assets/src/application/ui/display/viewport/LICENSE.md
  assets/src/application/ui/display/viewport/index.js
  assets/src/application/ui/display/viewport/withViewportMatch.js
  assets/src/application/ui/display/withLabel/index.ts
  assets/src/application/ui/display/withLabel/style.scss
  assets/src/application/ui/display/withLabel/types.ts
  assets/src/application/ui/display/withLabel/withLabel.tsx
  assets/src/application/ui/display/withTooltip/index.ts
  assets/src/application/ui/display/withTooltip/style.scss
  assets/src/application/ui/display/withTooltip/types.ts
  assets/src/application/ui/display/withTooltip/withTooltip.tsx
  assets/src/application/ui/input/EspressoButton/EspressoButton.tsx
  assets/src/application/ui/input/EspressoButton/Tooltip.tsx
  assets/src/application/ui/input/EspressoButton/style.scss
  assets/src/application/ui/input/EspressoButton/types.ts
  assets/src/application/ui/input/SearchInput/SearchInput.tsx
  assets/src/application/ui/input/SearchInput/index.tsx
  assets/src/application/ui/input/SelectInput/SelectInput.tsx
  assets/src/application/ui/input/SwitchInput/SwitchInput.tsx
  assets/src/application/ui/input/index.ts
  assets/src/application/ui/input/withLabel/index.tsx
  assets/src/application/ui/input/withLabel/style.scss
  assets/src/application/ui/layout/descriptionList/styles.scss
  assets/src/application/ui/layout/entityActionsMenu/entityMenuItems/Copy.tsx
  assets/src/application/ui/layout/entityActionsMenu/entityMenuItems/Edit.tsx
  assets/src/application/ui/layout/entityActionsMenu/entityMenuItems/Trash.tsx
  assets/src/application/ui/layout/entityList/filterBar/EntityListFilterBar.tsx
  assets/src/application/ui/layout/entityList/filterBar/buttons/CardViewFilterButton.tsx
  assets/src/application/ui/layout/entityList/filterBar/buttons/FilterButtonWrap.tsx
  assets/src/application/ui/layout/entityList/filterBar/buttons/TableViewFilterButton.tsx
  assets/src/application/ui/layout/entityList/filterBar/buttons/ToggleFiltersButton.tsx
  assets/src/application/ui/layout/entityList/filterBar/buttons/ToggleLegendButton.tsx
  assets/src/application/ui/layout/entityList/filterBar/style.scss
  assets/src/application/ui/layout/entityList/filterBar/types.ts
  assets/src/application/ui/layout/entityList/style.scss
  assets/src/application/ui/layout/espressoDropdownMenu/MenuItem.tsx
  assets/src/application/ui/layout/espressoDropdownMenu/Toggle.tsx
  assets/src/application/ui/styles/mixins/breakpoints.scss
  assets/src/application/ui/styles/root/buttons.css
  assets/src/domain/eventEditor/ui/datetimes/datesList/actionsMenu/dateEntityMainMenuItem/EditDate.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/cardView/DateDetails.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/cardView/TicketDetails.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/controls/TicketsChainedButton.tsx
Labels: EDTR v2, category:assets, type:task 🧹

#2638 Fix build error after package update | Closes #2637
  assets/src/application/ui/display/withTooltip/withTooltip.tsx
  assets/src/application/ui/layout/espressoDropdownMenu/Menu.tsx
  assets/src/application/ui/styles/themes/default/config.ts
  assets/src/application/ui/styles/themes/default/index.ts
  package.json
  yarn.lock
Labels: EDTR v2, category:assets, status:review, type: tooling :hammer:

#2631 Add Main Menu Item to Ticket Actions Menu; closes #2618.
  assets/src/application/ui/layout/entityActionsMenu/entityMenuItems/Trash.tsx
  assets/src/application/ui/layout/espressoDropdownMenu/style.scss
  assets/src/domain/eventEditor/ui/datetimes/datesList/actionsMenu/DeleteDateButton.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/actionsMenu/EditDateButton.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/actionsMenu/dateEntityMainMenuItem/index.ts
  assets/src/domain/eventEditor/ui/datetimes/datesList/actionsMenu/dropdown/CopyDate.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/actionsMenu/dropdown/DateMainMenuItem.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/actionsMenu/dropdown/EditDate.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/actionsMenu/dropdown/TrashDate.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/actionsMenu/dropdown/index.ts
  assets/src/domain/eventEditor/ui/datetimes/hooks/useDatesActionMenuHandler.tsx
  assets/src/domain/eventEditor/ui/tickets/hooks/useTicketsActionMenuHandler.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/actionsMenu/DeleteTicketButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/actionsMenu/EditTicketButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/actionsMenu/dropdown/CopyTicket.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/actionsMenu/dropdown/EditTicket.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/actionsMenu/dropdown/TicketMainMenuItem.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/actionsMenu/dropdown/TrashTicket.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/actionsMenu/dropdown/index.ts
  assets/src/domain/shared/entities/tickets/predicates/ticketFields.ts
Labels: EDTR v2, category:admin-page-ui-&-ux

#2629 Dynamically Change Calendar Date Header Text; closes #2619.
  assets/src/application/services/utilities/date/index.ts
  assets/src/application/services/utilities/date/switchTenseForDate.ts
  assets/src/application/ui/calendars/dateDisplay/CalendarDateSwitcher/index.tsx
  assets/src/application/ui/calendars/dateDisplay/CalendarDateSwitcher/types.ts
  assets/src/domain/eventEditor/ui/datetimes/datesList/cardView/DateCard.tsx
Labels: EDTR v2, type:task 🧹
