Repository eventespresso/event-espresso-core, pull requests merged in 2020-06, with the labels that each got.

#2906 Fix duplicate key warning in TPC
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/hooks/useAddDefaultPrices.ts
Labels: EDTR v2, category:admin-page-ui-&-ux, type:bug 🐞

#2888 Added ticket price amount labels.
  assets/src/application/ui/input/InputWithLabel/index.tsx
  assets/src/application/ui/input/InputWithLabel/style.scss
  assets/src/application/ui/input/index.ts
  assets/src/application/ui/input/priceTypeSign/utils.ts
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/components/table/styles.scss
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/components/table/useBodyRowGenerator.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/components/table/useFooterRowGenerator.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/components/table/useHeaderRowGenerator.ts
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/fields/BaseField.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/fields/BaseNumberInputField.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/fields/MoneyField/index.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/fields/MoneyField/style.scss
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/fields/MoneyField/types.ts
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/fields/index.ts
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/fields/types.ts
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/fields/useBaseField.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/fields/usePriceAmount.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/inputs/PriceAmountInput.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/inputs/styles.scss
  assets/src/infrastructure/ui/inputs/InputWithLabel.tsx
  assets/src/infrastructure/ui/inputs/NumberInput.tsx
  assets/src/infrastructure/ui/inputs/index.ts
  assets/src/infrastructure/ui/inputs/types.ts
Labels: EDTR v2, category:admin-page-ui-&-ux, type:enhancement 🎉

#2870 Plinko Routing
  admin_pages/payments/Payments_Admin_Page.core.php
  core/EE_Dependency_Map.core.php
  core/EE_Error.core.php
  core/EE_Front_Controller.core.php
  core/EE_System.core.php
  core/admin/EE_Admin.core.php
  core/admin/EE_Admin_Page_CPT.core.php
  core/domain/entities/routing/handlers/admin/AdminRoute.php
  core/domain/entities/routing/handlers/admin/EspressoEventEditor.php
  core/domain/entities/routing/handlers/admin/EspressoEventsAdmin.php
  core/domain/entities/routing/handlers/admin/EspressoLegacyAdmin.php
  core/domain/entities/routing/handlers/shared/RoutingRequests.php
  core/domain/services/assets/EspressoLegacyAdminAssetManager.php
  core/domain/services/assets/LegacyAccountingAssetManager.php
  core/libraries/form_sections/strategies/display/EE_Admin_File_Uploader_Display_Strategy.strategy.php
  core/services/dependencies/DependencyResolver.php
  core/services/loaders/ClassInterfaceCache.php
  core/services/routing/RouteCollection.php
  core/services/routing/RouteHandler.php
  core/services/routing/RouteMatchSpecificationDependencyResolver.php
  core/services/routing/RouteMatchSpecificationFactory.php
  core/services/shortcodes/LegacyShortcodesManager.php
  modules/core_rest_api/EED_Core_Rest_Api.module.php
  tests/includes/CoreLoader.php
  tests/includes/EE_REST_TestCase.php
  tests/includes/EE_UnitTestCase.class.php
  tests/mocks/core/domain/entities/routing/handlers/frontend/ShortcodeRequestsMock.php
  tests/mocks/core/domain/entities/routing/handlers/shared/GQLRequestsMock.php
  tests/mocks/core/domain/entities/routing/handlers/shared/RestApiRequestsMock.php
  tests/mocks/core/domain/entities/routing/handlers/shared/RoutingRequestsMock.php
  tests/mocks/core/services/dependencies/DependencyResolverMock.php
  tests/testcases/admin_pages/registrations/Registrations_Admin_Page_Test.php
  tests/testcases/core/EE_Dependency_Map_Test.php
  tests/testcases/core/EE_Registry_Test.php
  tests/testcases/core/admin/EE_Admin_Tests.php
  tests/testcases/core/db_classes/EE_CPT_Base_Test.php
  tests/testcases/core/domain/services/graphql/GraphQLUnitTestCase.php
  tests/testcases/core/libraries/rest_api/controllers/Checkin_Test.php
  tests/testcases/core/libraries/rest_api/controllers/Config_Test.php
  tests/testcases/core/services/dependencies/DependencyResolverTest.php
Labels: category:core-plugin, type:enhancement 🎉

#2907 RTL adjustments.
  assets/src/application/ui/input/Button/ButtonGroup/style.scss
  assets/src/application/ui/input/Button/style.scss
  assets/src/infrastructure/ui/display/pagination/Pagination.tsx
  assets/src/infrastructure/ui/display/pagination/style.scss
  assets/src/infrastructure/ui/display/steps/style.scss
  assets/src/infrastructure/ui/inputs/style.scss
  assets/src/infrastructure/ui/layout/modal/Modal.tsx
  assets/src/infrastructure/ui/layout/modal/styles.scss
Labels: EDTR v2, category:admin-page-ui-&-ux

#2910 Update packages and remove graphql-tools
  assets/src/domain/eventEditor/services/context/TestContext/TestContextProviders.tsx
  assets/src/domain/shared/entities/datetimes/predicates/filters/inYearAndMonth/index.ts
  package.json
  yarn.lock
Labels: EDTR v2, category:assets, status:review, type:task 🧹

#2912 Pagination a11y.
  assets/src/application/ui/input/Button/style.scss
  assets/src/infrastructure/ui/display/pagination/Pagination.tsx
  assets/src/infrastructure/ui/display/pagination/style.scss
  assets/src/infrastructure/ui/inputs/style.scss
Labels: EDTR v2

#2939 Fix fields to sync from TPC to ticket edit form in multi-step
  assets/src/domain/eventEditor/ui/tickets/ticketForm/multiStep/useDataListener.ts
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/data/useInitialState.ts
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/utils/constants.ts
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/utils/shouldUpdateTicket.ts
Labels: EDTR v2, category:admin-page-ui-&-ux, type:bug 🐞

#2941 Fix quantity update of related tickets
  assets/src/domain/eventEditor/services/apollo/mutations/datetimes/useUpdateRelatedTickets.ts
  assets/src/domain/eventEditor/ui/datetimes/dateForm/multiStep/Content.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/data/useOnSubmitAssignments.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/utils.ts
Labels: EDTR v2, category:admin-page-ui-&-ux, status:review, type:bug 🐞

#2942 Fix modal closing on Month/Year Selector in Datepicker
  assets/src/domain/shared/ui/entityEditModal/EntityEditModal.tsx
Labels: EDTR v2, category:admin-page-ui-&-ux, status:review, type:bug 🐞

#2943 Mark required ticket fields with asterisk
  assets/src/domain/eventEditor/ui/tickets/ticketForm/useTicketFormConfig.tsx
Labels: EDTR v2, category:admin-page-ui-&-ux, type:bug 🐞

#2945 Added styles to FormErrorMessage.
  assets/src/application/ui/forms/espressoForm/renderers/ErrorMessage/index.tsx
  assets/src/application/ui/forms/espressoForm/renderers/ErrorMessage/style.scss
  assets/src/application/ui/forms/espressoForm/renderers/FieldRenderer.tsx
Labels: EDTR v2, category:admin-page-ui-&-ux

#2944 Add tests to TAM utility function
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/utils/index.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/utils/ticketsWithNewQuantity.test.ts
Labels: EDTR v2, category:unit-tests, type:task 🧹

#2950 Fix TPC tax deletion issue
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/buttons/DeleteAllPricesButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/buttons/DeletePriceModifierButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/hooks/index.ts
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/hooks/useRemoveAllTaxes.ts
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/hooks/useRemoveDefaultTax.ts
  core/domain/services/graphql/data/mutations/TicketMutation.php
  core/domain/services/graphql/mutators/TicketUpdate.php
Labels: EDTR v2, category:models-and-data-infrastructure, status:review, type:bug 🐞

#2951 TAM: Show all dates by default
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/filters/controls/DatesByMonthControl.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/filters/filterState/useFilterStateManager.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/utils/index.ts
Labels: EDTR v2, category:admin-page-ui-&-ux, status:review, type:task 🧹

#2949 Added RemoveTaxesButton.
  assets/src/application/services/utilities/money/useMoneyDisplay.ts
  assets/src/application/ui/input/Button/Link.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketForm/multiStep/ContentBody.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/buttons/DeleteAllPricesButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/buttons/taxes/AddDefaultTaxesButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/buttons/taxes/RemoveTaxesButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/buttons/taxes/TaxesButtons.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/components/DefaultPricesInfo.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/components/NoPricesBanner.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/components/TicketPriceCalculator.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/components/styles.scss
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/hooks/useAddDefaultTaxes.ts
Labels: EDTR v2, category:admin-page-ui-&-ux

#2953 TPC input height fix.
  assets/src/infrastructure/ui/inputs/style.scss
Labels: EDTR v2, category:admin-page-ui-&-ux

#2956 Return of the EDTR UI Tweaks
  assets/src/application/ui/calendars/dateDisplay/BiggieCalendarDate/style.scss
  assets/src/application/ui/display/TimezoneTimeInfo/Trigger.tsx
  assets/src/application/ui/display/TimezoneTimeInfo/style.scss
  assets/src/application/ui/display/icons/svgs/style.scss
  assets/src/application/ui/display/icons/svgs/types.ts
  assets/src/application/ui/display/icons/svgs/withEnhance.tsx
  assets/src/application/ui/display/withTooltip/style.scss
  assets/src/application/ui/input/Button/ButtonGroup/style.scss
  assets/src/application/ui/input/Button/ButtonRow/style.scss
  assets/src/application/ui/input/Button/IconButton/style.scss
  assets/src/application/ui/input/Button/style.scss
  assets/src/application/ui/input/InputWithLabel/style.scss
  assets/src/application/ui/input/Stepper/buttons/Next.tsx
  assets/src/application/ui/input/Stepper/buttons/Previous.tsx
  assets/src/application/ui/layout/entityList/filterBar/style.scss
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/components/table/styles.scss
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/components/TicketPriceCalculator.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/components/styles.scss
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/components/table/styles.scss
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/components/table/useFooterRowGenerator.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/components/table/useHeaderRowGenerator.ts
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/inputs/PriceAmountInput.tsx
  assets/src/infrastructure/ui/display/Tooltip/index.tsx
  assets/src/infrastructure/ui/inputs/style.scss
Labels: EDTR v2, category:admin-page-ui-&-ux, type:enhancement 🎉

#2959 Fix default dates constants
  assets/src/domain/shared/constants/defaultDates.ts
Labels: EDTR v2, category:admin-page-ui-&-ux, status:review, type:bug 🐞

#2958 Fix TAM entity details in multi step
  assets/src/application/services/hooks/index.ts
  assets/src/application/services/hooks/useMemoLazy.ts
  assets/src/domain/eventEditor/ui/datetimes/dateForm/multiStep/ContentWrapper.tsx
  assets/src/domain/eventEditor/ui/datetimes/dateForm/multiStep/types.ts
  assets/src/domain/eventEditor/ui/datetimes/dateForm/types.ts
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/components/table/DateCell.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/components/table/HeaderCell.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/data/useDatesAndTickets.ts
  assets/src/domain/eventEditor/ui/tickets/ticketForm/multiStep/ContentWrapper.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketForm/multiStep/types.ts
  assets/src/domain/eventEditor/ui/tickets/ticketForm/types.ts
  assets/src/domain/shared/ui/entityEditModal/index.ts
  assets/src/domain/shared/ui/entityEditModal/withEntityFormDetails.tsx
Labels: EDTR v2, category:admin-page-ui-&-ux, status:review, type:bug 🐞

#2960 Fix TPC decimal price inputs
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/fields/BaseField.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/fields/BaseNumberInputField.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/fields/useBaseField.tsx
Labels: EDTR v2, category:admin-page-ui-&-ux, type:bug 🐞

#2963 Fix quantity cap for new ticket
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/utils/index.ts
  assets/src/domain/eventEditor/ui/tickets/hooks/useCapQuantity.ts
  assets/src/domain/eventEditor/ui/tickets/ticketForm/multiStep/Content.tsx
Labels: EDTR v2, category:models-and-data-infrastructure, type:bug 🐞

#2979 Add Tooltip to TPC Reverse Calculate Button
  assets/src/application/ui/display/withTooltip/style.scss
  assets/src/application/ui/display/withTooltip/withTooltip.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/buttons/ReverseCalculateButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/components/table/useFooterRowGenerator.tsx
Labels: EDTR v2, category:admin-page-ui-&-ux, type:enhancement 🎉

#2983 EDTR Mobile Style Fixes
  assets/src/application/ui/display/ItemCount/style.scss
  assets/src/application/ui/display/TimezoneTimeInfo/style.scss
  assets/src/application/ui/display/entityDetailsPanel/style.scss
  assets/src/application/ui/forms/espressoForm/renderers/FieldRenderer.tsx
  assets/src/application/ui/forms/espressoForm/styles.scss
  assets/src/application/ui/input/Button/ButtonGroup/style.scss
  assets/src/application/ui/input/Button/ButtonRow/style.scss
  assets/src/application/ui/input/Button/IconButton/style.scss
  assets/src/application/ui/input/Button/style.scss
  assets/src/application/ui/layout/EntityCard/styles.scss
  assets/src/application/ui/layout/entityActionsMenu/style.scss
  assets/src/application/ui/layout/entityList/RegistrationsLink/style.scss
  assets/src/application/ui/layout/entityList/filterBar/style.scss
  assets/src/application/ui/layout/entityList/pagination/style.scss
  assets/src/application/ui/layout/entityList/style.scss
  assets/src/application/ui/layout/espressoTable/style.scss
  assets/src/application/ui/layout/espressoTable/tablet-style.scss
  assets/src/application/ui/styles/mixins/breakpoints.scss
  assets/src/domain/eventEditor/ui/styles.scss
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/components/table/styles.scss
  assets/src/domain/shared/ui/entityEditModal/styles.scss
  assets/src/infrastructure/ui/display/pagination/style.scss
  assets/src/infrastructure/ui/inputs/dateTime/Datepicker/style.scss
  assets/src/infrastructure/ui/layout/modal/styles.scss
Labels: EDTR v2, category:admin-page-ui-&-ux, type:bug 🐞

#2987 Added TabbableText; js_only.
  assets/src/application/ui/input/InlineEditInput/InlineEditText.tsx
  assets/src/application/ui/input/InlineEditInput/InlineEditTextArea.tsx
  assets/src/application/ui/input/InlineEditInput/TabbableText.tsx
  assets/src/application/ui/input/InlineEditInput/style.scss
  assets/src/application/ui/input/InlineEditInput/types.ts
Labels: EDTR v2, category:admin-page-ui-&-ux

#2997 TimezoneTimeInfo on close blur.
  assets/src/application/ui/display/Popover/index.tsx
  assets/src/application/ui/display/Popover/style.scss
  assets/src/application/ui/display/TimezoneTimeInfo/index.tsx
  assets/src/infrastructure/ui/display/Popover.tsx
  package.json
  yarn.lock
Labels: EDTR v2, category:admin-page-ui-&-ux

#3002 Inline Edit Infinity Active/Hover States Fix.
  assets/src/application/ui/display/icons/svgs/index.ts
  assets/src/application/ui/display/icons/svgs/infinity.svg
  assets/src/application/ui/display/icons/svgs/infoCircleOutlined.svg
  assets/src/application/ui/input/InlineEditInput/InlineEditInfinity.tsx
  assets/src/application/ui/input/InlineEditInput/TabbableText.tsx
  assets/src/application/ui/input/InlineEditInput/style.scss
  assets/src/application/ui/input/InlineEditInput/types.ts
Labels: EDTR v2, category:admin-page-ui-&-ux

#2988 Added clickable tooltips.
  assets/src/application/ui/display/Tooltip/ClickableIconWithTooltip.tsx
  assets/src/application/ui/display/Tooltip/index.ts
  assets/src/application/ui/display/Tooltip/style.scss
  assets/src/application/ui/display/Tooltip/types.ts
  assets/src/application/ui/display/confirm/useConfirmationDialog.tsx
  assets/src/application/ui/display/icons/HelpIcon/index.tsx
  assets/src/application/ui/display/icons/HelpIcon/style.scss
  assets/src/application/ui/display/icons/index.ts
  assets/src/application/ui/display/icons/types.ts
  assets/src/application/ui/display/index.ts
  assets/src/application/ui/display/withTooltip/style.scss
  assets/src/application/ui/forms/espressoForm/renderers/FieldRenderer.tsx
  assets/src/application/ui/forms/espressoForm/styles.scss
  assets/src/application/ui/input/InlineEditInput/InlineEditText.tsx
  assets/src/application/ui/input/InlineEditInput/InlineEditTextArea.tsx
  assets/src/application/ui/input/InlineEditInput/TabbableText.tsx
  assets/src/application/ui/input/InlineEditInput/types.ts
  assets/src/domain/eventEditor/ui/datetimes/datesList/AddNewDateButton.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/actionsMenu/dropdown/DateMainMenu.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/editable/EditableDesc.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/editable/EditableName.tsx
  assets/src/domain/eventEditor/ui/ticketAssignmentsManager/useTicketAssignmentsManager.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/hooks/useTicketPriceCalculator.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/AddNewTicketButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/actionsMenu/dropdown/TicketMainMenu.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/editable/EditableDesc.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/editable/EditableName.tsx
  assets/src/domain/wpPluginsPage/exitSurvey/ExitSurvey.tsx
  assets/src/domain/wpPluginsPage/exitSurvey/Popup.tsx
  assets/src/infrastructure/ui/display/Tooltip/index.tsx
  assets/src/infrastructure/ui/inputs/inlineEdit/types.ts
  package.json
  yarn.lock
Labels: EDTR v2, category:admin-page-ui-&-ux

#3004 Table view fix.
  assets/src/application/ui/display/icons/HelpIcon/index.tsx
  assets/src/application/ui/input/InlineEditInput/style.scss
  assets/src/application/ui/layout/entityActionsMenu/style.scss
  assets/src/application/ui/layout/entityActionsMenu/styles.css
  assets/src/application/ui/layout/espressoTable/ResponsiveTable.tsx
  assets/src/application/ui/layout/espressoTable/style/data-cell.scss
  assets/src/application/ui/layout/espressoTable/style/index.scss
  assets/src/application/ui/layout/espressoTable/style/row.scss
  assets/src/application/ui/layout/espressoTable/style/tablet-style.scss
Labels: EDTR v2, category:admin-page-ui-&-ux

#3005 Infinity icon removal.
  assets/src/application/ui/display/entityDetailsPanel/style.scss
  assets/src/application/ui/display/icons/svgs/index.ts
  assets/src/application/ui/display/icons/svgs/infinity.svg
  assets/src/application/ui/input/InlineEditInput/InlineEditInfinity.tsx
  assets/src/application/ui/input/InlineEditInput/TabbableText/index.tsx
  assets/src/application/ui/input/InlineEditInput/TabbableText/style.scss
  assets/src/application/ui/input/InlineEditInput/index.tsx
  assets/src/application/ui/input/InlineEditInput/style.scss
  assets/src/application/ui/layout/EntityCard/styles.scss
  assets/src/application/ui/layout/espressoTable/style/data-cell.scss
  assets/src/application/ui/layout/espressoTable/style/index.scss
Labels: EDTR v2, category:admin-page-ui-&-ux

#3007 Allow empty title and description for dates and tickets
  core/domain/services/graphql/data/mutations/DatetimeMutation.php
  core/domain/services/graphql/data/mutations/TicketMutation.php
Labels: EDTR v2, category:models-and-data-infrastructure, status:review, type:bug 🐞

#3008 Related entities tooltip update.
  assets/src/domain/eventEditor/ui/datetimes/datesList/actionsMenu/AssignTicketsButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/actionsMenu/AssignDatesButton.tsx
Labels: EDTR v2

#3010 Fix boolean flags for EE_Ticket
  core/db_classes/EE_Ticket.class.php
Labels: EDTR v2, category:models-and-data-infrastructure, type:bug 🐞

#3011 Fix Inline Edit Tooltips
  assets/src/application/ui/calendars/dateDisplay/BiggieCalendarDate/style.scss
  assets/src/application/ui/display/TimezoneTimeInfo/style.scss
  assets/src/application/ui/input/CurrencyInput/index.tsx
  assets/src/application/ui/input/InlineEditInput/InlineEditInfinity.tsx
  assets/src/application/ui/input/InlineEditInput/InlineEditText.tsx
  assets/src/application/ui/input/InlineEditInput/InlineEditTextArea.tsx
  assets/src/application/ui/input/InlineEditInput/TabbableText/index.tsx
  assets/src/application/ui/input/InlineEditInput/TabbableText/style.scss
  assets/src/application/ui/layout/EntityCard/styles.scss
  assets/src/application/ui/layout/dropdownMenu/styles.scss
  assets/src/application/ui/layout/entityList/style.scss
  assets/src/domain/eventEditor/ui/datetimes/datesList/cardView/DateCapacity.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/cardView/TicketQuantity.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/editable/EditablePrice.tsx
Labels: EDTR v2, category:admin-page-ui-&-ux, type:bug 🐞

#3012 TPC default tax subscription
  assets/src/domain/eventEditor/hooks/edtrState/reducer.ts
  assets/src/domain/eventEditor/hooks/edtrState/types.ts
  assets/src/domain/eventEditor/hooks/edtrState/useEdtrStateManager.ts
  assets/src/domain/eventEditor/services/apollo/queries/prices/useFetchPrices.ts
  assets/src/domain/eventEditor/services/apollo/queries/prices/usePriceQueryOptions.ts
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/buttons/taxes/TaxesButtons.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/components/DefaultPricesInfo.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/components/DefaultTaxesInfo.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/components/TicketPriceCalculator.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/components/styles.scss
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/hooks/useAddDefaultTaxes.ts
  core/domain/services/admin/events/editor/EventEditorGraphQLData.php
  core/domain/services/graphql/connection_resolvers/AbstractConnectionResolver.php
  core/domain/services/graphql/connection_resolvers/PriceConnectionResolver.php
  core/domain/services/graphql/connections/TicketPricesConnection.php
Labels: EDTR v2, category:admin-page-ui-&-ux, status:review, type:enhancement 🎉
