Repository eventespresso/event-espresso-core, pull requests merged in 2020-09, with the labels that each got.

#3116 Fix SPCO Copy Attendee Data Closes #3102
  core/domain/entities/routing/handlers/shared/AssetRequests.php
  core/domain/services/assets/CoreAssetManager.php
Labels: category:spco-&-registration, status:review, type:bug 🐞

#3097 Only load .php files when dynamically loading classes
  core/helpers/EEH_File.helper.php
Labels: status:needs-testing

#3119 Prep Barista and Asset Management for REM
  core/EE_Dependency_Map.core.php
  core/EE_System.core.php
  core/domain/DomainBase.php
  core/domain/DomainFactory.php
  core/domain/entities/routing/handlers/shared/AssetRequests.php
  core/domain/entities/routing/handlers/shared/GQLRequests.php
  core/domain/entities/routing/handlers/shared/RegularRequests.php
  core/services/assets/AssetManifest.php
  core/services/assets/AssetManifestException.php
  core/services/assets/AssetManifestFactory.php
  core/services/assets/AssetManifestInterface.php
  core/services/assets/Barista.php
  core/services/assets/BaristaFactory.php
  core/services/assets/BaristaInterface.php
  core/services/assets/Registry.php
  core/services/factory/Factory.php
  core/services/factory/FactoryInterface.php
  core/services/factory/StaticFactoryInterface.php
  core/services/loaders/CachingLoaderDecoratorInterface.php
  core/services/loaders/Loader.php
  core/services/loaders/LoaderInterface.php
  core/services/loaders/ObjectIdentifier.php
  tests/mocks/core/domain/DomainFactoryMock.php
  tests/mocks/core/domain/entities/routing/handlers/shared/GQLRequestsMock.php
  tests/testcases/core/domain/DomainFactoryTest.php
  tests/testcases/core/services/loaders/ObjectIdentifierTest.php
Labels: category:core-plugin, status:review, type:enhancement 🎉

#3124 Add a check for missing message queue crons when running the message queue cleanup.
  core/libraries/messages/EE_Messages_Scheduler.lib.php
Labels: status:needs-testing

#3125 Allow multiple categories to be used in ESPRESSO_EVENTS
  core/helpers/EEH_Event_Query.helper.php
Labels: category:templates-shortcodes-and-widgets, status:needs-testing

#3121 Fix typo in GlotPress translation filename.
  core/EE_Load_Textdomain.core.php
Labels: category:i18n, status:needs-testing

#3126 Fix sanitization for rich text fields
  core/domain/services/graphql/data/mutations/DatetimeMutation.php
  core/domain/services/graphql/data/mutations/EventMutation.php
  core/domain/services/graphql/data/mutations/PriceMutation.php
  core/domain/services/graphql/data/mutations/TicketMutation.php
  core/domain/services/graphql/data/mutations/VenueMutation.php
Labels: EDTR v2, category:models-and-data-infrastructure, category:security, status:review

#3128 Simplify JS i18n Process
  core/EE_Dependency_Map.core.php
  core/domain/Domain.php
  core/domain/DomainBase.php
  core/domain/DomainInterface.php
  core/domain/entities/editor/CoreBlocksAssetManager.php
  core/domain/entities/routing/data_nodes/EventEspressoData.php
  core/domain/entities/routing/handlers/admin/EspressoEventEditor.php
  core/domain/entities/routing/handlers/admin/GutenbergEditor.php
  core/domain/entities/routing/handlers/admin/WordPressPluginsPage.php
  core/domain/services/assets/CoreAssetManager.php
  core/domain/services/assets/EventEditorAssetManager.php
  core/domain/services/assets/WordPressPluginsPageAssetManager.php
  core/domain/values/assets/JavascriptAsset.php
  core/services/assets/BlockAssetManager.php
  core/services/assets/I18nRegistry.php
  core/services/assets/JedLocaleData.php
  core/services/assets/Registry.php
  core/services/json/JsonDataNodeHandler.php
  core/services/json/PrimaryJsonDataNode.php
  core/services/routing/RouteHandler.php
  docs/AA--Javascript-in-EE/javascript-i18n.md
  tests/mocks/core/services/assets/I18nRegistryMock.php
  tests/testcases/core/domain/values/assets/JavascriptAssetTest.php
  tests/testcases/core/services/assets/I18nRegistryTest.php
  tests/testcases/core/services/assets/RegistryTest.php
Labels: category:assets, status:review, type:enhancement 🎉

#3130 Prep Frontend for REM
  core/services/json/JsonConfig.php
  public/template_tags.php
Labels: category:frontend-ui-&-ux, status:review, type:enhancement 🎉

#3133 Add NK deployment workflow
  .github/workflows/deploy-to-nk.yml
Labels: type:build-process 🔨, type:task 🧹

#3138 Don't Load Bundled WPGraphQL if PHP < 7 closes #3135
  core/domain/entities/routing/data_nodes/core/CurrentUser.php
Labels: category:third-party-libs, priority:high, status:review, type:bug 🐞

#3139 DMS & WP GQL Tweaks Before REM
  core/EE_Data_Migration_Manager.core.php
  core/domain/services/graphql/Utilities.php
  core/domain/services/graphql/connection_resolvers/AbstractConnectionResolver.php
  core/domain/services/graphql/data/loaders/AbstractLoader.php
  core/domain/services/graphql/data/loaders/AttendeeLoader.php
  core/domain/services/graphql/data/loaders/DatetimeLoader.php
  core/domain/services/graphql/data/loaders/PriceLoader.php
  core/domain/services/graphql/data/loaders/PriceTypeLoader.php
  core/domain/services/graphql/data/loaders/TicketLoader.php
  core/domain/services/graphql/data/loaders/VenueLoader.php
  core/libraries/plugin_api/EE_Register_Data_Migration_Scripts.lib.php
Labels: category:core-plugin, status:review, type:enhancement 🎉
