Repository eventespresso/event-espresso-core, pull requests merged in 2020-11, with the labels that each got.

#3196 Migrate CI to Github actions for master branch
  .github/workflows/ci-master.yml
  .travis.yml
  assets/src/wp-plugins-page/index.js
Labels: type:build-process 🔨

#3197 Migrate CI to Github actions for barista branch
  .github/workflows/ci-barista.yml
  .travis.yml
Labels: type: tooling :hammer:

#3140 When an event is expired, show both the expired event message an the view details button ...
  modules/ticket_selector/DisplayTicketSelector.php
Labels: status:needs-testing

#3136 Add hook to interrupt spco reg step(s)
  modules/single_page_checkout/EED_Single_Page_Checkout.module.php
Labels: status:merge

#3132 Don't update the Transaction/Registrations within the cron check when the primary registrant is Not Approved
  core/EE_Cron_Tasks.core.php
Labels: status:needs-testing

#2754 Display error on iframe output
  modules/ticket_selector/DisplayTicketSelector.php
Labels: category:frontend-ui-&-ux, status:needs-testing

#3129 Add an action for the check in status is toggle to either checked_in or checked_out
  core/db_classes/EE_Registration.class.php
Labels: status:needs-testing

#3207 Add support for Plain URLs
  core/domain/entities/routing/data_nodes/core/Api.php
  core/domain/services/contexts/RequestTypeContextDetector.php
  core/services/database/WordPressOption.php
  core/services/graphql/GraphQLEndpoint.php
  core/services/json/JsonDataHandler.php
  core/services/json/JsonDataWordpressOption.php
  core/services/request/middleware/SetRequestTypeContextChecker.php
Labels: EDTR v2, category:third-party-libs, type:bug 🐞

#3208 Better Event Manager Detection
  core/domain/services/admin/events/editor/EventManagers.php
  core/domain/services/contexts/RequestTypeContextDetector.php
Labels: category:models-and-data-infrastructure, status:review, type:enhancement 🎉
