Repository eventespresso/event-espresso-core, pull requests merged in 2020-02, with the labels that each got.

#2322 Travis failing build fix.
  .travis.yml
  package-lock.json
  yarn.lock
Labels: status:review, type: tooling :hammer:

#2318 Load all entities on rehydration | Closes #2317
  core/domain/services/admin/events/editor/AdvancedEditorData.php
  core/domain/services/graphql/connection_resolvers/AbstractConnectionResolver.php
Labels: EDTR Prototype, status:review, type:bug 🐞

#2308 Add common isTrashed predicate | Closes #2307
  assets/prototype/domain/eventEditor/data/ticket/types.ts
  assets/prototype/domain/eventEditor/data/types.ts
  assets/prototype/domain/eventEditor/tickets/ticketPriceCalculator/hooks/useOnSubmitPrices.ts
  assets/prototype/domain/eventEditor/tickets/ticketsList/filterBar/controls/ShowTicketsControl.tsx
  assets/prototype/domain/shared/entities/datetimes/predicates/filters/activeUpcoming/index.test.ts
  assets/prototype/domain/shared/entities/datetimes/predicates/filters/belowCapacity/filter.ts
  assets/prototype/domain/shared/entities/datetimes/predicates/filters/belowCapacity/index.test.ts
  assets/prototype/domain/shared/entities/datetimes/predicates/filters/expiredOnly/index.ts
  assets/prototype/domain/shared/entities/datetimes/predicates/filters/soldOutOnly/index.ts
  assets/prototype/domain/shared/entities/datetimes/predicates/filters/trashedOnly/index.ts
  assets/prototype/domain/shared/entities/datetimes/predicates/isTrashed/index.test.ts
  assets/prototype/domain/shared/entities/datetimes/predicates/isTrashed/index.ts
  assets/prototype/domain/shared/entities/tickets/predicates/filters/archivedOnly/index.test.ts
  assets/prototype/domain/shared/entities/tickets/predicates/filters/archivedOnly/index.ts
  assets/prototype/domain/shared/entities/tickets/predicates/filters/expiredOnly/index.test.ts
  assets/prototype/domain/shared/entities/tickets/predicates/filters/index.ts
  assets/prototype/domain/shared/entities/tickets/predicates/filters/trashedOnly/index.test.ts
  assets/prototype/domain/shared/entities/tickets/predicates/filters/trashedOnly/index.ts
  assets/prototype/domain/shared/entities/tickets/predicates/isArchived.ts
  assets/prototype/domain/shared/entities/tickets/predicates/isExpired.ts
  assets/prototype/domain/shared/entities/tickets/predicates/isTrashed.ts
  assets/prototype/domain/shared/entities/tickets/predicates/isValidEntityOrArchive.ts
  assets/prototype/domain/shared/entities/tickets/predicates/isValidOrTrashed.ts
  assets/prototype/domain/shared/predicates/shared/isTrashed/index.test.ts
  assets/prototype/domain/shared/predicates/shared/isTrashed/index.ts
Labels: EDTR Prototype, status:review, type:code-quality 👾

#2327 Fix priceType not loading | Closes #2325
  core/domain/services/admin/events/editor/AdvancedEditorData.php
Labels: EDTR Prototype, status:review, type:bug 🐞

#2326 Optimistic responses for tickets | Closes #2321
  assets/prototype/application/ui/components/input/inlineEditInput/InlineEditInput.tsx
  assets/prototype/domain/eventEditor/data/mutations/datetimes/useDatetimeMutator.ts
  assets/prototype/domain/eventEditor/data/mutations/tickets/test/updateTicket.test.ts
  assets/prototype/domain/eventEditor/data/mutations/tickets/useMutationVariables.ts
  assets/prototype/domain/eventEditor/data/mutations/tickets/useOptimisticResponse.ts
  assets/prototype/domain/eventEditor/data/mutations/tickets/useTicketMutator.ts
  assets/prototype/domain/eventEditor/data/queries/priceTypes/useDefaultPriceType.ts
  assets/prototype/domain/eventEditor/data/queries/prices/test/data.ts
  assets/prototype/domain/eventEditor/data/queries/prices/test/useFetchPrices.test.ts
  assets/prototype/domain/eventEditor/data/queries/prices/useFetchPrices.ts
  assets/prototype/domain/eventEditor/data/queries/tickets/useFetchTickets.ts
  assets/prototype/domain/eventEditor/tickets/ticketCard/TicketCard.tsx
  assets/prototype/domain/shared/entities/priceTypes/predicates/selectionPredicates/index.ts
Labels: EDTR Prototype, status:review, type:task 🧹

#2329 Use sortTicketsBy | Closes #2300
  assets/prototype/domain/eventEditor/data/ticket/types.ts
  assets/prototype/domain/eventEditor/tickets/ticketsList/filterBar/TicketsListEntityFilters.tsx
  assets/prototype/domain/eventEditor/tickets/ticketsList/filterBar/controls/TicketsSortedByControl.tsx
  assets/prototype/domain/eventEditor/tickets/ticketsList/filterBar/useTicketListFilterState/index.test.ts
  assets/prototype/domain/eventEditor/tickets/ticketsList/filterBar/useTicketListFilterState/index.ts
  assets/prototype/domain/shared/entities/tickets/predicates/sorters/index.test.ts
  assets/prototype/domain/shared/entities/tickets/predicates/sorters/index.ts
Labels: EDTR Prototype, status:review, type:task 🧹

#2210 Reconfigure Webpack; closes #2143.
  .eslintrc.json
  .travis.yml
  assets/ZZZ/components/event-attendees/index.js
  assets/ZZZ/components/ui/entity-list-filter-bar/collapsible.js
  assets/ZZZ/components/ui/loading-notice/style.css
  assets/ZZZ/hooks/index.js
  assets/ZZZ/hooks/useRect.js
  assets/prototype/application/services/apollo/mutations/useEntityMutation.ts
  assets/prototype/application/services/toaster/useErrorToast.tsx
  assets/prototype/application/ui/components/display/entityList/filterBar/Collapsible.js
  assets/prototype/application/ui/components/display/espressoIcon/EspressoIcon.tsx
  assets/prototype/application/ui/components/display/espressoIcon/index.ts
  assets/prototype/application/ui/components/index.ts
  assets/prototype/application/ui/components/input/currencyInput/CurrencyInput.tsx
  assets/prototype/application/ui/components/layout/editorModal/types.ts
  assets/prototype/application/ui/components/layout/index.ts
  assets/prototype/application/utilities/text/entityFieldSearch/index.ts
  assets/prototype/domain/eventEditor/context/TestContext/TestContextProviders.tsx
  assets/prototype/domain/eventEditor/context/TestContext/useSetGlobalStatusFlags.ts
  assets/prototype/domain/eventEditor/context/TestContext/useSetRelationalData.ts
  assets/prototype/domain/eventEditor/data/mutations/datetimes/updateTicketCache.ts
  assets/prototype/domain/eventEditor/data/mutations/datetimes/useDatetimeMutator.ts
  assets/prototype/domain/eventEditor/data/mutations/datetimes/useOnUpdateDatetime.ts
  assets/prototype/domain/eventEditor/data/mutations/tickets/useOnUpdateTicket.ts
  assets/prototype/domain/eventEditor/tickets/ticketPriceCalculator/TicketPriceModifierRow.tsx
  assets/prototype/domain/eventEditor/tickets/ticketPriceCalculator/buttons/AddPriceModifierButtonData.tsx
  assets/prototype/domain/eventEditor/tickets/ticketPriceCalculator/formDecorators/usePriceTypeDecorator.ts
  assets/prototype/domain/eventEditor/tickets/ticketPriceCalculator/formDecorators/utilities.ts
  assets/prototype/domain/eventEditor/tickets/ticketPriceCalculator/hooks/useTicketPriceCalculatorModal.tsx
  assets/prototype/domain/shared/entities/datetimes/predicates/filters/belowCapacity/filter.ts
  assets/prototype/domain/shared/entities/datetimes/predicates/filters/belowCapacity/validInfiniteCapacityLimit.ts
  assets/prototype/domain/shared/entities/datetimes/predicates/filters/soldOutOnly/index.ts
  assets/prototype/domain/shared/entities/datetimes/predicates/validSold/index.ts
  assets/prototype/domain/shared/types.d.ts
  config/env.js
  config/jest/cssTransform.js
  config/jest/fileTransform.js
  config/jest/setupTests.ts
  config/modules.js
  config/paths.js
  config/pnpTs.js
  config/tests/unit/jest.config.js
  config/webpack.common.js
  config/webpack.config.js
  config/webpack.dev.js
  config/webpack.prod.js
  config/webpackDevServer.config.js
  core/domain/services/assets/EspressoEditorAssetManager.php
  core/services/assets/I18nRegistry.php
  jest.config.js
  js-green-licenses.json
  package.json
  public/index.html
  scripts/build.js
  scripts/start.js
  scripts/test.js
  scripts/watch.js
  tests/javascript-config/unit/jest.config.json
  tsconfig.json
  yarn.lock
Labels: EDTR Prototype, status:review

#2258 Fix Types for Calculator PriceType Input
  assets/prototype/domain/eventEditor/data/queries/prices/index.ts
  assets/prototype/domain/eventEditor/data/queries/prices/test/data.ts
  assets/prototype/domain/eventEditor/data/types.ts
  assets/prototype/domain/eventEditor/tickets/ticketPriceCalculator/TicketPriceModifierRow.tsx
  assets/prototype/domain/eventEditor/tickets/ticketPriceCalculator/buttons/AddPriceModifierButtonData.tsx
  assets/prototype/domain/eventEditor/tickets/ticketPriceCalculator/buttons/PriceModifierActions.tsx
  assets/prototype/domain/eventEditor/tickets/ticketPriceCalculator/defaultPriceModifier.ts
  assets/prototype/domain/eventEditor/tickets/ticketPriceCalculator/formDecorators/usePriceTypeDecorator.ts
  assets/prototype/domain/eventEditor/tickets/ticketPriceCalculator/formDecorators/utilities.ts
  assets/prototype/domain/eventEditor/tickets/ticketPriceCalculator/hooks/calculateBasePrice.ts
  assets/prototype/domain/eventEditor/tickets/ticketPriceCalculator/hooks/calculateTicketTotal.ts
  assets/prototype/domain/eventEditor/tickets/ticketPriceCalculator/hooks/useTicketPriceCalculatorModal.tsx
  assets/prototype/domain/eventEditor/tickets/ticketPriceCalculator/inputs/PriceTypeInput.tsx
  assets/prototype/domain/eventEditor/tickets/ticketPriceCalculator/types.ts
  assets/prototype/domain/eventEditor/tickets/ticketPriceCalculator/usePriceModifier.ts
  assets/prototype/domain/shared/entities/priceTypes/predicates/selectionPredicates/index.ts
  assets/prototype/domain/shared/entities/prices/predicates/priceFields.ts
  assets/prototype/domain/shared/entities/prices/predicates/selectionPredicates/index.ts
  assets/prototype/domain/shared/entities/prices/predicates/updatePredicates.ts
  assets/prototype/domain/shared/entities/tickets/predicates/updatePredicates.ts
  assets/prototype/domain/shared/predicates/shared/selectionPredicates/index.ts
  core/domain/services/graphql/data/mutations/DatetimeMutation.php
  core/domain/services/graphql/data/mutations/EventMutation.php
  core/domain/services/graphql/data/mutations/PriceMutation.php
  core/domain/services/graphql/data/mutations/TicketMutation.php
  core/domain/services/graphql/types/Price.php
  package-lock.json
Labels: EDTR Prototype, status:review, type:bug 🐞, type:enhancement 🎉

#2345 Typefy and test application date utils | Closes #2132
  assets/src/application/services/utilities/date/addSub.ts
  assets/src/application/services/utilities/date/diff.ts
  assets/src/application/services/utilities/date/sort.ts
  assets/src/application/services/utilities/date/test/addSub/add.ISOWeekYears.test.ts
  assets/src/application/services/utilities/date/test/addSub/add.days.test.ts
  assets/src/application/services/utilities/date/test/addSub/add.hours.test.ts
  assets/src/application/services/utilities/date/test/addSub/add.milliseconds.test.ts
  assets/src/application/services/utilities/date/test/addSub/add.minutes.test.ts
  assets/src/application/services/utilities/date/test/addSub/add.months.test.ts
  assets/src/application/services/utilities/date/test/addSub/add.quarters.test.ts
  assets/src/application/services/utilities/date/test/addSub/add.seconds.test.ts
  assets/src/application/services/utilities/date/test/addSub/add.weeks.test.ts
  assets/src/application/services/utilities/date/test/addSub/add.years.test.ts
  assets/src/application/services/utilities/date/test/addSub/sub.ISOWeekYears.test.ts
  assets/src/application/services/utilities/date/test/addSub/sub.days.test.ts
  assets/src/application/services/utilities/date/test/addSub/sub.hours.test.ts
  assets/src/application/services/utilities/date/test/addSub/sub.milliseconds.test.ts
  assets/src/application/services/utilities/date/test/addSub/sub.minutes.test.ts
  assets/src/application/services/utilities/date/test/addSub/sub.months.test.ts
  assets/src/application/services/utilities/date/test/addSub/sub.quarters.test.ts
  assets/src/application/services/utilities/date/test/addSub/sub.seconds.test.ts
  assets/src/application/services/utilities/date/test/addSub/sub.weeks.test.ts
  assets/src/application/services/utilities/date/test/addSub/sub.years.test.ts
  assets/src/application/services/utilities/date/test/areEqual.test.ts
  assets/src/application/services/utilities/date/test/diff/diff.ISOWeekYears.test.ts
  assets/src/application/services/utilities/date/test/diff/diff.businessDays.test.ts
  assets/src/application/services/utilities/date/test/diff/diff.calendarDays.test.ts
  assets/src/application/services/utilities/date/test/diff/diff.calendarISOWeekYears.test.ts
  assets/src/application/services/utilities/date/test/diff/diff.calendarISOWeeks.test.ts
  assets/src/application/services/utilities/date/test/diff/diff.calendarMonths.test.ts
  assets/src/application/services/utilities/date/test/diff/diff.calendarQuarters.test.ts
  assets/src/application/services/utilities/date/test/diff/diff.calendarWeeks.test.ts
  assets/src/application/services/utilities/date/test/diff/diff.calendarYears.test.ts
  assets/src/application/services/utilities/date/test/diff/diff.days.test.ts
  assets/src/application/services/utilities/date/test/diff/diff.hours.test.ts
  assets/src/application/services/utilities/date/test/diff/diff.milliseconds.test.ts
  assets/src/application/services/utilities/date/test/diff/diff.minutes.test.ts
  assets/src/application/services/utilities/date/test/diff/diff.months.test.ts
  assets/src/application/services/utilities/date/test/diff/diff.quarters.test.ts
  assets/src/application/services/utilities/date/test/diff/diff.seconds.test.ts
  assets/src/application/services/utilities/date/test/diff/diff.weeks.test.ts
  assets/src/application/services/utilities/date/test/diff/diff.years.test.ts
  assets/src/application/services/utilities/date/test/localToUtc.test.ts
  assets/src/application/services/utilities/date/test/sort.test.ts
  assets/src/application/services/utilities/date/test/utcToLocal.test.ts
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/useDatesListFilterState/index.test.ts
  assets/src/domain/shared/entities/datetimes/predicates/filters/recentlyExpiredOnly/index.test.ts
  assets/src/domain/shared/entities/datetimes/predicates/isRecentlyExpired/index.test.ts
  assets/src/domain/shared/entities/datetimes/predicates/isRecentlyExpired/index.ts
  assets/src/domain/shared/entities/tickets/predicates/filters/expiredOnly/index.test.ts
  assets/src/domain/shared/entities/tickets/predicates/isExpired.ts
  assets/src/domain/shared/entities/tickets/predicates/isOnSale.ts
  assets/src/domain/shared/entities/tickets/predicates/isPending.ts
Labels: EDTR v2, category:unit-tests, status:review, type:enhancement 🎉

#2343 Install antd; closes #2342.
  assets/src/application/ui/display/EmptyState.tsx
  assets/src/application/ui/input/CurrencyInput/index.tsx
  assets/src/application/ui/input/EspressoButton/index.tsx
  assets/src/application/ui/input/EspressoButton/types.ts
  assets/src/application/ui/input/InlineEditInput/index.tsx
  assets/src/domain/eventEditor/ui/datetimes/dateCard/DateCard.tsx
  assets/src/domain/eventEditor/ui/datetimes/dateCard/DeleteDateButton.tsx
  assets/src/domain/eventEditor/ui/datetimes/dateCard/EditDateButton.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/List.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketCard/DeleteTicketButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketCard/EditTicketButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/TicketPriceTotalRow.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/buttons/AddPriceModifierButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/buttons/DeletePriceModifierButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/buttons/TicketPriceCalculatorButton.tsx
  assets/src/domain/shared/ui/RelationsSelector/index.tsx
  babel.config.js
  config/resolve-tsconfig-path-to-webpack-alias.js
  config/webpack.config.js
  js-green-licenses.json
  package.json
  tsconfig.json
  yarn.lock
Labels: EDTR v2, category:assets, type:task 🧹

#2361 Add Entity Paper Frame closes #2357
  assets/src/application/services/utilities/text/shortenGuid/index.ts
  assets/src/application/ui/display/EntityIDs/index.tsx
  assets/src/application/ui/display/EntityIDs/style.css
  assets/src/application/ui/display/index.ts
  assets/src/application/ui/layout/EntityPaperFrame/index.tsx
  assets/src/application/ui/layout/EntityPaperFrame/style.css
  assets/src/application/ui/layout/entityList/filterBar/index.ts
  assets/src/application/ui/layout/entityList/index.ts
  assets/src/application/ui/layout/index.ts
  assets/src/domain/eventEditor/ui/datetimes/dateCard/DateCard.tsx
  assets/src/domain/eventEditor/ui/datetimes/dateCard/styles.ts
  assets/src/domain/eventEditor/ui/tickets/ticketCard/TicketCard.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketCard/styles.ts
  package.json
  tsconfig.json
Labels: EDTR v2, category:assets, type:task 🧹

#2364 Minor PHP 7.4 fixes
  core/EE_Error.core.php
  core/admin/EE_Admin_Page_CPT.core.php
Labels: category:technical-debt, type:code-quality 👾

#2372 Migrate Entity Pagination; closes #2356.
  assets/ZZZ/components/ui/entity-pagination/entity-pagination.js
  assets/ZZZ/components/ui/entity-pagination/index.js
  assets/ZZZ/components/ui/entity-pagination/style.css
  assets/ZZZ/components/ui/entity-pagination/use-pagination-config.js
  assets/src/application/ui/layout/entityList/pagination/EntityPagination.tsx
  assets/src/application/ui/layout/entityList/pagination/index.js
  assets/src/application/ui/layout/entityList/pagination/style.scss
  assets/src/application/ui/layout/entityList/pagination/useEntityPagination.js
  package.json
  yarn.lock
Labels: EDTR v2, category:assets, type:task 🧹

#2379 Add tests to price predicates | Closes #2299
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/formDecorators/utilities.test.ts
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/formDecorators/utilities.ts
Labels: EDTR v2, category:unit-tests, status:review

#2374 Move Biggie Calendar Date
  assets/ZZZ/components/ui/dates-and-times/biggie-calendar-date/index.js
  assets/ZZZ/components/ui/dates-and-times/biggie-calendar-date/style.css
  assets/src/application/ui/calendars/dateDisplay/BiggieCalendarDate/index.tsx
  assets/src/application/ui/calendars/dateDisplay/BiggieCalendarDate/style.css
  assets/src/application/ui/calendars/dateDisplay/index.ts
  assets/src/application/ui/calendars/dateDisplay/types.ts
  assets/src/application/ui/calendars/index.ts
  assets/src/application/ui/display/EntityIDs/style.css
  assets/src/application/ui/forms/formModal/FormModal.tsx
  assets/src/application/ui/forms/formModal/FormModalForm.tsx
  assets/src/application/ui/input/EspressoButton/index.tsx
  assets/src/application/ui/input/EspressoButton/types.ts
  assets/src/application/ui/layout/EntityPaperFrame/index.tsx
  assets/src/application/ui/layout/EntityPaperFrame/style.css
  assets/src/domain/eventEditor/ui/datetimes/dateCard/DateCard.tsx
  assets/src/domain/eventEditor/ui/datetimes/dateCard/DeleteDateButton.tsx
  assets/src/domain/eventEditor/ui/datetimes/dateCard/EditDateButton.tsx
  assets/src/domain/shared/entities/datetimes/helpers/statusBgColorClass.ts
  assets/src/domain/shared/ui/dateRangeInput/dateDisplay.tsx
Labels: EDTR v2, category:assets

#2366 Moved EntityList and converted to TS; closes 2355.
  assets/ZZZ/components/ui/entity-list/entity-list.js
  assets/ZZZ/components/ui/entity-list/index.js
  assets/ZZZ/components/ui/entity-list/style.css
  assets/ZZZ/components/ui/entity-list/use-reorder-entities.js
  assets/src/application/services/apollo/mutations/types.ts
  assets/src/application/services/apollo/relations/types.ts
  assets/src/application/services/utilities/text/entityFieldSearch/index.ts
  assets/src/application/ui/display/EmptyState.tsx
  assets/src/application/ui/display/index.ts
  assets/src/application/ui/layout/editorModal/types.ts
  assets/src/application/ui/layout/entityList/EntityList/index.tsx
  assets/src/application/ui/layout/entityList/EntityList/style.scss
  assets/src/application/ui/layout/entityList/index.ts
  assets/src/domain/eventEditor/ui/datetimes/datesList/index.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/index.tsx
  js-green-licenses.json
  package.json
  tsconfig.json
  yarn.lock
Labels: EDTR Prototype, EDTR v2, category:assets, type:task 🧹

#2382 Avoid fatal errors when permanently deleting registrations
  admin_pages/registrations/Registrations_Admin_Page.core.php
Labels: category:admin-pages, type:bug 🐞

#2353 Refactor forms | Closes #2346
  assets/src/application/ui/forms/espressoForm/RenderField.tsx
  assets/src/application/ui/forms/espressoForm/RenderFields.tsx
  assets/src/application/ui/forms/espressoForm/RenderSection.tsx
  assets/src/application/ui/forms/espressoForm/RenderSections.tsx
  assets/src/application/ui/forms/espressoForm/ResetButton.tsx
  assets/src/application/ui/forms/espressoForm/Submit.tsx
  assets/src/application/ui/forms/espressoForm/adapters/Button.tsx
  assets/src/application/ui/forms/espressoForm/adapters/Form.tsx
  assets/src/application/ui/forms/espressoForm/adapters/FormItem.tsx
  assets/src/application/ui/forms/espressoForm/adapters/MappedField.tsx
  assets/src/application/ui/forms/espressoForm/adapters/MultiCheck.tsx
  assets/src/application/ui/forms/espressoForm/adapters/Number.tsx
  assets/src/application/ui/forms/espressoForm/adapters/Radio.tsx
  assets/src/application/ui/forms/espressoForm/adapters/Select.tsx
  assets/src/application/ui/forms/espressoForm/adapters/Switch.tsx
  assets/src/application/ui/forms/espressoForm/adapters/Text.tsx
  assets/src/application/ui/forms/espressoForm/adapters/TextArea.tsx
  assets/src/application/ui/forms/espressoForm/adapters/index.ts
  assets/src/application/ui/forms/espressoForm/adapters/types.ts
  assets/src/application/ui/forms/espressoForm/config.tsx
  assets/src/application/ui/forms/espressoForm/context.ts
  assets/src/application/ui/forms/espressoForm/fields/Field.tsx
  assets/src/application/ui/forms/espressoForm/fields/Group.tsx
  assets/src/application/ui/forms/espressoForm/fields/Repeatable.tsx
  assets/src/application/ui/forms/espressoForm/fields/index.ts
  assets/src/application/ui/forms/espressoForm/hooks/useFormItemLayout.ts
  assets/src/application/ui/forms/espressoForm/hooks/useShouldBeVisible.ts
  assets/src/application/ui/forms/espressoForm/index.tsx
  assets/src/application/ui/forms/espressoForm/renderers/FieldRenderer.tsx
  assets/src/application/ui/forms/espressoForm/renderers/FormRenderer.tsx
  assets/src/application/ui/forms/espressoForm/renderers/RepeatableRenderer.tsx
  assets/src/application/ui/forms/espressoForm/styles.scss
  assets/src/application/ui/forms/espressoForm/types.ts
  assets/src/application/ui/forms/espressoForm/utils.ts
  package.json
  yarn.lock
Labels: EDTR v2, status:review

#2381 Migrate entity details panel | Closes #2354
  assets/src/application/services/apollo/mutations/types.ts
  assets/src/application/services/utilities/parseInfinity.ts
  assets/src/application/ui/enityDetails/DetailsSeparator.tsx
  assets/src/application/ui/enityDetails/EntityDetail.tsx
  assets/src/application/ui/enityDetails/EntityDetailsPanel.tsx
  assets/src/application/ui/enityDetails/index.ts
  assets/src/application/ui/enityDetails/style.css
  assets/src/application/ui/enityDetails/types.ts
  assets/src/application/valueObjects/InfinitySymbol.tsx
  assets/src/domain/eventEditor/ui/datetimes/DateRegistrationsLink.tsx
  assets/src/domain/eventEditor/ui/datetimes/dateCard/DateCard.tsx
  assets/src/domain/eventEditor/ui/datetimes/dateCard/DateDetails.tsx
  assets/src/domain/eventEditor/ui/tickets/TicketRegistrationsLink.tsx
  assets/src/domain/eventEditor/ui/tickets/hooks/useTicketRegistrationCount.ts
  assets/src/domain/eventEditor/ui/tickets/ticketCard/TicketCard.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketCard/TicketDetails.tsx
Labels: EDTR v2, status:review, type:enhancement 🎉

#2376 Refactor entity action menu | Closes #2352
  assets/src/application/ui/layout/entityActionMenu/index.ts
  assets/src/application/ui/layout/entityActionMenu/types.ts
  assets/src/application/ui/layout/entityActionMenu/useEntityActions.ts
  assets/src/application/ui/layout/entityActionMenu/useEntityActionsManager.ts
  assets/src/domain/eventEditor/hooks/useEditorInitialization.ts
  assets/src/domain/eventEditor/ui/datetimes/dateCard/DateActionsMenu.tsx
  assets/src/domain/eventEditor/ui/datetimes/dateCard/DateCard.tsx
  assets/src/domain/eventEditor/ui/datetimes/dateCard/EditDateButton.tsx
  assets/src/domain/eventEditor/ui/datetimes/hooks/useDatesActionMenuHandler.tsx
  assets/src/domain/eventEditor/ui/datetimes/hooks/useDatesActionMenuItems.ts
  assets/src/domain/eventEditor/ui/datetimes/types.ts
  assets/src/domain/eventEditor/ui/entityActionMenu/index.ts
  assets/src/domain/eventEditor/ui/entityActionMenu/types.ts
  assets/src/domain/eventEditor/ui/entityActionMenu/useEntityActionMenuItems.tsx
  assets/src/domain/eventEditor/ui/entityActionMenu/useEntityActionMenuSubscription.ts
  assets/src/domain/eventEditor/ui/tickets/hooks/useTicketsActionMenuHandler.tsx
  assets/src/domain/eventEditor/ui/tickets/hooks/useTicketsActionMenuItems.ts
  assets/src/domain/eventEditor/ui/tickets/ticketCard/DeleteTicketButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketCard/EditTicketButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketCard/TicketActionsMenu.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketCard/TicketCard.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/buttons/TicketPriceCalculatorButton.tsx
  assets/src/domain/eventEditor/ui/tickets/types.ts
  package.json
  yarn.lock
Labels: EDTR v2, status:review

#2387 Refactor form modal | Closes #2383
  assets/src/application/ui/forms/formModal/FormModal.tsx
  assets/src/application/ui/forms/formModal/FormModalForm.tsx
  assets/src/domain/eventEditor/ui/datetimes/dateForm/DateForm.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketForm/TicketForm.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/TicketPriceCalculatorForm.tsx
  assets/src/domain/shared/ui/RelationsSelector/index.tsx
Labels: EDTR v2, status:review

#2380 Add Unit Tests for Ticket Predicates (without filters); closes #2306.
  assets/src/domain/shared/entities/tickets/predicates/filters/expiredOnly/index.ts
  assets/src/domain/shared/entities/tickets/predicates/isExpired.ts
  assets/src/domain/shared/entities/tickets/predicates/isExpired/index.test.ts
  assets/src/domain/shared/entities/tickets/predicates/isExpired/index.ts
  assets/src/domain/shared/entities/tickets/predicates/isOnSale/index.test.ts
  assets/src/domain/shared/entities/tickets/predicates/isOnSale/index.ts
  assets/src/domain/shared/entities/tickets/predicates/isPending/index.test.ts
  assets/src/domain/shared/entities/tickets/predicates/isPending/index.ts
  assets/src/domain/shared/entities/tickets/predicates/isValidOrTrashed/index.test.ts
  assets/src/domain/shared/entities/tickets/predicates/isValidOrTrashed/index.ts
  assets/src/domain/shared/entities/tickets/predicates/selectionPredicates.ts
  assets/src/domain/shared/entities/tickets/predicates/selectionPredicates/index.test.ts
  assets/src/domain/shared/entities/tickets/predicates/selectionPredicates/index.ts
  assets/src/domain/shared/entities/tickets/predicates/ticketFields.ts
Labels: EDTR v2, category:unit-tests

#2388 Fix tests related to timezones | Closes #2385
  assets/src/application/services/hooks/test/useTimeZoneTime.test.tsx
  assets/src/domain/shared/entities/tickets/predicates/filters/onSaleOnly/index.test.ts
  assets/src/domain/shared/entities/tickets/predicates/isOnSale/index.ts
Labels: EDTR v2, category:unit-tests, status:review

#2389 Migrate Icon Menu Item; closes #2358.
  assets/ZZZ/components/ui/icon-menu-item/icon-menu-item.js
  assets/ZZZ/components/ui/icon-menu-item/style.css
  assets/src/application/ui/display/IconMenuItem/index.tsx
  assets/src/application/ui/display/IconMenuItem/style.scss
Labels: EDTR v2, category:assets, type:task 🧹

#2375 Move Medium Calendar Date
  assets/ZZZ/components/ui/dates-and-times/medium-calendar-date/index.js
  assets/ZZZ/components/ui/dates-and-times/medium-calendar-date/style.css
  assets/src/application/ui/calendars/dateDisplay/BiggieCalendarDate/index.tsx
  assets/src/application/ui/calendars/dateDisplay/MediumCalendarDate/index.tsx
  assets/src/application/ui/calendars/dateDisplay/MediumCalendarDate/style.css
  assets/src/application/ui/calendars/dateDisplay/index.ts
  assets/src/application/ui/calendars/dateDisplay/types.ts
  assets/src/application/ui/layout/entityList/index.ts
  assets/src/application/ui/layout/index.ts
  assets/src/domain/eventEditor/ui/datetimes/dateCard/DateCard.tsx
  tsconfig.json
Labels: EDTR v2, category:assets

#2365 Refactor Responsive Table Component; closes #2347.
  assets/src/application/ui/layout/espressoTable/EspressoDragSortingTable/index.tsx
  assets/src/application/ui/layout/espressoTable/EspressoDragSortingTable/styles.scss
  assets/src/application/ui/layout/espressoTable/EspressoTable.tsx
  assets/src/application/ui/layout/espressoTable/index.ts
  assets/src/application/ui/layout/espressoTable/style.css
  assets/src/application/ui/layout/index.ts
  package.json
  yarn.lock
Labels: EDTR v2, category:admin-page-ui-&-ux

#2390 Migrate Avatar Image; closes #2359.
  assets/ZZZ/components/ui/image/avatar.js
  assets/ZZZ/components/ui/image/test/index.js
  assets/src/application/ui/display/Avatar.tsx
  assets/src/application/ui/display/index.ts
  assets/src/application/ui/layout/espressoTable/EspressoTable.tsx
  yarn.lock
Labels: EDTR v2, category:assets, type:task 🧹

#2301 Document model IDs
  docs/G--Model-System/README.md
  docs/G--Model-System/model-querying.md
  docs/G--Model-System/models-primary-keys.md
Labels: category:models-and-data-infrastructure, status:review, type:documentation 📖

#2398 Fix eslint | Closes #2397
  .eslintrc.json
  assets/src/application/services/config/test/data.ts
  assets/src/application/services/context/test/ConfigProvider.test.tsx
  assets/src/application/services/context/test/RelationsProvider.test.tsx
  assets/src/application/services/context/test/StatusProvider.test.tsx
  assets/src/application/services/hooks/useRect.ts
  assets/src/application/services/utilities/date/test/diff/diff.ISOWeekYears.test.ts
  assets/src/application/services/utilities/date/test/diff/diff.businessDays.test.ts
  assets/src/application/services/utilities/date/test/diff/diff.calendarDays.test.ts
  assets/src/application/services/utilities/date/test/diff/diff.calendarISOWeekYears.test.ts
  assets/src/application/services/utilities/date/test/diff/diff.calendarISOWeeks.test.ts
  assets/src/application/services/utilities/date/test/diff/diff.calendarMonths.test.ts
  assets/src/application/services/utilities/date/test/diff/diff.calendarQuarters.test.ts
  assets/src/application/services/utilities/date/test/diff/diff.calendarWeeks.test.ts
  assets/src/application/services/utilities/date/test/diff/diff.calendarYears.test.ts
  assets/src/application/services/utilities/date/test/diff/diff.days.test.ts
  assets/src/application/services/utilities/date/test/diff/diff.hours.test.ts
  assets/src/application/services/utilities/date/test/diff/diff.milliseconds.test.ts
  assets/src/application/services/utilities/date/test/diff/diff.minutes.test.ts
  assets/src/application/services/utilities/date/test/diff/diff.months.test.ts
  assets/src/application/services/utilities/date/test/diff/diff.quarters.test.ts
  assets/src/application/services/utilities/date/test/diff/diff.seconds.test.ts
  assets/src/application/services/utilities/date/test/diff/diff.weeks.test.ts
  assets/src/application/services/utilities/date/test/diff/diff.years.test.ts
  assets/src/domain/eventEditor/services/context/EventEditorContext/ContextProviders.test.tsx
  assets/src/domain/eventEditor/services/context/TestContext/useResetApolloCache.ts
  assets/src/domain/shared/entities/datetimes/predicates/filters/recentlyExpiredOnly/index.test.ts
  assets/src/domain/shared/entities/tickets/predicates/filters/nextOnSaleOrPendingOnly/index.test.ts
  assets/src/domain/shared/entities/tickets/predicates/isPending/index.ts
  assets/src/domain/shared/types.d.ts
  config/webpack.config.js
  package.json
  yarn.lock
Labels: EDTR v2, status:review, type: tooling :hammer:

#2384 Move Calendar Date Range to EDTR v2
  assets/src/application/constants/date-fns-formats.ts
  assets/src/application/ui/calendars/dateDisplay/BiggieCalendarDate/index.tsx
  assets/src/application/ui/calendars/dateDisplay/CalendarDateRange/index.tsx
  assets/src/application/ui/calendars/dateDisplay/MediumCalendarDate/index.tsx
  assets/src/application/ui/calendars/dateDisplay/MediumCalendarDate/style.css
  assets/src/application/ui/calendars/dateDisplay/index.ts
  assets/src/domain/eventEditor/ui/datetimes/dateCard/DateCard.tsx
Labels: EDTR v2, category:assets, status:review, type:task 🧹

#2401 Move Calendar Page Date to EDTR v2 closes #2349
  assets/ZZZ/components/ui/dates-and-times/calendar-page-date/index.js
  assets/ZZZ/components/ui/dates-and-times/calendar-page-date/style.css
  assets/src/application/ui/calendars/dateDisplay/CalendarPageDate/index.tsx
  assets/src/application/ui/calendars/dateDisplay/CalendarPageDate/style.scss
  assets/src/application/ui/calendars/dateDisplay/index.ts
Labels: EDTR v2, category:assets, status:review, type:task 🧹

#2402 Refactor mutators to typefy inputs | Closes #2399
  assets/src/application/services/apollo/mutations/index.ts
  assets/src/application/services/apollo/mutations/types.ts
  assets/src/application/services/apollo/mutations/useEntityMutation.ts
  assets/src/application/services/apollo/mutations/useEntityMutator.ts
  assets/src/application/services/apollo/mutations/useMutationHandler.ts
  assets/src/application/services/apollo/mutations/useMutator.ts
  assets/src/application/ui/forms/formModal/types.ts
  assets/src/application/ui/layout/editorModal/types.ts
  assets/src/domain/eventEditor/services/apollo/mutations/datetimes/index.ts
  assets/src/domain/eventEditor/services/apollo/mutations/datetimes/test/createDatetime.test.ts
  assets/src/domain/eventEditor/services/apollo/mutations/datetimes/test/deleteDatetime.test.ts
  assets/src/domain/eventEditor/services/apollo/mutations/datetimes/test/updateDatetime.test.ts
  assets/src/domain/eventEditor/services/apollo/mutations/datetimes/types.ts
  assets/src/domain/eventEditor/services/apollo/mutations/datetimes/useDatetimeMutationHandler.ts
  assets/src/domain/eventEditor/services/apollo/mutations/datetimes/useDatetimeMutator.ts
  assets/src/domain/eventEditor/services/apollo/mutations/datetimes/useMutationVariables.ts
  assets/src/domain/eventEditor/services/apollo/mutations/index.ts
  assets/src/domain/eventEditor/services/apollo/mutations/prices/index.ts
  assets/src/domain/eventEditor/services/apollo/mutations/prices/test/createPrice.test.ts
  assets/src/domain/eventEditor/services/apollo/mutations/prices/test/deletePrice.test.ts
  assets/src/domain/eventEditor/services/apollo/mutations/prices/test/updatePrice.test.ts
  assets/src/domain/eventEditor/services/apollo/mutations/prices/types.ts
  assets/src/domain/eventEditor/services/apollo/mutations/prices/usePriceMutationHandler.ts
  assets/src/domain/eventEditor/services/apollo/mutations/prices/usePriceMutator.ts
  assets/src/domain/eventEditor/services/apollo/mutations/tickets/index.ts
  assets/src/domain/eventEditor/services/apollo/mutations/tickets/test/createTicket.test.ts
  assets/src/domain/eventEditor/services/apollo/mutations/tickets/test/deleteTicket.test.ts
  assets/src/domain/eventEditor/services/apollo/mutations/tickets/test/updateTicket.test.ts
  assets/src/domain/eventEditor/services/apollo/mutations/tickets/types.ts
  assets/src/domain/eventEditor/services/apollo/mutations/tickets/useMutationVariables.ts
  assets/src/domain/eventEditor/services/apollo/mutations/tickets/useTicketMutationHandler.ts
  assets/src/domain/eventEditor/services/apollo/mutations/tickets/useTicketMutator.ts
  assets/src/domain/eventEditor/services/apollo/mutations/types.ts
  assets/src/domain/eventEditor/services/apollo/mutations/useMutationHandler.ts
  assets/src/domain/eventEditor/services/apollo/mutations/useMutationOptions.ts
  assets/src/domain/eventEditor/services/apollo/mutations/useMutator.ts
  assets/src/domain/eventEditor/services/apollo/mutations/useMutators.ts
  assets/src/domain/eventEditor/services/apollo/types.ts
  assets/src/domain/eventEditor/ui/datetimes/dateCard/DateCard.tsx
  assets/src/domain/eventEditor/ui/datetimes/dateCard/DateDetails.tsx
  assets/src/domain/eventEditor/ui/datetimes/dateCard/DeleteDateButton.tsx
  assets/src/domain/eventEditor/ui/datetimes/useAddDatetimeModal.tsx
  assets/src/domain/eventEditor/ui/datetimes/useEditDatetimeModal.tsx
  assets/src/domain/eventEditor/ui/tickets/hooks/useDeleteTicketHandler.ts
  assets/src/domain/eventEditor/ui/tickets/ticketCard/TicketCard.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketCard/TicketDetails.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/defaultPriceModifier.ts
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/hooks/useOnSubmitPrices.ts
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/hooks/useTicketPriceCalculatorModal.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/types.ts
  assets/src/domain/eventEditor/ui/tickets/useAddTicketModal.tsx
  assets/src/domain/eventEditor/ui/tickets/useEditTicketModal.tsx
  assets/src/domain/shared/entities/prices/predicates/priceFields.ts
  assets/src/domain/shared/entities/prices/predicates/selectionPredicates/index.ts
  assets/src/domain/shared/entities/prices/predicates/updatePredicates.ts
  assets/src/domain/shared/entities/tickets/predicates/selectionPredicates/index.ts
  assets/src/domain/shared/entities/tickets/predicates/ticketFields.ts
  assets/src/domain/shared/entities/tickets/predicates/updatePredicates.ts
  package.json
Labels: EDTR v2, status:review, type:code-quality 👾

#2408 Update useSuccessToast to make it use AntD notifications; closes #2396.
  assets/src/application/services/toaster/types.ts
  assets/src/application/services/toaster/useDismissToast.tsx
  assets/src/application/services/toaster/useErrorToast.tsx
  assets/src/application/services/toaster/useInfoToast.tsx
  assets/src/application/services/toaster/useLoadingToast.tsx
  assets/src/application/services/toaster/useSuccessToast.tsx
  assets/src/application/services/toaster/useToaster.tsx
Labels: EDTR v2, category:assets, type:task 🧹

#2409 Improve EspressoForm & FormModal | Closes #2406
  assets/src/application/ui/forms/espressoForm/EspressoForm.tsx
  assets/src/application/ui/forms/espressoForm/TestForm.tsx
  assets/src/application/ui/forms/espressoForm/index.tsx
  assets/src/application/ui/forms/espressoForm/renderers/FormRenderer.tsx
  assets/src/application/ui/forms/espressoForm/types.ts
  assets/src/application/ui/forms/formModal/FormModal.tsx
  assets/src/application/ui/forms/formModal/FormModalForm.tsx
  assets/src/application/ui/forms/formModal/FormRenderer.tsx
  assets/src/application/ui/forms/formModal/types.ts
  assets/src/domain/eventEditor/ui/EventEditor.tsx
Labels: EDTR v2, type:enhancement 🎉

#2405 Refactor inline edit input | Closes #2391
  assets/src/application/ui/input/CurrencyInput/index.tsx
  assets/src/application/ui/input/InlineEditInput/Editable.tsx
  assets/src/application/ui/input/InlineEditInput/InlineEditHeading.tsx
  assets/src/application/ui/input/InlineEditInput/InlineEditText.tsx
  assets/src/application/ui/input/InlineEditInput/InlineEditTextArea.tsx
  assets/src/application/ui/input/InlineEditInput/index.tsx
  assets/src/application/ui/input/InlineEditInput/style.css
  assets/src/application/ui/input/InlineEditInput/types.ts
  assets/src/application/ui/input/index.ts
  assets/src/domain/eventEditor/ui/datetimes/dateCard/DateCard.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketCard/TicketCard.tsx
Labels: EDTR v2, type:enhancement 🎉

#2412 Date details form with custom Date/Time inputs | Closes #2394
  assets/src/application/constants/dateFnsFormats.ts
  assets/src/application/constants/momentFormats.ts
  assets/src/application/services/apollo/mutations/useMutationHandler.ts
  assets/src/application/ui/calendars/dateDisplay/BiggieCalendarDate/index.tsx
  assets/src/application/ui/calendars/dateDisplay/CalendarDateRange/index.tsx
  assets/src/application/ui/calendars/dateDisplay/CalendarPageDate/index.tsx
  assets/src/application/ui/calendars/dateDisplay/MediumCalendarDate/index.tsx
  assets/src/application/ui/forms/espressoForm/EspressoForm.tsx
  assets/src/application/ui/forms/espressoForm/RenderSection.tsx
  assets/src/application/ui/forms/espressoForm/ResetButton.tsx
  assets/src/application/ui/forms/espressoForm/Submit.tsx
  assets/src/application/ui/forms/espressoForm/adapters/Form.tsx
  assets/src/application/ui/forms/espressoForm/adapters/MappedField.tsx
  assets/src/application/ui/forms/espressoForm/adapters/index.ts
  assets/src/application/ui/forms/espressoForm/adapters/types.ts
  assets/src/application/ui/forms/espressoForm/fields/Group.tsx
  assets/src/application/ui/forms/espressoForm/renderers/FieldRenderer.tsx
  assets/src/application/ui/forms/espressoForm/renderers/FormRenderer.tsx
  assets/src/application/ui/forms/espressoForm/renderers/RepeatableRenderer.tsx
  assets/src/application/ui/forms/espressoForm/styles.scss
  assets/src/application/ui/forms/espressoForm/types.ts
  assets/src/application/ui/forms/formModal/FormModal.tsx
  assets/src/application/ui/forms/formModal/FormModalForm.tsx
  assets/src/application/ui/forms/formModal/types.ts
  assets/src/application/ui/input/Button.tsx
  assets/src/application/ui/input/DateTimePicker/CustomDate.ts
  assets/src/application/ui/input/DateTimePicker/DatePicker.tsx
  assets/src/application/ui/input/DateTimePicker/DatePickerBase.tsx
  assets/src/application/ui/input/DateTimePicker/TimePicker.tsx
  assets/src/application/ui/input/DateTimePicker/TimePickerBase.tsx
  assets/src/application/ui/input/DateTimePicker/index.ts
  assets/src/application/ui/input/EspressoButton/index.tsx
  assets/src/application/ui/input/EspressoButton/types.ts
  assets/src/application/ui/input/MultiCheck.tsx
  assets/src/application/ui/input/Number.tsx
  assets/src/application/ui/input/Radio.tsx
  assets/src/application/ui/input/Select.tsx
  assets/src/application/ui/input/Switch.tsx
  assets/src/application/ui/input/Text.tsx
  assets/src/application/ui/input/TextArea.tsx
  assets/src/application/ui/input/index.ts
  assets/src/application/ui/input/types.ts
  assets/src/application/ui/layout/editorModal/types.ts
  assets/src/application/ui/layout/espressoTable/EspressoDragSortingTable/index.tsx
  assets/src/application/ui/layout/espressoTable/EspressoTable.tsx
  assets/src/application/ui/layout/espressoTable/index.ts
  assets/src/application/ui/layout/index.ts
  assets/src/domain/eventEditor/services/apollo/queries/events/index.ts
  assets/src/domain/eventEditor/services/apollo/queries/events/useEvent.ts
  assets/src/domain/eventEditor/services/apollo/queries/useCacheQuery.ts
  assets/src/domain/eventEditor/services/apollo/types.ts
  assets/src/domain/eventEditor/ui/datetimes/dateForm/useDateFormConfig.ts
  assets/src/domain/eventEditor/ui/datetimes/useAddDatetimeModal.tsx
  assets/src/domain/eventEditor/ui/datetimes/useEditDatetimeModal.tsx
  assets/src/domain/shared/ui/dateRangeInput/dateDisplay.tsx
  assets/src/domain/shared/ui/editorModal/types.ts
  package.json
  yarn.lock
Labels: EDTR v2, status:review, type:enhancement 🎉

#2420 Complete server-side GQL mutations | Closes #2417
  assets/src/domain/eventEditor/services/apollo/mutations/datetimes/types.ts
  assets/src/domain/eventEditor/services/apollo/mutations/tickets/types.ts
  core/domain/services/graphql/data/mutations/DatetimeMutation.php
  core/domain/services/graphql/data/mutations/PriceMutation.php
  core/domain/services/graphql/data/mutations/TicketMutation.php
  core/domain/services/graphql/types/Datetime.php
  core/domain/services/graphql/types/Price.php
  core/domain/services/graphql/types/Ticket.php
Labels: EDTR v2, category:models-and-data-infrastructure, status:review

#2422 Fix local/UTC timezone issue for EDTR | Closes #2421
  core/services/graphql/types/TypeBase.php
Labels: EDTR v2, type:bug 🐞

#2400 Refactor Responsive Table Component; closes #2347.
  assets/ZZZ/components/ui/responsive-table/index.js
  assets/ZZZ/components/ui/responsive-table/responsive-cell.js
  assets/ZZZ/components/ui/responsive-table/responsive-table.js
  assets/ZZZ/components/ui/responsive-table/style.css
  assets/ZZZ/components/ui/responsive-table/table-body.js
  assets/ZZZ/components/ui/responsive-table/table-footer.js
  assets/ZZZ/components/ui/responsive-table/table-header-cell.js
  assets/ZZZ/components/ui/responsive-table/table-header.js
  assets/ZZZ/components/ui/responsive-table/utils.js
  assets/ZZZ/editor/events/dates-and-times/editor-date/datesListView/dates-list-table-header.js
  assets/ZZZ/editor/events/dates-and-times/editor-date/datesListView/dates-list-table-row.js
  assets/ZZZ/editor/events/dates-and-times/editor-date/datesListView/editor-date-entities-list-view.css
  assets/ZZZ/editor/events/dates-and-times/editor-date/datesListView/editor-date-entities-list-view.js
  assets/ZZZ/editor/events/dates-and-times/editor-date/datesListView/index.js
  assets/ZZZ/editor/events/dates-and-times/editor-date/datesListView/use-reorder-dates.js
  assets/src/application/ui/layout/espressoTable/ResponsiveCell.js
  assets/src/application/ui/layout/espressoTable/ResponsiveTable.js
  assets/src/application/ui/layout/espressoTable/Table.js
  assets/src/application/ui/layout/espressoTable/TableBody.js
  assets/src/application/ui/layout/espressoTable/TableDataCell.js
  assets/src/application/ui/layout/espressoTable/TableFooter.js
  assets/src/application/ui/layout/espressoTable/TableHeader.js
  assets/src/application/ui/layout/espressoTable/TableHeaderCell.js
  assets/src/application/ui/layout/espressoTable/TableRow.js
  assets/src/application/ui/layout/espressoTable/index.js
  assets/src/application/ui/layout/espressoTable/utils.js
  assets/src/domain/eventEditor/ui/datetimes/datesList/listView/DatesListView.js
  assets/src/domain/eventEditor/ui/datetimes/datesList/listView/datesListTableHeader.js
  assets/src/domain/eventEditor/ui/datetimes/datesList/listView/datesListTableRow.js
  assets/src/domain/eventEditor/ui/datetimes/datesList/listView/editor-date-entities-list-view.css
  assets/src/domain/eventEditor/ui/datetimes/datesList/listView/index.js
  package.json
  yarn.lock
Labels: EDTR v2, category:assets, type:task 🧹

#2429 Create hidden input | Closes #2426
  assets/src/application/ui/forms/espressoForm/adapters/MappedField.tsx
  assets/src/application/ui/forms/espressoForm/renderers/FieldRenderer.tsx
  assets/src/application/ui/forms/espressoForm/types.ts
  assets/src/application/ui/input/Hidden.tsx
  assets/src/application/ui/input/index.ts
Labels: EDTR v2, type:enhancement 🎉

#2430 Add validations and other form config | Closes #2427
  assets/src/application/ui/forms/espressoForm/Submit.tsx
  assets/src/application/ui/forms/espressoForm/adapters/MappedField.tsx
  assets/src/application/ui/forms/espressoForm/index.tsx
  assets/src/application/ui/forms/espressoForm/renderers/FieldRenderer.tsx
  assets/src/application/ui/forms/espressoForm/renderers/FormRenderer.tsx
  assets/src/application/ui/forms/espressoForm/utils.ts
  assets/src/application/ui/forms/formModal/FormModalForm.tsx
  assets/src/domain/eventEditor/ui/datetimes/dateForm/formValidation.ts
  assets/src/domain/eventEditor/ui/datetimes/dateForm/types.ts
  assets/src/domain/eventEditor/ui/datetimes/dateForm/useDateFormConfig.ts
  assets/src/domain/eventEditor/ui/tickets/ticketForm/formValidation.ts
  assets/src/domain/eventEditor/ui/tickets/ticketForm/types.ts
  assets/src/domain/eventEditor/ui/tickets/ticketForm/useTicketFormConfig.tsx
  assets/src/domain/shared/services/utils/dateAndTime.ts
  assets/src/domain/shared/services/utils/processDateAndTime.ts
  package.json
  yarn.lock
Labels: EDTR v2, type:enhancement 🎉

#2413 Fix overflowing Event Notifications metabox in WP 5.4; Fixes #2410
  core/admin/assets/ee-admin-page.css
Labels: category:accessibility, type:bug 🐞

#2445 Relocate dates UI files | Closes #2442
  assets/src/domain/eventEditor/ui/datetimes/DateRegistrationsLink.tsx
  assets/src/domain/eventEditor/ui/datetimes/DatetimeIdTag.tsx
  assets/src/domain/eventEditor/ui/datetimes/dateCard/style.css
  assets/src/domain/eventEditor/ui/datetimes/dateForm/DateForm.tsx
  assets/src/domain/eventEditor/ui/datetimes/dateForm/style.ts
  assets/src/domain/eventEditor/ui/datetimes/dateForm/useDateFormConfig.ts
  assets/src/domain/eventEditor/ui/datetimes/datesList/AddNewDateButton.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/List.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/actionsMenu/DateActionsMenu.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/actionsMenu/DeleteDateButton.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/actionsMenu/EditDateButton.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/cardView/DateCard.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/cardView/DateDetails.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/index.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/tableView/DatesListView.js
  assets/src/domain/eventEditor/ui/datetimes/datesList/tableView/datesListTableHeader.js
  assets/src/domain/eventEditor/ui/datetimes/datesList/tableView/datesListTableRow.js
  assets/src/domain/eventEditor/ui/datetimes/datesList/tableView/editor-date-entities-list-view.css
  assets/src/domain/eventEditor/ui/datetimes/datesList/tableView/index.js
  assets/src/domain/eventEditor/ui/datetimes/hooks/useDatesActionMenuHandler.tsx
  assets/src/domain/eventEditor/ui/datetimes/hooks/useDatesActionMenuItems.ts
  assets/src/domain/eventEditor/ui/datetimes/types.ts
Labels: EDTR v2, status:review, type:task 🧹

#2446 Relocate tickets UI files | Closes #2443
  assets/src/domain/eventEditor/ui/datetimes/dateForm/formValidation.ts
  assets/src/domain/eventEditor/ui/datetimes/dateForm/types.ts
  assets/src/domain/eventEditor/ui/datetimes/dateForm/useDateFormConfig.ts
  assets/src/domain/eventEditor/ui/datetimes/datesList/cardView/DateCard.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/controls/DatesSortedControl.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/controls/DisplayDatesControl.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/controls/ShowDatesControl.tsx
  assets/src/domain/eventEditor/ui/tickets/TicketIdTag.tsx
  assets/src/domain/eventEditor/ui/tickets/TicketRegistrationsLink.tsx
  assets/src/domain/eventEditor/ui/tickets/hooks/useDeleteTicketHandler.ts
  assets/src/domain/eventEditor/ui/tickets/hooks/useTicketRegistrationCount.ts
  assets/src/domain/eventEditor/ui/tickets/hooks/useTicketsActionMenuHandler.tsx
  assets/src/domain/eventEditor/ui/tickets/hooks/useTicketsActionMenuItems.ts
  assets/src/domain/eventEditor/ui/tickets/ticketCard/styles.ts
  assets/src/domain/eventEditor/ui/tickets/ticketForm/TicketForm.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketForm/formValidation.ts
  assets/src/domain/eventEditor/ui/tickets/ticketForm/style.ts
  assets/src/domain/eventEditor/ui/tickets/ticketForm/types.ts
  assets/src/domain/eventEditor/ui/tickets/ticketForm/useTicketFormConfig.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/AddNewTicketButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/List.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/actionsMenu/DeleteTicketButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/actionsMenu/EditTicketButton.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/actionsMenu/TicketActionsMenu.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/cardView/TicketCard.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/cardView/TicketDetails.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/TicketListFilterBar.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/controls/DisplayTicketsControl.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/controls/ShowTicketsControl.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/controls/TicketsSortedByControl.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketsList/index.tsx
  assets/src/domain/eventEditor/ui/tickets/types.ts
  tsconfig.json
Labels: EDTR v2, type:task 🧹

#2393 Check for event object before generating iCal file
  modules/ical/EED_Ical.module.php
Labels: type:bug 🐞

#2462 Extract Global Apollo Types from Domain | Closes #2448
  assets/src/application/services/apollo/mutations/types.ts
  assets/src/application/services/apollo/mutations/useMutationHandler.ts
  assets/src/application/services/apollo/mutations/useMutator.ts
  assets/src/application/services/apollo/relations/types.ts
  assets/src/application/services/apollo/types.ts
  assets/src/application/services/utilities/text/entityFieldSearch/index.ts
  assets/src/application/services/utilities/text/shortenGuid/index.ts
  assets/src/application/ui/display/EntityIDs/index.tsx
  assets/src/application/ui/layout/EntityCard/types.ts
  assets/src/application/ui/layout/editorModal/types.ts
  assets/src/application/ui/layout/entityActionsMenu/types.ts
  assets/src/application/ui/layout/entityActionsMenu/useEntityActionsMenuItems.tsx
  assets/src/application/ui/layout/entityList/EntityList/index.tsx
  assets/src/domain/eventEditor/interfaces/types.ts
  assets/src/domain/eventEditor/services/apollo/mutations/datetimes/types.ts
  assets/src/domain/eventEditor/services/apollo/mutations/datetimes/useDatetimeMutationHandler.ts
  assets/src/domain/eventEditor/services/apollo/mutations/prices/types.ts
  assets/src/domain/eventEditor/services/apollo/mutations/tickets/types.ts
  assets/src/domain/eventEditor/services/apollo/mutations/tickets/useTicketMutationHandler.ts
  assets/src/domain/eventEditor/services/apollo/mutations/types.ts
  assets/src/domain/eventEditor/services/apollo/mutations/useMutationOptions.ts
  assets/src/domain/eventEditor/services/apollo/mutations/useMutator.ts
  assets/src/domain/eventEditor/services/apollo/queries/datetimes/useDatetimeIds.ts
  assets/src/domain/eventEditor/services/apollo/queries/index.ts
  assets/src/domain/eventEditor/services/apollo/queries/priceTypes/usePriceTypeForPrice.ts
  assets/src/domain/eventEditor/services/apollo/queries/priceTypes/usePriceTypes.ts
  assets/src/domain/eventEditor/services/apollo/queries/prices/usePriceQueryOptions.ts
  assets/src/domain/eventEditor/services/apollo/queries/prices/usePrices.ts
  assets/src/domain/eventEditor/services/apollo/queries/tickets/useTicketIds.ts
  assets/src/domain/eventEditor/services/apollo/queries/tickets/useTicketPrices.ts
  assets/src/domain/eventEditor/services/apollo/queries/tickets/useTicketQueryOptions.ts
  assets/src/domain/eventEditor/services/apollo/queries/types.ts
  assets/src/domain/eventEditor/services/apollo/types.ts
  assets/src/domain/eventEditor/services/context/types.ts
  assets/src/domain/eventEditor/ui/datetimes/dateForm/useDateFormConfig.ts
  assets/src/domain/eventEditor/ui/datetimes/types.ts
  assets/src/domain/eventEditor/ui/tickets/hooks/useTicketRegistrationCount.ts
  assets/src/domain/eventEditor/ui/tickets/ticketForm/useTicketFormConfig.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/hooks/useOnSubmitPrices.ts
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/hooks/useTicketPriceCalculatorModal.tsx
  assets/src/domain/eventEditor/ui/tickets/ticketPriceCalculator/types.ts
  assets/src/domain/eventEditor/ui/tickets/types.ts
  assets/src/domain/shared/entities/prices/predicates/selectionPredicates/index.ts
  assets/src/domain/shared/entities/tickets/predicates/selectionPredicates/index.ts
  assets/src/domain/shared/services/predicates/isTrashed/index.ts
  assets/src/domain/shared/services/predicates/isValidOrTrashed/index.ts
  assets/src/domain/shared/services/predicates/selectionById/index.ts
  assets/src/domain/shared/ui/editorModal/types.ts
Labels: EDTR v2, status:review, type:code-quality 👾

#2463 Espresso form tooltips | Closes #2449
  assets/src/application/ui/forms/espressoForm/renderers/FieldRenderer.tsx
  assets/src/application/ui/forms/espressoForm/styles.scss
  assets/src/domain/eventEditor/ui/datetimes/dateForm/useDateFormConfig.ts
  assets/src/domain/eventEditor/ui/tickets/ticketForm/useTicketFormConfig.tsx
Labels: EDTR v2, status:review, type:enhancement 🎉

#2465 Remove the Codebase redirect URL.
  core/admin/templates/espresso_ratings_request_content.template.php
Labels: category:admin-page-ui-&-ux

#2466 Refactor toaster/form submit feedback | Closes #2461, #2444
  assets/src/application/services/apollo/mutations/useMutationHandler.ts
  assets/src/application/services/context/ToastProvider.tsx
  assets/src/application/services/toaster/IconGraphQL.tsx
  assets/src/application/services/toaster/LoadingToast.tsx
  assets/src/application/services/toaster/index.ts
  assets/src/application/services/toaster/types.ts
  assets/src/application/services/toaster/useDismissToast.tsx
  assets/src/application/services/toaster/useErrorToast.tsx
  assets/src/application/services/toaster/useInfoToast.tsx
  assets/src/application/services/toaster/useInitToaster.tsx
  assets/src/application/services/toaster/useLoadingToast.ts
  assets/src/application/services/toaster/useLoadingToast.tsx
  assets/src/application/services/toaster/useSuccessToast.tsx
  assets/src/application/services/toaster/useToastManager.tsx
  assets/src/application/services/toaster/useToaster.tsx
  assets/src/application/services/toaster/useWarningToast.tsx
  assets/src/application/ui/forms/formModal/FormModalForm.tsx
  assets/src/domain/eventEditor/services/apollo/initialization/useInitQueries.ts
  assets/src/domain/eventEditor/services/apollo/queries/datetimes/useFetchDatetimes.ts
  assets/src/domain/eventEditor/services/apollo/queries/priceTypes/useFetchPriceTypes.ts
  assets/src/domain/eventEditor/services/apollo/queries/prices/useFetchPrices.ts
  assets/src/domain/eventEditor/services/apollo/queries/tickets/useFetchTickets.ts
Labels: EDTR v2, status:review, type:enhancement 🎉

#2431 Refactor datetimes list | part 1 | partially closes #2424.
  assets/src/application/ui/input/PerPageControl/index.tsx
  assets/src/application/ui/input/index.ts
  assets/src/application/ui/layout/entityList/EntityList/index.tsx
  assets/src/application/ui/layout/entityList/EntityList/types.ts
  assets/src/application/ui/layout/entityList/filterBar/Collapsible.tsx
  assets/src/application/ui/layout/entityList/filterBar/EntityListFilterBar.tsx
  assets/src/application/ui/layout/entityList/filterBar/useEntityListFilterState.ts
  assets/src/application/ui/layout/entityList/index.ts
  assets/src/application/ui/layout/entityList/pagination/EntityPagination.tsx
  assets/src/application/ui/layout/entityList/pagination/style.scss
  assets/src/application/ui/layout/entityList/pagination/types.ts
  assets/src/application/ui/layout/entityList/pagination/useEntityPagination.js
  assets/src/application/ui/layout/entityList/pagination/useEntityPagination.ts
  assets/src/application/ui/layout/espressoTable/ResponsiveCell.js
  assets/src/application/ui/layout/espressoTable/ResponsiveTable.tsx
  assets/src/application/ui/layout/espressoTable/Table.js
  assets/src/application/ui/layout/espressoTable/TableBody.js
  assets/src/application/ui/layout/espressoTable/TableDataCell.js
  assets/src/application/ui/layout/espressoTable/TableFooter.js
  assets/src/application/ui/layout/espressoTable/TableHeader.js
  assets/src/application/ui/layout/espressoTable/TableHeaderCell.js
  assets/src/application/ui/layout/espressoTable/TableRow.js
  assets/src/application/ui/layout/espressoTable/style.scss
  assets/src/domain/eventEditor/ui/datetimes/datesList/List.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/cardView/CardView.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/cardView/index.ts
  assets/src/domain/eventEditor/ui/datetimes/datesList/cardView/styles.scss
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/DatesListEntityFilters.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/DatesListFilterBar.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/filterBar/useDatesListFilterState/index.ts
  assets/src/domain/eventEditor/ui/datetimes/datesList/styles.scss
  assets/src/domain/eventEditor/ui/datetimes/datesList/tableView/TableView.tsx
  assets/src/domain/eventEditor/ui/datetimes/datesList/tableView/index.js
  assets/src/domain/eventEditor/ui/datetimes/datesList/tableView/index.ts
  assets/src/domain/eventEditor/ui/tickets/ticketsList/filterBar/TicketListFilterBar.tsx
Labels: EDTR v2, type:task 🧹

#2467 ADD: Filters for edit name and desction / line item details
  core/libraries/line_item_display/EE_Admin_Table_Line_Item_Display_Strategy.strategy.php
  core/libraries/line_item_display/EE_Admin_Table_Registration_Line_Item_Display_Strategy.strategy.php
  core/libraries/line_item_display/EE_SPCO_Line_Item_Display_Strategy.strategy.php
Labels: category:community-contribution, type:enhancement 🎉

#2464 Switch to using a timestamp on the Event admin list month_range query.
  admin_pages/events/Events_Admin_Page.core.php
Labels: category:admin-pages, status:needs-testing

#2447 Fet/live event msg preview
  admin_pages/messages/Messages_Admin_Page.core.php
  core/libraries/messages/EE_messenger.lib.php
Labels: category:admin-page-ui-&-ux, category:messaging-&-messengers, status:needs-testing, type:enhancement 🎉
