Repository eventespresso/event-espresso-core, pull requests merged in 2021-10, with the labels that each got.

#3541 Add Auto-rebase workflow
  .github/workflows/rebase.yml
Labels: category:CI-CD-pipeline

#3529 Add a deploy workflow for demoee
  .github/workflows/deploy-to-demoee.yml
  .github/workflows/rebase.yml
Labels: status:review

#3543 Replace Support Requests App With GitHub Action
  .github/support.yml
  .github/workflows/support.yml
Labels: type:build-process 🔨, category:CI-CD-pipeline
