Repository eventespresso/event-espresso-core, pull requests merged in 2021-04, with the labels that each got.

#3320 Remove (and replace) the 'hidden' class from the ee modal then its shown/hidden
  core/admin/assets/ee-dialog-helper.js
Labels: status:merge

#3361 Cast global $post_type to string when running add_meta_boxes hook.
  core/admin/templates/admin_details_wrapper.template.php
Labels: category:admin-pages

#3359 Request Routing Fixes
  core/EE_Dependency_Map.core.php
  core/EE_System.core.php
  core/domain/entities/routing/handlers/shared/RestApiRequests.php
  core/domain/entities/routing/specifications/admin/WordPressPluginsPage.php
  core/libraries/rest_api/calculations/CalculatedModelFieldsFactory.php
  core/services/request/Request.php
  core/services/request/RequestInterface.php
  core/services/routing/RouteHandler.php
  tests/includes/EE_REST_TestCase.php
  tests/mocks/core/domain/entities/routing/handlers/shared/RestApiRequestsMock.php
  tests/mocks/core/services/request/RequestMock.php
  tests/testcases/core/EE_Dependency_Map_Test.php
  tests/testcases/core/libraries/rest_api/controllers/Checkin_Test.php
Labels: category:general, priority:normal, status:review, type:enhancement 🎉

#3365 Fix Data Type Passed to Question Model Method
  admin_pages/registration_form/Registration_Form_Admin_Page.core.php
Labels: category:models-and-data-infrastructure, priority:normal, type:bug 🐞

#3343 Allow payment methods to pass arrays as values in redirect_args
  core/db_classes/EE_Payment.class.php
Labels: category:payment-methods, status:please-fix, type:enhancement 🎉
