Repository eventespresso/event-espresso-core, pull requests merged in 2022-08, with the labels that each got.

#3989 Add Prep Decaf Release Workflow
  .github/workflows/prep-decaf-release.yml
Labels: type:build-process 🔨, priority:normal, status:review, category:decaf

#3988 Update CrawlerDetect
  core/services/request/middleware/BotDetector.php
  core/third_party_libs/CrawlerDetect/CrawlerDetect.php
  core/third_party_libs/CrawlerDetect/Fixtures/AbstractProvider.php
  core/third_party_libs/CrawlerDetect/Fixtures/Crawlers.php
  core/third_party_libs/CrawlerDetect/Fixtures/Exclusions.php
  core/third_party_libs/CrawlerDetect/Fixtures/Headers.php
Labels: category:3rd-party-integrations, type:task 🧹, priority:normal, status:review

#3991 Fix CNT_ISO3 field not being pulled from the request
  admin_pages/general_settings/General_Settings_Admin_Page.core.php
Labels: type:bug 🐞, priority:high

#3994 Remove External Dependencies for Decaf
  admin_pages/about/templates/whats_new.template.php
  caffeinated/admin/extend/about/templates/whats_new.template.php
  core/templates/global_assets/images/banners/ee4-wait-list-manager-380x250.jpeg
  core/templates/global_assets/images/banners/event-registrations-with-paypal-express-checkout-smart-payment-buttons-380x250.jpeg
  core/templates/global_assets/images/banners/ticket-bundles-533x562.png
Labels: category:assets, type:task 🧹, category:decaf

#3997 Moved Accounting Library
  core/domain/services/assets/CoreAssetManager.php
  core/templates/global_assets/accounting/accounting.js
  core/templates/global_assets/accounting/accounting.min.js
Labels: category:3rd-party-integrations, type:task 🧹, category:decaf

#4001 Moved the jquery countdown library to global assets directory.
  core/templates/global_assets/scripts/jquery.countdown.min.js
  modules/single_page_checkout/EED_Single_Page_Checkout.module.php
Labels: category:3rd-party-integrations, type:task 🧹, category:decaf

#4000 Moved plugin jQuery file to global assets.
  core/templates/global_assets/scripts/jquery.plugin.min.js
  modules/single_page_checkout/EED_Single_Page_Checkout.module.php
Labels: category:3rd-party-integrations, type:task 🧹, category:decaf

#3999 Move JS Moment to Global Assets Directory
  core/admin/EE_Admin_Page.core.php
  core/templates/global_assets/moment/moment-timezone-with-data.min.js
  core/templates/global_assets/moment/moment-with-locales.min.js
Labels: category:3rd-party-integrations, type:task 🧹, category:decaf

#4004 Move qtip Library to Global Assets Directory
  core/helpers/EEH_Qtip_Loader.helper.php
  core/templates/global_assets/qtip/jquery.qtip.css
  core/templates/global_assets/qtip/jquery.qtip.js
  core/templates/global_assets/qtip/jquery.qtip.min.css
  core/templates/global_assets/qtip/jquery.qtip.min.js
  core/templates/global_assets/qtip/jquery.qtip.min.map
Labels: category:3rd-party-integrations, type:task 🧹, category:decaf

#3996 Remove Joyride
  admin_pages/about/templates/credits.template.php
  core/admin/EE_Admin.core.php
  core/admin/assets/ee-help-tour.js
  core/templates/global_assets/css/ee-joyride-styles.css
  core/third_party_libs/joyride/joyride-2.1.css
  core/third_party_libs/joyride/jquery.cookie.js
  core/third_party_libs/joyride/jquery.joyride-2.1.js
  core/third_party_libs/joyride/modernizr.mq.js
  docs/Z--General/third-party-libraries-in-use.md
Labels: category:3rd-party-integrations, type:task 🧹, category:decaf

#4005 Add Feature Flag for Jaybizzle Package
  core/services/request/middleware/BotDetector.php
Labels: category:3rd-party-integrations, type:task 🧹, category:decaf

#4006 Add Feature Flag for PluginUpdateEngineChecker Class
  core/libraries/plugin_api/EE_Register_Addon.lib.php
  core/services/licensing/LicenseService.php
Labels: category:3rd-party-integrations, type:task 🧹, category:decaf
