Repository eventespresso/event-espresso-core, pull requests merged in 2022-02, with the labels that each got.

#3694 Fixed Event Status Banner Not Showing in Block Themes.
  modules/event_single/EED_Event_Single.module.php
  modules/events_archive/EED_Events_Archive.module.php
Labels: category:templates-shortcodes-and-widgets, type:theme/plugin-conflict 💥, status:needs-testing

#3693 Fix Events Archive Config Reset
  caffeinated/admin/extend/events/Extend_Events_Admin_Page.core.php
  caffeinated/modules/events_archive_caff/EED_Events_Archive_Caff.module.php
  core/services/request/RequestParams.php
Labels: type:bug 🐞, category:admin-pages, priority:normal, status:merge

#3706 Fix PHP Notice When "send notification" Checkbox is Not Checked.
  core/business/EE_Registration_Processor.class.php
  core/third_party_libs/pue/pue-client.php
  modules/messages/EED_Messages.module.php
Labels: type:enhancement 🎉, category:messaging-&-messengers, status:merge

#3707 Remove "demoee" From "remoteNamesToPushTo"
  info.json
Labels: type:build-process 🔨, type:task 🧹, priority:high

#3681 Replace Legacy Request Data in Messages Admin
  admin_pages/messages/Messages_Admin_Page.core.php
  admin_pages/messages/assets/ee_message_admin.css
  admin_pages/messages/assets/ee_message_editor.js
  admin_pages/messages/templates/shortcode_selector_skeleton.template.php
  caffeinated/admin/extend/messages/espresso_events_Messages_Hooks_Extend.class.php
  core/admin/EE_Admin_Page.core.php
  core/helpers/EEH_Array.helper.php
  core/helpers/EEH_Form_Fields.helper.php
  core/helpers/EEH_MSG_Template.helper.php
  core/helpers/EEH_URL.helper.php
  core/libraries/messages/EE_Message_To_Generate.php
  core/libraries/messages/EE_Messages_Generator.lib.php
  core/libraries/messages/EE_Messages_Processor.lib.php
  core/libraries/messages/EE_Messages_Queue.lib.php
  core/libraries/messages/data_class/EE_Messages_Preview_incoming_data.class.php
  core/services/request/CurrentPage.php
  core/services/request/DataType.php
  core/services/request/Request.php
  core/services/request/RequestInterface.php
  core/services/request/RequestParams.php
  core/services/request/sanitizers/AllowedTags.php
  core/services/request/sanitizers/RequestSanitizer.php
  modules/messages/EED_Messages.module.php
  tests/mocks/modules/ticket_selector/RequestMock.php
Labels: type:enhancement 🎉, category:admin-pages, status:please-fix

#3729 Bump `composer/installers` to v2
  .gitattributes
  composer.json
  tests/includes/CoreLoader.php
Labels: type:build-process 🔨, category:unit-tests

#3730 Use Different Cache Keys for Linting and Unit Tests
  .github/workflows/ci-master.yml
Labels: type:build-process 🔨, category:unit-tests
